### ISSUE TITLE
优化文档签名标注

### ISSUE THREAD

**Issue by janryWang** [alibaba/uform#103]
目前文档签名标注不够规范，没有严格按照typescript标准来定义，同时，类型描述的也还不够完善

**Comment by monkindey** [comment]
看不太明白“签名标注”， 这个意思是啥？

**Comment by janryWang** [comment]
> 看不太明白“签名标注”， 这个意思是指？

![image](https://user-images.githubusercontent.com/4060976/59158310-f6da6900-8aea-11e9-9452-963ba5b632af.png)
类似这个
