### ISSUE TITLE
[Umbrella] Effects JSON 

### ISSUE THREAD

**Issue by janryWang** [alibaba/uform#105]
很多用户，对逻辑的序列化描述需求比较强烈，可以考虑支持一个json化描述effects的能力

**Comment by nikogu** [comment]
类似于：https://mozilla-services.github.io/react-jsonschema-form/ 里面的 `any of` 的升级版，联动如果不能通过 schema 描述，那么很多表单无法直接使用 schema，这样有碍于实现表单配置化的功能。

**Comment by nikogu** [comment]
其实感觉更多的是要脱离编程的思路，以数据语言来描述联动关系，否则如果只是照搬 `effects` 的话，太逻辑化，不能作为数据映射，后期维护和编写会很复杂。

**Comment by janryWang** [comment]
> 其实感觉更多的是要脱离编程的思路，以数据语言来描述联动关系，否则如果只是照搬 `effects` 的话，太逻辑化，不能作为数据映射，后期维护和编写会很复杂。

不会单纯照搬，更多的是json化的描述，对机器更友好吧

**Comment by dreamkidd** [comment]
我们现在的实现思路是是前端定义一系列 effect 规则，通过后台 json 返回联动规则，就是一种对表单联动的 json 描述

**Comment by cwtuan** [comment]
表单联动的逻辑，可能是根据某个item的值，也有可能是请求结果。

比如：select1=1, select=2。然后select3需要把select1和select2的值，去请求后端，取得列表后，塞入select3

**Comment by janryWang** [comment]
## UForm Effects JSON RFC提案

### 背景

目前很多用户对于UForm的数据驱动需求，不止是单纯的字段描述，还需要逻辑描述(联动，异步联动)，所以，这样的逻辑描述应该以什么样的形式来描述，我们还需要进一步设计。



### 现状

过去，我们针对表单字段的逻辑描述一般都是与具体字段配置逻辑绑定在一起的，但是，我们的实际联动逻辑，其实是多字段协作控制的，如果是单纯以字段角度出发，无法清楚描述单字段与其他字段的共同协作联动关系，同时也很难对整体的联动有一个全局视角去梳理。



### 目标梳理

- JSON化，机器友好
- 表单逻辑DSL，不需要满足图灵完备性，只解决业务domain级问题
- 插件化，收敛并复用业务逻辑



### 架构思路

![](https://img.alicdn.com/tfs/TB1.GhIeEGF3KVjSZFvXXb_nXXa-1168-918.png)



### 草稿方案

```
const EffectPlugin = (config)=>(context)=>{
   //插件config是属于插件的配置，context则是parser函数调用的第二个参数带进来的上下文
   return {
     middlewares:{//定义事件中间件，与koa中间件原理一样
        async onFieldChange(payload,next){
            ....
            await next()
            ....
        }
     },
     pipes:[//定义管道操作符
        {
          type:"fetchCategory",
          process:({payload,input,complie})=>{
            return fromPromise(//rxjs的fromPromise
              fetchCategory(input)
             .then(response=>complie(response))//编译output，response会作为$payload
            )
          }
        },
        {
          type:"setFieldState",
          process:({payload,input,complie})=>{
            context.setFieldState(input.target,state=>{
              Object.assign(state,complie())
            })
          }
        }
     ]
   }
}


const parser = createEffectsParser({
  effects,//前端默认effects实现
  plugins:[
     EffectPlugin()
  ]
})

//后端传过来的JSON数据
const json = {
   onFormInit:{
      
   },
   onFieldChange:{
      filter:"aa.bb.cc",//过滤字段变化
      pipe:[
        {
          type:"fetchCategory",
          input:{
            //数据流组件入参
          },
          ouput:{
            //数据流组件出参
            categoryId:"$payload.data.id" //表达式求值，可以做计算，最终封装出对应的出参供给下一个流程使用
          }
        },
        {
           type:"setFieldState",
           dependencies:["kk.mm","jj.oo"],//声明字段依赖
           input:{
             target:"aa.bb.cc"//需要设置状态的目标字段路径
           },
           output:{
             visible:"$payload.categoryId > 100 && $fieldState.value < 100",
             editable:"$dependencies.value < 30"
           }
        }
      ]
   }
  
}

//React组件使用
<SchemaForm schema={schema} effects={parser(json,{...context...})}/>
```



### 方案优劣

优势

- 流程清晰，出入参明确
- 插件化，方便基于业务构建符合业务特性的逻辑DSL

劣势

- 无法直接在JSON中写异步逻辑，只能通过写插件的形式来解决异步问题
- ouput的字符串表达式写法无法继续抽象

**Comment by my9074** [comment]
@janryWang  假如通过 UForm 动态生成的表单，其中的 select 是需要用户点击下拉时去服务端请求数据然后再展示。这类的场景是用 EffectPlugin 以插件的形式描述还是有其他的方式？

**Comment by janryWang** [comment]
> @janryWang 假如通过 UForm 动态生成的表单，其中的 select 是需要用户点击下拉时去服务端请求数据然后再展示。这类的场景是用 EffectPlugin 以插件的形式描述还是有其他的方式？

直接写一个异步下拉自定义组件，配置url参数即可

**Comment by my9074** [comment]
@janryWang 谢谢~你说的封装个自定义组件在负责的场景可以~但是感觉普通的下拉没啥必要。想问下有没有类似 `formItemMounted` 类似的生命周期函数或者别的方式可以写一些异步逻辑？

**Comment by janryWang** [comment]
> @janryWang 谢谢~ 你说的封装个自定义组件在负责的场景可以~但是感觉普通的下拉没啥必要。想问下有没有类似 `formItemMounted` 类似的生命周期函数或者别的方式可以写一些异步逻辑？

暂时没有，不过未来的版本会加入更加完备的生命周期钩子

**Comment by zhangjv** [comment]
很厉害，打算自己实现这个RFC，有些问题请教，求指点：

1. 配置中的pipes在实现上，对应rxjs中的pipe吗？还是只取一个同样的概念。因为我看EffectPlugin中的pipes定义，返回的不是一个纯函数。
2. 简单的 if 流程控制如何在这个机制上实现？因为我觉得条件判断是不是算足够常见，不耦合业务逻辑的？

**Comment by janryWang** [comment]
之前提的RFC，后来我试着去实现，其实发现它有个很严重的问题，就是它的整体思路其实是偏向于js视角去解决问题的，对配置界面的操作易用性并不是太友好，所以，我们如果仔细分析一下目前effects的处理策略，其实它是一种push式联动方案，如果落到配置界面上的话，或许MVVM的方案更加适合配置。所以，我们可以大概捋一捋思路：
```
{
  state:{//默认formState数据
    values:{},
    initialValues:{},
    //扩展状态
  },
  tasks:[
    {
       name:"fetchInitialValues",
       trigger:{
         type:"onFormMount"
       },
       options:{
         xxx:"{{$context.xxx}}"
       },
       resolve:{//操作formState
         values:{
           aa:"{{$payload.aa}}"
         }
       },
       reject:{
       
       }
    },
    {
       name:"fetchSomething",
       trigger:{
         type:"onFieldChange",
         options:"aa.bb"
       },
       options:{
         xxx:"{{$context.xxx}}"
       },
       resolve:{//操作formState
         
       },
       reject:{//操作formState
       
       }
    },
    
  ],
  fields:{
    'aa.bb':{
      visible:"{{$formState.values.xxx}}",
    }
  }
}

//内置变量
$context //整体上下文，静态环境变量，由js注入
$payload //异步任务返回值
$formState //表单整体状态
$fieldState //只有在trigger.type为onFieldChange时候的动态变量

```

整个json，包括3块内容：
第一块是代表表单的默认状态，你可以在其中扩展自己的状态变量
第二块是代表表单的异步任务，主要由表单核心生命周期来触发，然后最终还是回到操作表单状态的模式
第三块是代表字段状态绑定，通过表达式实现数据与字段状态的双向绑定，我们通过解析表达式依赖，最终可以等价转换成现在的effects模式

整体数据流在用户态而言就是一个单向数据流模式，只是它内部的运作则还是p2p的点对点的运作机制，所以也不存在性能问题。

**Comment by quirkyshop** [comment]
很棒的讨论！一些想法和建议

1. trigger应该是数组，支持多重触发源
2. 这里的task是否需要到别的地方去定义 **(我理解需要的，并且需要Task RFC）**，因为有可能是非常复杂的一些参数或者结果处理
3. task的顺序是否重要，**如果有两个task的trigger是一样的，编写的顺序会影响执行顺序吗**，这里的问题主要是有操作同一字段的两个task会有竞态问题（不过如果考虑是对机器友好的话，可以在操作界面限制或提示来解决）

如果换一种思路，把task改写成这样会更好吗，**语义是清晰了**，但是有点绕，只是一种讨论和建议，不过以下的写法弊端是无法太好的描述自定义trigger（虽然原方案也一样），也就是tasks的key不一定是生命周期, 如下面的 **timer(定时器), followTask(跟随trigger)** 等等

```jsx
tasks: {
  onFormMount: [
    { name:"fetchInitialValues1", resolve, reject ... },
    { name:"fetchInitialValues2", resolve, reject ... }
    { name:"fetchInitialValues3", resolve, reject ... }
  ],
  onFieldChange: [
    { name:"fetchSomething1", options: { trigger: ['aa.bb', 'cc.dd'] }, resolve, reject ... },
    { name:"fetchSomething2", options: { trigger: ['aa.bb', 'cc.dd'] }, resolve, reject ... }
  ],
  timer: [
    { name:"fetchSomething3", options: { timeout: 3000 }, resolve, reject ... },
  ],
   followTask: [...]
}

```

**Comment by changkem** [comment]
现在序列化effects进展怎么样了

**Comment by janryWang** [comment]
> 现在序列化effects进展怎么样了

看#478，目前内部已经开发好了，文档还没透出，需要内部先试用一段时间
