### ISSUE TITLE
Why set the max-width?

### ISSUE THREAD

**Issue by stkevintan** [alibaba/uform#107]
- [ ] https://github.com/alibaba/uform/blob/b9d45049121d22e7caeb89b74022b8b9b6a86913/packages/antd/src/utils.js#L29

why there is the max-width? 
How can i custom it or remove it ? 
and why the other component doesn't have this rule, eg: Input ?
![图片](https://user-images.githubusercontent.com/5887203/59337314-e87e8e00-8d32-11e9-8fb0-1848e988e607.png)

**Comment by janryWang** [comment]
这个问题你可以通过在x-props中传style属性来自定义长度

**Comment by stkevintan** [comment]
@janryWang 那为什么要设一个这样的max-width呢？ 而且仅仅只有select设置了，导致select跟其他组件在一起显得长度不一致

**Comment by janryWang** [comment]
> @janryWang 那为什么要设一个这样的max-width呢？ 而且仅仅只有select设置了，导致select跟其他组件在一起显得长度不一致
> 个人觉得这种maxwidth之类的属性应该让用户自己自定义比较好，组件不需要care

嗯，赞同，只是这份代码，一开始不是我加的，是另外一个同学加的，我需要了解清楚他当时加这个是为了解决什么问题

**Comment by cnt1992** [comment]
> > @janryWang 那为什么要设一个这样的max-width呢？ 而且仅仅只有select设置了，导致select跟其他组件在一起显得长度不一致
> > 个人觉得这种maxwidth之类的属性应该让用户自己自定义比较好，组件不需要care
> 
> 嗯，赞同，只是这份代码，一开始不是我加的，是另外一个同学加的，我需要了解清楚他当时加这个是为了解决什么问题

当时加的时候只是避免100%长度占太长，可以把`max-width`属性去掉让用户自定义好了

**Comment by janryWang** [comment]
@stkevintan 欢迎提个PR解决这个问题吧
