### ISSUE TITLE
Is there a way to use formState to control the formCard visible?

### ISSUE THREAD

**Issue by mysansa52** [alibaba/uform#110]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Question
2. Describe your issue:

Use formState to control layout visibility,But  How to get formState in layout
.

**Comment by janryWang** [comment]
给FormCard配name属性，通过setFieldState就可以控制它的visible了

**Comment by janryWang** [comment]
答疑性问题都到答疑群里问吧
