### ISSUE TITLE
表单联动FormBlock 由隐藏变成显示值被清除

### ISSUE THREAD

**Issue by javahuang** [alibaba/uform#113]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug
  - Feature request

2. Describe your issue:

FormBlock 里面的 Field 由隐藏变成显示状态，之前的值依然保留。
FormBlock 由隐藏变成显示状态，里面的 Field 之前的值被清除了。

能不能将 FormBlock 从隐藏变成显示状态，之前的值依然保留？我有个 FormBlock 里面有大量的 Field，从显示变成隐藏之后，用户又得重新输入一遍。

 https://codesandbox.io/s/fancy-dust-logjr

**Comment by janryWang** [comment]
这个问题有点尴尬，目前的逻辑是，Field unmount会触发数据删除，主要是为了解决类似Array List每一行添加删除之后再次添加的时候不会保留之前填的数据，至于相邻联动数据又没删除，这个应该是异常行为，相当于没有触发unmount
