### ISSUE TITLE
uform vs noform

### ISSUE THREAD

**Issue by netroby** [alibaba/uform#121]
uform对比阿里的另外一个产品noform
差别如何？
https://alibaba.github.io/nopage/#/nopage/noform/brief-intro

**Comment by janryWang** [comment]
最直白的对比，你可以在后续使用过程中逐步发现这些特点
1. 性能更牛逼，特别是对于复杂联动场景下
2. 数据驱动更友好，标准JSON Schema
3. 联动写起来很舒服很自然
