### ISSUE TITLE
能否通过 Schema 定义表单联动操作

### ISSUE THREAD

**Issue by dreamkidd** [alibaba/uform#13]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  * Question

2. Describe your issue:

rt，Demo表单联动的实现基本上是通过 effects 实现，能否通过 schema 定义表单联动规则呢？类似 x-rule 的做法，可以通过 x-effects 字段定义联动 rule

**Comment by janryWang** [comment]
x-effect是用于派发事件的，具体联动只能在effects里实现，这样的好处就类似于redux的reducer，统一一处管理业务逻辑，提升代码可维护性的同时，对于纯JSON Schema数据驱动场景也是比较友好的

**Comment by dreamkidd** [comment]
假设表单是完全由后端schema 生成的，包括联动规则也是由后端指定，这种情况下，需要前后端通过一个接口指定交互规范，然后根据规范再去通过effects 实现交互规则

**Comment by janryWang** [comment]
你可以做domain级别的抽象，对effects做json化描述

**Comment by dreamkidd** [comment]
谢谢
