### ISSUE TITLE
关于使用第三方UI组件库的问题?UForm是否支持？（例如  material-ui）

### ISSUE THREAD

**Issue by Gzbox** [alibaba/uform#130]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
2. Describe your issue:

  - What is the current behavior?

如果我使用的不是Antd 或 Next 组件库，是material-ui   我该如何使用material-ui ？？
有文档介绍吗？

**Comment by janryWang** [comment]
参考@uform/antd的源码自己封装

**Comment by Gzbox** [comment]
好的  谢谢
