### ISSUE TITLE
表单里面获取表单各个字段的值

### ISSUE THREAD

**Issue by zhuscat** [alibaba/uform#133]
我的表单中存在一些展示信息需要根据用户填写的信息实时作出改变，像 `Formik` 可以通过 Render Props 的方式直接拿到值，然后进行计算，如：

```jsx
<Formik {...props}>
  {({ values, ...otherProps }) => ...}
</Formik>
```

那在 UForm 中推荐的方式是怎么样的呢？

用 `effects` 将计算得到的值设置到组件自己的状态上吗？

**Comment by janryWang** [comment]
这个就是个正常的联动，使用最简单的setFieldState就行了，首先，你需要写一个自定义组件
