### ISSUE TITLE
uform/utils的isEqual方法在小程序内报错

### ISSUE THREAD

**Issue by wangmingxu** [alibaba/uform#134]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

    Bug

2. Describe your issue:

  - What is the current behavior?
     尝试在小程序上面基于uform/core开发一个表单组件，但是uform/utils里面的isEqual函数里面出现了a instanceof URL这种写法，而小程序里面没有URL对象导致报'URL is not defined'的错误
  - What is the expected behavior?
     希望官网可以考虑多种运行环境，作出兼容
  - Which versions of UForm?
     0.1.16
  - Did this work in previous versions of UForm?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
小程序？这个目前暂无考虑，不过你可以先fork一份，尝试修复在小程序下的一些报错，如果能通过少量代码就解决问题的，可以给我们提个PR

**Comment by wangmingxu** [comment]
#137
