### ISSUE TITLE
When to support typescript?

### ISSUE THREAD

**Issue by zsirfs** [alibaba/uform#14]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of Rax, and which browser / OS are affected by this issue?
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by janryWang** [comment]
There is currently no plan to support typescript, but welcome PR. 😆

**Comment by zsirfs** [comment]
@janryWang OK, thank to reply me.

**Comment by zsirfs** [comment]
@janryWang Can you give me a copy of your email? If I support the typescript program, I hope to contact you for a more precise type definition.
