### ISSUE TITLE
maybe we should make scheduler as a peerdependence

### ISSUE THREAD

**Issue by stkevintan** [alibaba/uform#140]
https://github.com/alibaba/uform/blob/985af279d0a0cadb7bf258e38232b21ef08a4d92/packages/core/package.json#L25

**Comment by janryWang** [comment]
If we move scheduler to peerdependence, the user experience will be worse. Everyone has to manually install the scheduler.

**Comment by stkevintan** [comment]
@janryWang 但是一旦使用了react 16就会有react scheduler依赖。目前我使用的react 16.8.6,依赖scheduler 0.13.6, 但是uform依赖版本是0.11.2，所以打出来的包里面有两个不同版本的scheduler。
看你的代码里使用shceduler只是用来在当requestAnimationFrame不存在的时候的polyfill。感觉为了这个而引入一个库不太适合

**Comment by janryWang** [comment]
不是，您看到的顺序错了，scheduler是首选，只有它的API不存在才会选用requestAnimationFrame，还有，用到它的目的很明确，是为了让整个表单状态更新的调度推入react渲染执行栈中，对于concurrent mode是友好的

**Comment by stkevintan** [comment]
@janryWang sorry是我看错了， 但是既然装react的话，那么就已经装了scheduler依赖了，那装uform的时候没必要再装一遍吧。我们直接判断是否有scheduler这个库，如果有那就用。
如果没有，说明当前不是react环境，或者react版本太低，这个时候也不需要考虑跟react concurrrent mode 结合了

**Comment by janryWang** [comment]
> @janryWang sorry是我看错了， 但是既然装react的话，那么就已经装了scheduler依赖了，那装uform的时候没必要再装一遍吧。我们直接判断是否有scheduler这个库，如果有那就用。
> 如果没有，说明当前不是react环境，或者react版本太低，这个时候也不需要考虑跟react concurrrent mode 结合了

嗯，你这样的判断是正确的，可以提个PR修复一下哈，对了，顺便提一下，您的微信号是多少呢？

**Comment by stkevintan** [comment]
@janryWang   哈哈好的，我的微信是 kevintan_1993
