### ISSUE TITLE
官网 场景案例里面，表单详情的demo，均无法初始化

### ISSUE THREAD

**Issue by catalsdevelop** [alibaba/uform#146]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

`Fusion Next`和`Ant Design`里面的`表单行情`都不可以

https://uformjs.org/#/YZCyCk/Zqhjh1UGfY
https://uformjs.org/#/YZCyCk/0eh2h6U0Hy

**Comment by anyuxuan** [comment]
> ## Help us to manage our issues by answering the following:
> 1. How would you tag this issue?
> 
> * Bug
> 
> 1. Describe your issue:
> 
> `Fusion Next`和`Ant Design`里面的`表单行情`都不可以
> 
> https://uformjs.org/#/YZCyCk/Zqhjh1UGfY
> https://uformjs.org/#/YZCyCk/0eh2h6U0Hy

你是指这两个Demo中的初始值显示不正确吗？

**Comment by stkevintan** [comment]
sorry误操作了😅
@catalsdevelop 无法初始化是值没有初始化还是组件没有初始化？可否给个截图看看？

**Comment by catalsdevelop** [comment]
啊，看到了，是我没有仔细看，你说的没错。
