### ISSUE TITLE
文档示例的uoload不能正常运行

### ISSUE THREAD

**Issue by yinxuan1128** [alibaba/uform#18]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:

示例地址：https://codesandbox.io/s/lp8o5ylj1z
`      <Field
        type="upload"
        title="普通上传文件"
        name="upload3"
        x-component="upload"
        x-props={{ listType: 'text' ,action:'https://www.easy-mock.com/mock/5b713974309d0d7d107a74a3/alifd/upload'}}
      />`
点击文件上传后，文件列表不更新，收集的数据里面也没有upload3的值

**Comment by janryWang** [comment]
感谢提供复现地址

**Comment by janryWang** [comment]
已修复
