### ISSUE TITLE
无法通过schema配置文件动态显示表单

### ISSUE THREAD

**Issue by yinxuan1128** [alibaba/uform#185]
1. How would you tag this issue?
  - Bug

2. Describe your issue:
Uform组件无法通过schema配置文件动态显示表单，只有第一次设置的schema配置起作用，后续更改配置参数，无法正确渲染

**Comment by anyuxuan** [comment]
不知道你第二次设置schema的逻辑是什么，这边我写了一个Demo，再次设置schema是有效果的，不知道我的Demo是否可以解决你的问题
https://codesandbox.io/embed/fragrant-cdn-bsl6u

**Comment by yinxuan1128** [comment]
@anyuxuan 我主要想把表单用弹窗来展示，我看了您的demo，也试着在您的demo里用modal展示，表单显示没问题。但是我用另一个组件包裹后就不行了，不知道为什么。麻烦您看下我的[https://codesandbox.io/s/strange-margulis-7ypdg](url)
只有先点击的生效了

**Comment by anyuxuan** [comment]
@yinxuan1128 这个是因为antd的Modal在关闭后没有销毁里面的子元素，你在你的DEMO里的Modal上增加参数destroyOnClose就可以了
