### ISSUE TITLE
Field的type为array的时候，x-component为table有问题

### ISSUE THREAD

**Issue by xw-Zhou** [alibaba/uform#187]
```
x-props={{
     renderAddition:() => <button>添加</button>,// 以回调函数的形式设置的时候，点击不生效
     renderRemove:<NuButton>删除</NuButton>// 这样子可以生效，但是前面携带Icon
}}
```
#### 文档写的是
```renderAddition:()=><div>通过渲染函数做完全内容定制</div> or "直接传渲染文案，会默认带上icon"。```

#### 查阅源码发现应该是这个文件下设置有问题
```uform/packages/react/src/shared/array.tsx```

#### 如果能修改成下面这种的形式就更好了：
```
renderAddition:(params) => {//回调函数的形式时，这里有参数
    return <button onClick={()=>params.add()}>添加</button>
}
```

**Comment by anyuxuan** [comment]
@xw-Zhou 我写了一个Demo，看看是否可以解决你的疑惑
https://codesandbox.io/embed/nice-shannon-xllbv

**Comment by janryWang** [comment]
应该是函数的形式，props.onClick没有透传下去

**Comment by xw-Zhou** [comment]
> @xw-Zhou 我写了一个Demo，看看是否可以解决你的疑惑
> https://codesandbox.io/embed/nice-shannon-xllbv

这样写确实可以实现了，谢谢，但是我在这里的样式上还是有点问题，如果数据列比较多的话，必须把滚动条拉到后面才能进行操作。。。体验确实不太好

**Comment by xw-Zhou** [comment]
> 应该是函数的形式，props.onClick没有透传下去

上面那样写可以了，谢谢，但是我在这里的样式上还是有点问题，如果数据列比较多的话，必须把滚动条拉到后面才能进行操作。。。体验确实不太好

**Comment by anyuxuan** [comment]
@xw-Zhou 每一行数据的操作按钮只能排列在最后一列这个问题我之后优化一下，这个issue就先关了，谢谢你的反馈

**Comment by xw-Zhou** [comment]
> @xw-Zhou 每一行数据的操作按钮只能排列在最后一列这个问题我之后优化一下，这个issue就先关了，谢谢你的反馈

好的，谢谢
