### ISSUE TITLE
高性能如何体现

### ISSUE THREAD

**Issue by lianyzhou** [alibaba/uform#19]
尝试使用registerFormField创建了一个自定义表单元素，发现外层容器渲染时，表单元素会重新渲染，这是正常情况吗，如何体现高性能

![image](https://user-images.githubusercontent.com/6295633/56826551-1d23ac80-688f-11e9-8969-8b1fb7b9811e.png)

是否能提供一个复杂的例子，说明registerFormField的高级使用场景。

**Comment by janryWang** [comment]
打开React Update Highlight，可以直接看组件的渲染情况
这是Ant Design的例子
![](https://img.alicdn.com/tfs/TB11xYUS6DpK1RjSZFrXXa78VXa-2252-1670.gif)

很明显，每次操作都会触发组件树的全量渲染

这个是UForm的例子
![image](https://img.alicdn.com/tfs/TB1m24nafc3T1VjSZLeXXbZsVXa-2186-1524.gif)

**Comment by lianyzhou** [comment]
@janryWang 从你给的截图中，很清晰的看到了高性能的体现，:thumbsup:。
examples中能否提供一个registerFormField的较为复杂的例子，比如this.props.mutators的使用。

**Comment by janryWang** [comment]
@lianyzhou 您可以直接看源码，里面有用mutators的例子 https://github.com/alibaba/uform/blob/master/packages/next/src/fields/array.js
