### ISSUE TITLE
长Label希望增加title属性

### ISSUE THREAD

**Issue by yumingyan** [alibaba/uform#196]
1. uform/antd   type=year 年选择无效
2. type=array时，minItems属性无效
3. 长Label无法显示完整时，希望可以添加title属性,鼠标经过可以看到完整Label值
https://codesandbox.io/s/festive-mccarthy-7jtoj

**Comment by janryWang** [comment]
1. 年份选择的问题与 #33 重复了
2. minItems属性无效，目前这种行为是一个正确的行为，minItems是用于控制删除按钮的动作，如果您需要控制至少一条数据，需要手动先在intialValues里传默认数据
3. 长label问题，建议在文案上简化，如果需要详细描述，可以借助description属性来辅助描述

**Comment by janryWang** [comment]
先close了，如果还有问题再open吧
