### ISSUE TITLE
0.3.4 uform/core 没有lib导出

### ISSUE THREAD

**Issue by cendechen** [alibaba/uform#197]
This dependency was not found:

* @uform/core in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/form.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save @uform/core

**Comment by anyuxuan** [comment]
非常感谢你的及时反馈，目前问题已经解决，最新版本是v0.3.6，这个问题是因为我个人的误操作导致的，十分抱歉，感谢你对UForm的支持

**Comment by anyuxuan** [comment]
非常感谢你的及时反馈，目前问题已经解决，最新版本是v0.3.6，这个问题是因为我个人的误操作导致的，十分抱歉，感谢你对UForm的支持
