### ISSUE TITLE
@uform/core 单独使用报错

### ISSUE THREAD

**Issue by cendechen** [alibaba/uform#199]
form.js?5dac:701 Uncaught (in promise) TypeError: Illegal invocation
    at eval (form.js?5dac:701)
    at new Promise (<anonymous>)
    at Form.internalValidate (form.js?5dac:697)
    at Form.validate (form.js?5dac:469)
    at Form.submit (form.js?5dac:491)
    at eval (form.vue?aefa:26)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/form.vue?vue&type=script&lang=js& (app.js:1188)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (form.vue?d99d:1)

**Comment by anyuxuan** [comment]
https://codesandbox.io/embed/elegant-lumiere-eu0kf
我写了一个DEMO，没有出现问题，不知道你具体的使用方式是什么？

**Comment by janryWang** [comment]
> https://codesandbox.io/embed/elegant-lumiere-eu0kf
> 我写了一个DEMO，没有出现问题，不知道你具体的使用方式是什么？

应该是调用了某个方法报错了，@cendechen 麻烦把复现流程阐述清楚一些

**Comment by cendechen** [comment]
> > https://codesandbox.io/embed/elegant-lumiere-eu0kf
> > 我写了一个DEMO，没有出现问题，不知道你具体的使用方式是什么？
> 
> 应该是调用了某个方法报错了，@cendechen 麻烦把复现流程阐述清楚一些

单独使用，没有引用react库的时候，就会报错，对了，这个考虑支持一下vue吗？ 
最近做表单项目，发觉封装思路很不错，如果官方没有支持，想基于源码构建一个vue版本

**Comment by janryWang** [comment]
> > > https://codesandbox.io/embed/elegant-lumiere-eu0kf
> > > 我写了一个DEMO，没有出现问题，不知道你具体的使用方式是什么？
> > 
> > 
> > 应该是调用了某个方法报错了，@cendechen 麻烦把复现流程阐述清楚一些
> 
> 单独使用，没有引用react库的时候，就会报错，对了，这个考虑支持一下vue吗？
> 最近做表单项目，发觉封装思路很不错，如果官方没有支持，想基于源码构建一个vue版本

vue暂时不在19年计划中，您的意思是，如果没依赖React就会出问题？

**Comment by cendechen** [comment]
> > > > https://codesandbox.io/embed/elegant-lumiere-eu0kf
> > > > 我写了一个DEMO，没有出现问题，不知道你具体的使用方式是什么？
> > > 
> > > 
> > > 应该是调用了某个方法报错了，@cendechen 麻烦把复现流程阐述清楚一些
> > 
> > 
> > 单独使用，没有引用react库的时候，就会报错，对了，这个考虑支持一下vue吗？
> > 最近做表单项目，发觉封装思路很不错，如果官方没有支持，想基于源码构建一个vue版本
> 
> vue暂时不在19年计划中，您的意思是，如果没依赖React就会出问题？是不是没有安装scheduler这个包

对，安装了 scheduler也一样会报错

**Comment by cendechen** [comment]
> > > > https://codesandbox.io/embed/elegant-lumiere-eu0kf
> > > > 我写了一个DEMO，没有出现问题，不知道你具体的使用方式是什么？
> > > 
> > > 
> > > 应该是调用了某个方法报错了，@cendechen 麻烦把复现流程阐述清楚一些
> > 
> > 
> > 单独使用，没有引用react库的时候，就会报错，对了，这个考虑支持一下vue吗？
> > 最近做表单项目，发觉封装思路很不错，如果官方没有支持，想基于源码构建一个vue版本
> 
> vue暂时不在19年计划中，您的意思是，如果没依赖React就会出问题？是不是没有安装scheduler这个包

对，安装了 scheduler也一样会报错

**Comment by janryWang** [comment]
能不能在codesandbox 复现这个问题？@cendechen
