### ISSUE TITLE
未来会有RN支持相关的计划吗？

### ISSUE THREAD

**Issue by x956606865** [alibaba/uform#20]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of Rax, and which browser / OS are affected by this issue?
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by janryWang** [comment]
目前暂无该计划，不过欢迎PR共建

**Comment by zhailb666** [comment]
自定义表单如何扩展
