### ISSUE TITLE
object下filed的name为数字的时候，会把object转为数组类型

### ISSUE THREAD

**Issue by littleone2018** [alibaba/uform#201]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
 - Bug

2. Describe your issue:

  https://codesandbox.io/s/flamboyant-morning-djziu?fontsize=14

有时候会以用户id为name，这样会导致表单很庞大，很卡，请尽快修复。

**Comment by janryWang** [comment]
codesandbox链接无效，麻烦给个有效案例

**Comment by littleone2018** [comment]
<SchemaForm onSubmit={val => console.log(val.ob.length)} inline>
      <Field name="ob" type="object">
        <Field title="id" name="10001" type="string" />
        <Submit />
      </Field>
    </SchemaForm>

**Comment by littleone2018** [comment]
```
<SchemaForm onSubmit={val => console.log(val.ob.length)} inline>
      <Field name="ob" type="object">
        <Field title="id" name="10001" type="string" />
        <Submit />
      </Field>
    </SchemaForm>
```

**Comment by firesz** [comment]
为什么我在react组件的ObjectField 也遇到这个问题了呢？
我是最新的 2.2.29 版本
