### ISSUE TITLE
win @next/antd 异步校验自动失焦

### ISSUE THREAD

**Issue by Mamoriaii** [alibaba/uform#205]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:
  - What is the current behavior?
windows @uform/antd下使用debounce-promise异步校验input会自动失焦
  - Which versions of UForm?
  - Did this work in previous versions of UForm?
2.6, 3.2, 3.3, 3.6 都存在

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox

- windows
修改[官方 简单登录页面异步校验](https://codesandbox.io/s/mgjub) @uform/next 为 @uform/antd 可复现

**Comment by atzcl** [comment]
是点击 [提交] 按钮后失去焦点还是？

**Comment by janryWang** [comment]
我这边可以复现了，问题找下来是因为Input的suffix属性动态更新会导致失去焦点，https://github.com/ant-design/ant-design/issues/17947
