### ISSUE TITLE
Can't find the types dir

### ISSUE THREAD

**Issue by YikaJ** [alibaba/uform#209]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug

2. Describe your issue:

  - What is the current behavior?
```bash
Cannot find module '../types/components/button'.
```
  - What is the expected behavior?
It can compile success in typescript.

  - Which versions of UForm?
@uform/antd@0.3.6

  - Did this work in previous versions of UForm?
This is my first time to use it.

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox.

![image](https://user-images.githubusercontent.com/8725110/62107961-63980580-b2db-11e9-83d4-3972f0f346a0.png)

copy `src/types` to `lib/types` and it works.

**Comment by monkindey** [comment]
你是用 TypeScript 使用的么？不过 https://github.com/alibaba/uform/pull/206 已经去掉了 types  文件夹，后面合并再看看是否存在问题？

**Comment by atzcl** [comment]
这个原因是 tsc 编译后去掉了引用的 .d.ts 文件，等 #206 合并了就能修复

**Comment by YikaJ** [comment]
OK，等你们进行合并后再看看，我先手动复制解决了。
