### ISSUE TITLE
Field的x-render这个api使用方法，能添加个使用案例吗？着急

### ISSUE THREAD

**Issue by xw-Zhou** [alibaba/uform#212]
如题

**Comment by atzcl** [comment]
可以看下这个例子 [https://codesandbox.io/s/wxt5b](https://codesandbox.io/s/wxt5b)

**Comment by gooddaddy** [comment]
文档也太。。。哪个了，能不能安排个人搞好点点

**Comment by janryWang** [comment]
目前x-render其实并不推荐使用，所以就没有给出太多例子，后续1.x出来之后，对于强UI定制场景会有更优的方案 @gooddaddy ，还有，建议一下，尽量不要对开源项目吐槽，Welcome PR
