### ISSUE TITLE
form value don't work when the value has been changed by onFieldChange  

### ISSUE THREAD

**Issue by tianxuzhang** [alibaba/uform#213]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of UForm?
  - Did this work in previous versions of UForm?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

eg:
https://codesandbox.io/s/ufrom-bug-valueinitialvalues-b8kzy?fontsize=14

**Comment by janryWang** [comment]
从表现来看，initialValues设置初始值，onFieldChange置空失效是bug，要实现预期效果：只在用户变更的时候触发，需要在fieldChange支持一个是否是初始化阶段触发的标记，方便用户过滤
