### ISSUE TITLE
[Feature request] Support custom rule registration

### ISSUE THREAD

**Issue by atzcl** [alibaba/uform#215]
为了方便开发者管理、使用可复用的校验规则，我们可以提供类似
```
import { addValidationRules } from '@uform/core'
```

或者是
```
window.uform.addValidationRules
```
的方法用于开发者注册全局的自定义校验规则

`addValidationRules` 用法可能是这样的：
```
addValidationRules({
  phone: (value, rule, values, name) => (
    new Promise(resolve => {
      (/^((\+|00)86)?1((3[\d])|(4[5,6,7,9])|(5[0-3,5-9])|(6[5-7])|(7[0-8])|(8[\d])|(9[1,8,9]))\d{8}$/).test(value)
        ? resolve()
        : resolve(rule.message || '手机格式不正确')
    })
  ),

  idCard: (value, rule, values, name) => (
    new Promise(resolve => {
      (
        /(^\d{8}(0\d|10|11|12)([0-2]\d|30|31)\d{3}$)|(^\d{6}(18|19|20)\d{2}(0\d|10|11|12)([0-2]\d|30|31)\d{3}(\d|X|x)$)/
      ).test(value)
        ? resolve()
        : resolve(rule.message || '身份证号码不正确')
    })
  ),

  ....
})

```

在 `x-rules` 里的使用可能是这样的：
```
...
x-rules={[
   { required: true, message: '请输入手机号码' },
   { phone: true },
]}
...


...
x-rules={[
   { required: true, message: '请输入身份证号码' },
   { idCard: true, message: '仅支持1/2代(15位/18位数字)身份证号' },
]}
...
```

另外可能需要考虑一下如果注册的 rule 名重复冲突了应该怎么办、是否应该提供卸载指定 rule 等等

**Comment by janryWang** [comment]
1. window.uform.addValidationRules 这种写法只有在umd包中可以使用
3. 动态注册的校验规则的错误消息需要统一在validationLocale里面配置
2. 需要支持pattern的注册

**Comment by atzcl** [comment]
1. `window.uform.addValidationRules` 等后面有 UMD 版本的时候可以提供一下
2. 错误信息不一定要在 ` validationLocale ` 里面配置，如果有需要多语言支持的，可以自行去设置一下
3. 不明白 `pattern` 的注册是啥😂😂

**Comment by atzcl** [comment]
另外看下有没有必要官方出一个集成了平时经常使用的校验规则的工具包，方便日常的开发；
类似：
```
// 在入口文件处注册
import { addValidationRules } from '@uform/core';
import { alpha, between, date_equals, file, image, sometimes, ...... } from '@uform/rules';

addValidationRules({ alpha, between, date_equals, file, image, sometimes, ......  });
```

**Comment by janryWang** [comment]
> 1. `window.uform.addValidationRules` 等后面有 UMD 版本的时候可以提供一下
> 2. 错误信息不一定要在 `validationLocale` 里面配置，如果有需要多语言支持的，可以自行去设置一下
> 3. 不明白 `pattern` 的注册是啥😂😂

我第二点的意思是，如果是封装自定义规则的，规则文案，这里是指默认文案，也必须以国际化文案包的形式注册，比如

```
addValidationRules({
  idcard:{
    validator:()=>....,
    message:{
       zh:'中文',
       en:'英文'
    }
  }
})
```

第三点，我是指正则规则，因为目前是可以支持`<Field x-rules="phone" ..`这种写法的，是否需要给个便利方法，帮助用户快递扩展正则库，比如

```
const addValidationPattern = (name,parttern,message)=>{
  addValidationRules({
     [name]:{
        validator(){
             ...正则判断
        },
        message:message || `${name} pattern was validate failed.`
     }
  })
`
}

```

**Comment by atzcl** [comment]
第二点，为什么自定义规则的默认文案必须要以国际化文案包的形式注册，用户并不一定需要多语言支持的，可能只是简单地想在校验规则里面抛出错误信息，，

第三点可以增加这种注册形式，具体看下怎么支持了

**Comment by janryWang** [comment]
> 第二点，为什么自定义规则的默认文案必须要以国际化文案包的形式注册，用户并不一定需要多语言支持的，可能只是简单地想在校验规则里面抛出错误信息，，
> 
> 第三点可以增加这种注册形式，具体看下怎么支持了

我的目的注意是，用户维护国际化文案可以统一以一个校验包的国际化文案来管理，这样是比较方便的，不需要用户分散管理，还有就是，国际化文案作为默认语言处理的，所以还是支持在x-rules使用的时候直接传message的形式

**Comment by atzcl** [comment]
是会支持直接在 `x-rules` 里面定义 `message `，上面的伪代码有写，国际化文案的定义添加不是有 `setValidationLocale ` api 可以使用嘛？

**Comment by janryWang** [comment]
> 是会支持直接在 `x-rules` 里面定义 `message `，上面的伪代码有写，国际化文案的定义添加不是有 `setValidationLocale ` api 可以使用嘛？

对，我的意思就是使用了注册自定义规则的API之后，setValidationLocale这个API是否还能用？

**Comment by atzcl** [comment]
保留会好点吧，这里可以保持功能的干净，然后名字可以改成 ` setValidationLocale ` ----> ` addValidationLocaleMessages ` ?

**Comment by janryWang** [comment]
> 保留会好点吧，这里可以保持功能的干净，然后名字可以改成 `setValidationLocale` ----> `addValidationLocaleMessages` ?

为什么要改呢？改了之后就是break change哦

**Comment by atzcl** [comment]
感觉会更加形象些，或者可以导一个别名兼容一下？

**Comment by janryWang** [comment]
> 感觉会更加形象些，或者可以导一个别名兼容一下？

如果没有太大的差异就不用改了吧，避免用户二次学习
