### ISSUE TITLE
uform 回滚方案

### ISSUE THREAD

**Issue by monkindey** [alibaba/uform#216]
### 背景

uform 现在作为供应链技术体系的基础，需要保证它的稳定性和回滚方案。

### 问题

现在 `uform` 没有打成一个 bundle，并且依赖版本号是自动升级的，导致 `@uform/react`、`@uform/core` 在外界不能控制版本号。

* @uform/next@0.3.7
  * @uform/react@0.3.7
     * @uform/core@0.3.7

### 方案

类比 [React cjs 包](https://unpkg.alibaba-inc.com/react-dom@16.8.4/cjs/react-dom.development.js)，我们可以提供一个 bundle 包，然后把一些不依赖的东西给 alias 出去，比如 next 之类的。也就是呈现给用户 uform 就是一个包而已，而不是在 node_modules 控制。

**Comment by janryWang** [comment]
https://github.com/cssinjs/jss/blob/master/packages/react-jss/package.json 这个包也是没有打bundle，打bundle其实跟写死版本号没啥区别，都容易造成重复打包，这个也不是一个乐观解决方案，如果我们的方案都是以悲观方案来看待的话，那就很难有办法去正向的解决问题，什么都是让用户锁版本号就行了，用户遇到问题可能都不想提issue跟进解决。
我本人还是倾向于，遇到问题修复问题，通过技术手段避免问题。

**Comment by stkevintan** [comment]
我觉得，全变成peerdepence吧。
