### ISSUE TITLE
[Umbrella] Support compact responsive UI

### ISSUE THREAD

**Issue by janryWang** [alibaba/uform#223]
1. 考虑到有些场景对校验防抖动的占位元素高度的述求很低，要求信息更聚焦，所以需要支持紧凑型UI
2. 考虑到无线端的展示场景，UI上还是存在一些问题，需要整体看一下 #221

**Comment by atzcl** [comment]
antd/next 本来就是 PC 端的 UI 框架，如果用户需要在移动端使用不就应该由用户自己兼容调整嘛？等后面去掉了 styled-components 就会更方便用户自己定制了吧
