### ISSUE TITLE
文本串联样式问题

### ISSUE THREAD

**Issue by welkang** [alibaba/uform#231]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug
  - Enhancement

2. Describe your issue:
![image](https://user-images.githubusercontent.com/1400403/62464410-15916f00-b7bf-11e9-8d4f-ca4061aae41b.png)
文本串联如果输入框前面没有文本，则无法与其他字段左对齐，版本是 0.3.7。

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.https://codesandbox.io/embed/elegant-hellman-fr7s1

**Comment by soulwu** [comment]
借地方说一个关联的建议。FormTextBox在editable为false时，建议去掉text-field与text-box-words之前的margin，这样可以让内容可读性更友好
https://codesandbox.io/embed/workbench-frame-2tzue
![image](https://user-images.githubusercontent.com/1633638/62469253-76727480-b7ca-11e9-9300-f17358c6344c.png)
