### ISSUE TITLE
FormTextBox文本行高问题

### ISSUE THREAD

**Issue by soulwu** [alibaba/uform#232]
https://github.com/alibaba/uform/blob/33291e3e5cb5d7c7c3fd6e89d9dc70e42b94cd8c/packages/next/src/components/layout.js#L270

这里写死了28px的行高，在不同主题样式下会导致文本不对齐。比如使用的Fusion主题，medium的form-element定义为32px高的话，label文本就会和text-words在垂直方向上不对齐

**Comment by janryWang** [comment]
你的意思是直接干掉？

**Comment by soulwu** [comment]
> 你的意思是直接干掉？

可以支持使用者传入或者是支持fusion主题变量？

**Comment by janryWang** [comment]
> > 你的意思是直接干掉？
> 
> 可以支持使用者传入或者是支持fusion主题变量？

主题变量估计有点难，因为没走sass，这个问题先hold住吧，应该影响不大
