### ISSUE TITLE
是否考虑兼容ant@2.x

### ISSUE THREAD

**Issue by lianyzhou** [alibaba/uform#24]
一些老项目还停留在ant 2.x版本，是否 @uform/antd中不限制dependencies中必须使用3.x，而是以peerDependencies的形式约束。

**Comment by janryWang** [comment]
我们目前还不确定ant 2.x与3.x的API差异有多大，是否会影响平滑切换，这个还需要进一步评估，当然，您也可以协助我们一起判断
