### ISSUE TITLE
能否放开description的字数限制，或者给个属性什么的来决定是否转换成 “问号”

### ISSUE THREAD

**Issue by guxiansheng** [alibaba/uform#241]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of UForm?
  - Did this work in previous versions of UForm?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
看文档，这个能力早就支持了，在SchemaForm上配maxTipsNum

**Comment by janryWang** [comment]
后面注意提issue的格式，如果是Bug，还有RFC提议，就提issue，如果是提问的，统一在答疑群里提问
