### ISSUE TITLE
[Umbrella] UForm Effect hooks

### ISSUE THREAD

**Issue by janryWang** [alibaba/uform#244]
因为对UForm做了typescript重构之后，发现UForm在很多地方，其实是对typescript不够友好的，特别是在effects函数中对事件的监听写法，通过字符串的方式来监听事件，对2019年的前端社区来说，其实已经算过时的东西了。

所以，我们是否可以考虑采用类似于react hooks的写法？比如：

```jsx
import { SchemaForm} from '@uform/antd'
import { onFieldChange,onFormInit } from '@uform/lifecycle'
const effects = ()=>{
   onFormInit().subscribe(()=>{

   })
   onFieldChange('xxxx').subscribe(()=>{

   })
}

React.render(<SchemaForm effects={effects}>....</SchemaForm>)
```

这样的写法有个好处，就是我们的事件处理逻辑可以很方便的复用了。比如：

```
import { SchemaForm } from '@uform/antd'
import { onFieldChange,onFormInit } from '@uform/lifecycle'

const injectBasicInfo = (params)=>{
   onFormInit().subscribe(()=>{

   })
   onFieldChange('xxxx').subscribe(()=>{

   })
}

const injectFinanceInfo = (params)=>{
   onFormInit().subscribe(()=>{

   })
   onFieldChange('xxxx').subscribe(()=>{

   })
}

const effects = ()=>{
   injectBasicInfo()
   injectFinanceInfo()
}

```

所以总的来说，这种写法，对typescript友好，同时，方便复用，而且它是一个扩展能力，并不对原有写法有任何侵入，完全no break change.

**Comment by welkang** [comment]
```
import { SchemaForm} from '@uform/antd'
import { onFieldChange, onFormInit } from '@uform/lifecycle'
const effects = ()=>{
   onFormInit(() => {

   });
   onFieldChange('xxxx', () => {

   });
}

React.render(<SchemaForm effects={effects}>....</SchemaForm>)
```
这样是不是更简洁一些？

**Comment by stkevintan** [comment]
我写effect的时候首先会把变成一个可枚举的对象，然后用一个wrap抱起来：
``` typescript
export const helperFactory = (...args: EffectParameters) => {
  const [_$, options] = args
  const $ = _$ as (
    eventName: string,
    selector?: string | IFormPathMatcher
  ) => Observable<any>
  const { setFieldState } = options
  return {
    onFieldChange: (selector?: string | IFormPathMatcher) => {
      return $('onFieldChange', selector) as Observable<IFieldState>
    },
    onFormInit: () => $('onFormInit'),
    onFormMount: () => $('onFormMount'),
    onFormReset: () => $('onFormReset'),
    onFormSubmit: () => $('onFormSubmit'),
    onEvent: (event: string) => $(event),
}
```

感觉：
1. 字符串作为event的token容易写错，不如用一个`tokenCreator`函数，产出一个symbol或者一种不容易重复的东西
2. 内部的事件我觉得直接封装为onFormInit$, onFormMount$方法我觉得更好，不容易混淆
3. `$(xxx)`产出是一个`subject`，不太合理，应该返回一个Observable对象，让用户只能`subscribe`，无权调用`next`，所有用户自定义事件产出都应该交由`dispatch`完成

**Comment by janryWang** [comment]
> 我写effect的时候首先会把变成一个可枚举的对象，然后用一个wrap抱起来：
> 
> ```ts
> export const helperFactory = (...args: EffectParameters) => {
>   const [_$, options] = args
>   const $ = _$ as (
>     eventName: string,
>     selector?: string | IFormPathMatcher
>   ) => Observable<any>
>   const { setFieldState } = options
>   return {
>     onFieldChange: (selector?: string | IFormPathMatcher) => {
>       return $('onFieldChange', selector) as Observable<IFieldState>
>     },
>     onFormInit: () => $('onFormInit'),
>     onFormMount: () => $('onFormMount'),
>     onFormReset: () => $('onFormReset'),
>     onFormSubmit: () => $('onFormSubmit'),
>     onEvent: (event: string) => $(event),
> }
> ```
> 
> 感觉：
> 
> 1. 字符串作为event的token容易写错，不如用一个`tokenCreator`函数，产出一个symbol或者一种不容易重复的东西
> 2. 内部的事件我觉得直接封装为onFormInit$, onFormMount$方法我觉得更好，不容易混淆
> 3. `$(xxx)`产出是一个`subject`，不太合理，应该返回一个Observable对象，让用户只能`subscribe`，无权调用`next`，所有用户自定义事件产出都应该交由`dispatch`完成
1. 字符串作为event token的问题effect hook可以解决
2. 命名上，的确用$作为后缀比较适合
3. 返回Observable的建议很好

**Comment by hmz5** [comment]
> ```
> import { SchemaForm} from '@uform/antd'
> import { onFieldChange, onFormInit } from '@uform/lifecycle'
> const effects = ()=>{
>    onFormInit(() => {
> 
>    });
>    onFieldChange('xxxx', () => {
> 
>    });
> }
> 
> React.render(<SchemaForm effects={effects}>....</SchemaForm>)
> ```
> 
> 这样是不是更简洁一些？

这样就限制了好多功能，外部就不能增加pipe了
