### ISSUE TITLE
defaultValue、initialValues, value的区别

### ISSUE THREAD

**Issue by wzw007** [alibaba/uform#245]
关于defaultValue、initialValues, value的区别和使用场景， 文档描述得很简单， 能补充一下吗

**Comment by changkem** [comment]
> 关于defaultValue、initialValues, value的区别和使用场景， 文档描述得很简单， 能补充一下吗

defaultValue是非受控状态下的初始值，而initalValues是受控状态下的初始值（使用了value的情况下想使用初始值，则使用initalValues），value则是表单的值
