### ISSUE TITLE
详情页文字展示样式

### ISSUE THREAD

**Issue by ZirkleTsing** [alibaba/uform#248]
1. How would you tag this issue?
  - Enhancement

2. Describe your issue:

  - What is the current behavior?
 目前详情页的文字的统一样式是word-break:keep-all,在文字很多的情况下有不换行的问题:
![image](https://user-images.githubusercontent.com/12378910/62767533-7c689e00-bac7-11e9-9e52-558413388c0e.png)
  - What is the expected behavior?
希望详情页表现形式如下:
![image](https://user-images.githubusercontent.com/12378910/62767457-475c4b80-bac7-11e9-89db-c2ebe5f261f2.png)

**Comment by atzcl** [comment]
这个是你自己的样式吧？方便用 [https://codesandbox.io](https://codesandbox.io) 给个复现的例子吗？
