### ISSUE TITLE
目前似乎不支持cascader？

### ISSUE THREAD

**Issue by yinxuan1128** [alibaba/uform#25]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:
目前只提供一些基本组件，类似cascader，tree这些组件留给用户自定义吗？
.

**Comment by janryWang** [comment]
是的，使用registerFormField自己注册

**Comment by yaoguoba** [comment]
有例子吗？我想使用Textarea不知道怎么弄

**Comment by yinxuan1128** [comment]
我用registerFormField注册了，只是显示的缺省提示是英文，locale应该怎么设置啊？

**Comment by yaoguoba** [comment]
发出来给我个参考啊，谢谢

**Comment by yinxuan1128** [comment]
registerFormField('area', connect()((props) => {
  return <Input.TextArea value={props.value} rows={props.rows} onChange={e => props.onChange(e.target.value)} />
}));示例里有啊

**Comment by yinxuan1128** [comment]
@janryWang 请问SchemaForm里的locale怎么设置啊？

**Comment by janryWang** [comment]
> @janryWang 请问SchemaForm里的locale怎么设置啊？

您是想设置哪个组件的locale呢

**Comment by yinxuan1128** [comment]
我现在注册的组件cascader，包括现在示例里的select daterange 似乎都是英文的，schemaform和field里面都有locale 但是该怎么设置呢？文档有很多还是不够详细的地方

**Comment by yaoguoba** [comment]
> registerFormField('area', connect()((props) => {
>   return <Input.TextArea value={props.value} rows={props.rows} onChange={e => props.onChange(e.target.value)} />
> }));示例里有啊

谢谢哈，我没找到示例

**Comment by janryWang** [comment]
> 我现在注册的组件cascader，包括现在示例里的select daterange 似乎都是英文的，schemaform和field里面都有locale 但是该怎么设置呢？文档有很多还是不够详细的地方

感谢反馈，locale这部分的文档缺失，我们会尽快加上

**Comment by janryWang** [comment]
already fixed.
