### ISSUE TITLE
编辑 virtualBox 中的字段无法触发重新渲染

### ISSUE THREAD

**Issue by fanxiaokun** [alibaba/uform#259]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

bug

2. Describe your issue:

  - What is the current behavior?
当 type 为 object 的属性设置了 x-component 是 virtualBox 的时候，编辑该属性的字段无法触发更新

  - What is the expected behavior?
编辑字段后应该可以正常触发更新
  - Which versions of UForm?
0.3.10
  - Did this work in previous versions of UForm?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.重现 https://codesandbox.io/s/magical-cookies-l9toc?fontsize=14

**Comment by janryWang** [comment]
不是bug，用法问题，因为你自己的组件没有接收enum属性，具体看看这个例子 https://codesandbox.io/s/elegant-cdn-t6biv

**Comment by fanxiaokun** [comment]
不好意思啊，应该是上个例子我举的不太对，按照你给我的例子，我重新试了下，应该还是有问题。
具体问题如下：VirtualBox放在组件内创建，会导致字段不会重新update,而按照常规做法，放在组件外，就会正常update。
重现：https://codesandbox.io/s/magical-cookies-l9toc?fontsize=14

**Comment by fanxiaokun** [comment]
> 不是bug，用法问题，因为你自己的组件没有接收enum属性，具体看看这个例子 https://codesandbox.io/s/elegant-cdn-t6biv

不好意思啊，应该是上个例子我举的不太对，按照你给我的例子，我重新试了下，应该还是有问题。
具体问题如下：VirtualBox放在组件内创建，会导致字段不会重新update,而按照常规做法，放在组件外，就会正常update。
重现：https://codesandbox.io/s/magical-cookies-l9toc?fontsize=14
