### ISSUE TITLE
基于antd的select类型field，首次触发时出现警告 Warning: Invalid attribute name: `0`

### ISSUE THREAD

**Issue by sotoup** [alibaba/uform#26]
基于antd的select类型field，首次触发时出现警告 Warning: Invalid attribute name: `0`
官方给出实例就有此问题
[https://codesandbox.io/s/nry5o9lnx4](https://codesandbox.io/s/nry5o9lnx4)

**Comment by janryWang** [comment]
这个是antd的Select组件的下拉Menu组件将label/value组成了具体的属性传给了MenuItem组件，造成React报warning.
![image](https://user-images.githubusercontent.com/4060976/56955747-cf4fc280-6b74-11e9-8d51-1c57403bf45e.png)
Demo里的例子只是最简单体现json schema的enum枚举.
我们实际业务使用的话，是会
```
<Field type="string" enum={[{label:"aaa",value:"1",label:"bbb",value:"2"}]} name="string"/>
```
所以，在实际业务场景，并不会报该warning的。

**Comment by oubinke** [comment]
> 这个是antd的Select组件的下拉Menu组件将label/value组成了具体的属性传给了MenuItem组件，造成React报warning.
> ![image](https://user-images.githubusercontent.com/4060976/56955747-cf4fc280-6b74-11e9-8d51-1c57403bf45e.png)
> Demo里的例子只是最简单体现json schema的enum枚举.
> 我们实际业务使用的话，是会
> 
> ```
> <Field type="string" enum={[{label:"aaa",value:"1",label:"bbb",value:"2"}]} name="string"/>
> ```
> 
> 所以，在实际业务场景，并不会报该warning的。

应该是<Field type="string" enum=[{label:"aaa",value:"1"},{label:"bbb",value:"2"}] name="string"/>
