### ISSUE TITLE
SchemaForm中使用virtualBox自定义 antd 的Tab,TabPane的tab配置不生效

### ISSUE THREAD

**Issue by fanxiaokun** [alibaba/uform#260]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
Question
2. Describe your issue:

  - What is the current behavior?
SchemaForm中使用virtualBox自定义 antd 的Tab,TabPane的tab配置不生效
  - What is the expected behavior?
在SchemaForm中可以正常使用Tab标签页
  - Which versions of UForm?
0.3.10
  - Did this work in previous versions of UForm?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.重现 https://codesandbox.io/s/kind-chatelet-r5f28?fontsize=14

**Comment by janryWang** [comment]
用法不对，建议这样使用 https://codesandbox.io/s/silent-rain-wyd5b
