### ISSUE TITLE
Table类型的表单List组件，当某一条Field触发校验后，再删除，该索引位置的校验状态还在

### ISSUE THREAD

**Issue by changkem** [alibaba/uform#267]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - What is the current behavior?
 Table类型的表单List组件，当某一条Field触发校验后，再删除，该索引位置的校验状态还在
  - What is the expected behavior?
 当某一条Field触发校验后，再删除，该索引位置的校验状态应该清除
  - Which versions of UForm?
 `@uform/next@0.3.10`
  - Did this work in previous versions of UForm?
 未知
3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
**CodeSandbox:** https://codesandbox.io/s/cold-grass-tkepb?fontsize=14

**Comment by janryWang** [comment]
这个问题先hold住，内核重构的时候会fix
