### ISSUE TITLE
Disabled fields could not be changed in array when reordering the array

### ISSUE THREAD

**Issue by slobber** [alibaba/uform#27]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of UForm?
  - Did this work in previous versions of UForm?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.
press up/down button in the array field, inputs will be changed but the textField won't.

https://codesandbox.io/s/qzo660or2j

**Comment by janryWang** [comment]
Thank you for reporting the bug and we will fix it as soon as possible, but for schema-driven rendering Form, your usage is not what we recommend. You can refer to this example. https://codesandbox.io/s/kk9620ymjr

**Comment by slobber** [comment]
Got it, thanks.

**Comment by janryWang** [comment]
already fixed.
