### ISSUE TITLE
FormBlock in TypeScript

### ISSUE THREAD

**Issue by YikaJ** [alibaba/uform#271]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug

2. Describe your issue:

  - What is the current behavior?
在 TypeScript 下使用，FormBlock 等 layout 组件需要文档中不存在的属性，name / render。

![image](https://user-images.githubusercontent.com/8725110/63250505-64023b80-c29e-11e9-852a-c34823378eee.png)

![image](https://user-images.githubusercontent.com/8725110/63250309-eccca780-c29d-11e9-996c-1b5498642c00.png)

![image](https://user-images.githubusercontent.com/8725110/63251098-98c2c280-c29f-11e9-8026-30e986c9421a.png)

  - What is the expected behavior?

去掉 name / render 等属性

  - Which versions of UForm?

@uform/antd@0.3.11

  - Did this work in previous versions of UForm?

no

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by YikaJ** [comment]
希望能保持和文档一致，不然会有比较大的疑惑。

**Comment by atzcl** [comment]
`name、render` 的类型已经修正为可选参数了


> 去掉 name / render 等属性

`FormBlock` 等 layout 组件在本质上就是个 `SchemaField` 组件, 所以是会暴露出 `name、render` prop 的，具体可看 [https://uformjs.org/#/97UlUl/3wF9F5UnUJ](https://uformjs.org/#/97UlUl/3wF9F5UnUJ)
