### ISSUE TITLE
不支持标准jsonschema的验证， 是否考虑引入ajv来支持

### ISSUE THREAD

**Issue by wzw007** [alibaba/uform#272]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Enhancement
2. Describe your issue:
  - Which versions of UForm?
     any version
.

**Comment by janryWang** [comment]
目前您对标准的json-schema验证的需求主要是哪些属性？

**Comment by wzw007** [comment]
maximum, minimum、maxLength, minLength, pattern, format、maxItems, minItems, uniqueItems 等等
