### ISSUE TITLE
<Field />组件最好能增加隐藏标签的功能

### ISSUE THREAD

**Issue by effapp** [alibaba/uform#279]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Feature request

2. Describe your issue:

 <Field />组件最好能增加隐藏标签的功能

**Comment by atzcl** [comment]
是要隐藏 label 嘛？

**Comment by effapp** [comment]
> 是要隐藏 label 嘛？

是的，最好能增加一个属性，用来设置是否隐藏lable的

**Comment by monkindey** [comment]
能方便说下应用场景吗？

**Comment by effapp** [comment]
比如说，我要在标签和输入框中间插入别的组件（如：下拉框），我就可以自己写lable + 其它组件 + <Field />:

**Comment by effapp** [comment]
我还可以写两个Field组件，只用一个标签：如 ："金额：  Field组件1   field组件2"
其中， Field组件1是下拉框，大于、小于、等于。。。，field组件2是输入框，这样的话我就可以通过SchemaForm取到“Field组件1”的值。

**Comment by atzcl** [comment]
这样会有样式的问题需要处理

**Comment by effapp** [comment]
只需要在Field组件增加一个属性，设置Field组件的label显示还是不显示就可以啦，可以增加吗？

**Comment by atzcl** [comment]
@effapp 你直接把 `title` 给去掉就可以了，例子：[https://codesandbox.io/s/wizardly-grothendieck-3uq9t](https://codesandbox.io/s/wizardly-grothendieck-3uq9t)

**Comment by janryWang** [comment]
@atzcl 已经给出方案
