### ISSUE TITLE
如何用UForm实现如下图所示的选择输入框

### ISSUE THREAD

**Issue by effapp** [alibaba/uform#280]
1. How would you tag this issue?

  - Question
 
2. Describe your issue:

 如何用UForm实现如下图所示的选择输入框：
![image](https://user-images.githubusercontent.com/51013754/63502626-8b584300-c500-11e9-8e37-3759545243fc.png)

**Comment by atzcl** [comment]
使用 `x-props` 来传入对应原生组件的 `props` 就好了

例子：
[https://codesandbox.io/s/wizardly-grothendieck-3uq9t](https://codesandbox.io/s/wizardly-grothendieck-3uq9t)

**Comment by effapp** [comment]
> 使用 `x-props` 来传入对应原生组件的 `props` 就好了
> 
> 例子：
> https://codesandbox.io/s/wizardly-grothendieck-3uq9t

请问，怎样取到 `x-props` 传入的对应原生组件的addonBefore的值呢？

![image](https://user-images.githubusercontent.com/51013754/63564354-5a771d00-c597-11e9-8f8c-62d8cd1faff5.png)

**Comment by atzcl** [comment]
目前大概只有两种方式吧 🤔

1. 监听 addonBefore 的 Select onChange, 以前怎么处理就怎么处理

2. 使用 registerFormField 来包装定制一个这样的组件，来简化使用

**Comment by effapp** [comment]
当把addonBefore的内容换成Field组件时，没有任何显示，如果可以用Field组件更佳：
const addonBefore = (
    <Field
        type="string"
        enum={['1', '2', '3', '4']}
        required
        title="Select"
        name="select"
      />
  );

**Comment by atzcl** [comment]
@effapp 例子已更新

**Comment by janryWang** [comment]
这种需求，用自定义组件实现
