### ISSUE TITLE
使用Field组件作为x-props时，不能正常显示，而用其它antd组件则能正常显示：

### ISSUE THREAD

**Issue by effapp** [alibaba/uform#281]
1. How would you tag this issue?

   - Bug
 
2. Describe your issue:
使用Field组件作为x-props时，不能正常显示，而用其它antd组件则能正常显示：
 
![image](https://user-images.githubusercontent.com/51013754/63631281-e0f33380-c657-11e9-8a95-c4d64037a68a.png)

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
bug实例：
https://codesandbox.io/s/upbeat-microservice-sw5kv

**Comment by janryWang** [comment]
<Field/>组件不是一个普通UI组件，所以不能随便使用的，只能再SchemaForm中使用
