### ISSUE TITLE
如何同时控制多个<SchemaForm />的validate或者submit行为？

### ISSUE THREAD

**Issue by NenX** [alibaba/uform#284]
1. How would you tag this issue?

  - Discussion

2. Describe your issue:
  页面有多个`<SchemaForm />,` ，需要合并FormState并同时submit，有什么比较优雅到方式吗？

**Comment by janryWang** [comment]
Promise.all([actions1.submit(),actions2.submit(),actions3.submit()])这样处理能否解决你的需求？

**Comment by NenX** [comment]
@janryWang 我的需求是想合并actions，然后拿到合并后的actions做统一的validate、setFormState、getFormState等操作。例如：
```javascript
const allActions = merge(actions1,actions2,...);
allActions.validate().then(
    formState => {
        mySubmit(formState.value)
    }
)
allActions.setFormState(state => state.value = someData)
```

**Comment by janryWang** [comment]
目前是不支持合并的
