### ISSUE TITLE
通过action.reset重置后，输入内容会触发Field的校验

### ISSUE THREAD

**Issue by zxv1026** [alibaba/uform#285]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

  -2. Describe your issue:

  - What is the current behavior?
输入名称和地址，点击取消，再次输入名称时，地址的错误提示会出现
  - What is the expected behavior?
输入名称和地址，点击取消，再次输入名称时，地址的错误提示不出现

3.  [https://codesandbox.io/s/blissful-archimedes-knrg2](https://codesandbox.io/s/blissful-archimedes-knrg2)

**Comment by wangxiaofeid** [comment]
actions.reset(true, false)，有参数的
