### ISSUE TITLE
[Bug Report] extends Form  in typescript  error   'Form' cannot be used as a value because it was exported using 'export type'.

### ISSUE THREAD

**Issue by StarHosea** [alibaba/uform#2889]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily/issues/new/choose)

### Steps to reproduce
```
import { Form as FormilyForm } from '@formily/core';
//TS1362: 'FormilyForm' cannot be used as a value because it was exported using 'export type'
export class Form extends FormilyForm {
  
}

```

### What is expected?
```
import { Form as FormilyForm } from '@formily/core';
export class Form extends FormilyForm {
  
}

```

### What is actually happening?
```
import { Form as FormilyForm } from '@formily/core';
//TS1362: 'FormilyForm' cannot be used as a value because it was exported using 'export type'
export class Form extends FormilyForm {
  
}

```

### Package
@formily/core@2.0.13

---

**Comment by janryWang** [comment]
故意控制Form只导出类型的，就是防止用户魔改扩展
