### ISSUE TITLE
@uform/react的index.d.ts好像有问题，没有导出registerFormField等方法

### ISSUE THREAD

**Issue by chenjigeng** [alibaba/uform#29]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - Which versions of UForm?
  0.1.8
  在ts项目里使用UForm，发现registerFormField等方法没有声明。
![image](https://user-images.githubusercontent.com/14784326/57147360-fa971380-6df9-11e9-818e-63650398ca1c.png)

**Comment by janryWang** [comment]
already fixed.
