### ISSUE TITLE
array类型能否支持[1, 'string', {key: value}]这种schema结构

### ISSUE THREAD

**Issue by Jsonya** [alibaba/uform#298]
## 问题描述
目前uform无法实现标准schema规范下的array不同子item类型渲染，比如能够通过定义下面的schema正常渲染子项的控件，但最终获取的值为数组。
```json
{
  "type": "array",
  "items": [{
    "type": "string"
  }, {
    "type": "number"
  }]
}
```

## 疑问
- 是否有计划支持这个结构呢？
- 在目前不支持该结构的前提下，有没有其他比较好的解决方案呢？自定义组件？还是拆分成对象结构再拼装比较合适

## 版本
- @uform/antd: 0.3.11
- @uform/react: 0.3.11

**Comment by janryWang** [comment]
这个不是标准的json-schema，建议还是拆成ObjectList来维护

**Comment by Jsonya** [comment]
> 这个不是标准的json-schema，建议还是拆成ObjectList来维护

但是文档中有提到这种结构呀？ https://json-schema.org/understanding-json-schema/reference/array.html

**Comment by suinia** [comment]
碰到同样的问题....标准json schema是这样, 但是显示不出来。
得把enum: ['ACCOUNT',  'PAY']提到外层
但是需求是后端也需要做一层校验 只能按标准的来
```
{
      type: 'object',
      properties: {
        test: {
          type: 'array',
          title: 'test',
          items: {
            enum: ['ACCOUNT',  'PAY'],
            type: 'string'
          },
          'x-component': 'checkbox'
        }
      }
    }
```
