### ISSUE TITLE
表单回填的时候不会触发onFieldChange

### ISSUE THREAD

**Issue by huaibaomengxiang** [alibaba/uform#299]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - 表单回填之后不会触发onFieldChange
  - 可以触发onFieldChange
  - "@uform/next": "^0.3.9",
  - Did this work in previous versions of UForm? 不清楚

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.https://codesandbox.io/s/suspicious-sun-qy9qq

**Comment by huaibaomengxiang** [comment]
复现步骤 切换协议然后点击按钮

**Comment by janryWang** [comment]
用例有问题：
第一：useState的参数，如果每次传的引用一样的话，是不会触发rerender
第二：为什么要先reset，然后再设置值？这样做的目的是什么？是希望重置数据，还是希望刷新数据，如果是刷新数据的话，那为啥每次的数据又是一样的，目前uform做了diff判断，如果数据结构一样的，是不会触发更新的
