### ISSUE TITLE
antd cards 写法有笔误

### ISSUE THREAD

**Issue by lingxufeng2014** [alibaba/uform#30]
antd 文件夹内的antd 使用，可否整体都改成 import {xxx} from 'antd' 这种形式呢？

其中 cards 文件引入 card 的写法是这样的：
`import Card from "antd/lib/card"
`
这么写倒是没问题，但在 umd 引入 antd 的背景下，这里确定会报错。

-------
以上，谢谢！

**Comment by janryWang** [comment]
不是笔误呢，故意这么写的，因为不希望整体打包，如果您是umd方式使用的话，可以把antd/lib/card external到antd.Card上

**Comment by lingxufeng2014** [comment]
@janryWang 弱弱问一句，为啥这么操作呢？ 我大致琢磨了下源码，antd 文件夹里面就这一个是这么写的，非常好奇原因。

**Comment by janryWang** [comment]
还真是笔误，非常不好意思，我会尽快修复这个问题

**Comment by janryWang** [comment]
目前在v0.1.10中已修复
