### ISSUE TITLE
[Bug] 日期 Field 在 disabled 条件下报错

### ISSUE THREAD

**Issue by DelBlank** [alibaba/uform#302]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  如题

**[复现](https://codesandbox.io/s/zen-flower-do2o6)**

![image](https://user-images.githubusercontent.com/32668387/64341293-9d66d500-d01a-11e9-919a-a6a1fc0c79d1.png)

**Comment by DelBlank** [comment]
预计什么时候可以修复 @janryWang

**Comment by DelBlank** [comment]
这个改起来应该比较快

**Comment by janryWang** [comment]
> 这个改起来应该比较快

周日发版

**Comment by DelBlank** [comment]
好的，辛苦了 @janryWang
