### ISSUE TITLE
[Bug Report] mv @formily/core and @formily/vue as [devDeps] and [peerDeps]

### ISSUE THREAD

**Issue by skyfore** [alibaba/uform#3076]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-shadow-q43fum?file=/package.json)

### Steps to reproduce
Install **@formily/element@2.0.18** and **@formily/core@2.0.20** **@formily/vue@2.0.20**

@formily/element 版本与 core 和 vue 版本不一致

### What is expected?
work as expect

能够正常生效，联动、数据渲染等等

### What is actually happening?
-

### Package
@formily/element@2.0.20

---

为什么不考虑在基础组件库层面上将 @formily/core @formily/vue 等依赖声明为 peerDeps，因为在实际业务场景中有可能会出现 @formily/core 修复了一些问题，但是业务中并不想更新 @formily/element 组件库版本，这样会强制要求用户一定要保持 @formily 相关库版本一致，这一部分内容也没有在文档中体现。

**Comment by janryWang** [comment]
这是包管理策略，保证所有包同一个版本，方便回滚，至于你说的桥接库版本的这个问题，后面会把所有桥接库移到formilyjs分组里，这样就会独立版本控制了
