### ISSUE TITLE
[Bug Report] formilyjs 在pnpm v7 版本peerDependencies无法下载包问题

### ISSUE THREAD

**Issue by faner11** [alibaba/uform#3094]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-react-antd-pure-jsx-omncis)

### Steps to reproduce
将pnpm 升级为 v7版本，删除node_modules, 执行 pnpm i 即可触发，原因是formilyjs 的react依赖为>=17.0.0, 应该改为^17.0.0 就可以了

### What is expected?

pnpm 的方案 https://pnpm.io/zh/package_json

可以正常pnpm i ，

### What is actually happening?
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
├─┬ autoprefixer
│ └── ✕ missing peer postcss@^8.1.0
├─┬ @formily/antd
│ ├── ✕ missing peer react-is@">=16.8.0 || >=17.0.0"
│ ├─┬ @formily/react
│ │ ├── ✕ missing peer react-is@">=16.8.0 || >=17.0.0"
│ │ └─┬ @formily/reactive-react
│ │   └── ✕ missing peer react-is@">=16.8.0 || >=17.0.0"
│ ├─┬ react-sticky-box
│ │ ├── ✕ missing peer prop-types@^15.6.2
│ │ └── ✕ unmet peer react@"^0.14.0 || ^15.0.0 || ^16.0.0": found 17.0.2
│ └─┬ react-sortable-hoc
│   ├── ✕ unmet peer react@"^0.14.0 || ^15.0.0 || ^16.0.0": found 17.0.2
│   └── ✕ unmet peer react-dom@"^0.14.0 || ^15.0.0 || ^16.0.0": found 17.0.2
├─┬ styled-components
│ └── ✕ missing peer react-is@">= 16.8.0"
└─┬ less-loader
  └── ✕ missing peer webpack@^5.0.0
Peer dependencies that should be installed:

### Package
@formily/antd@2.1.0

---

**Comment by janryWang** [comment]
来个PR吧
