### ISSUE TITLE
[Bug Report] setSelfErrors 在某些情况下生效

### ISSUE THREAD

**Issue by ghost** [alibaba/uform#3114]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-test-4sg5km?file=/App.tsx)

### Steps to reproduce
1.初始化时候 设置`onFieldValueChange `值不满足条件执行` field.setSelfErrors(["show error"]);`,
2. 手动设置一个值
3. 再设置field 为阅读态
 

### What is expected?
`setSelferrors`生效 字段出现 error

### What is actually happening?
field.setSelfErrors(["show error"]);`没有生效

### Package
@formily/core@2.1.1

---

先设置 field 为阅读态 在设置 field的value 是ok 的

**Comment by weixihd** [comment]
你好请问你解决这个问题了吗？自定义的组件在JSON Schema 中用的时候，useField创建的field调用setSelfErrors无效，在JSX中用的时候就没问题，你知道该怎么解决吗?
