### ISSUE TITLE
[Bug Report] Unable to set data in reactions

### ISSUE THREAD

**Issue by ccpu** [alibaba/uform#3124]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reactive-setdata-issue-0vyetq?file=/App.tsx)

### Steps to reproduce
1. open sandbox
2. enter text in input, label should change

### What is expected?
should be able to set `setData` or `field.data=...` in reactions.

### What is actually happening?
setting `setData` or `field.data=...`  not triggering `useField` data field

### Package
@formily/core@2.1.2

---

While I believe I can use `setContent` for this purpose, I thought I would mention it here in case there is a bug.

**Comment by janryWang** [comment]
setData is not setValue，just use to store some user custom value, so that the user can use it inside the component via useField().data

**Comment by frehaiku** [comment]
If your want to update label, the `Label` Component need wrap `observer` API via `@formily/react`.

**Comment by ccpu** [comment]
> If your want to update label, the `Label` Component need wrap `observer` API via `@formily/react`.

Ohh, i missed the observer, that exactly solved the issue, thank you.
