### ISSUE TITLE
[Bug Report] 表单设计器“自增表格“无法作为来源字段被别的组件依赖

### ISSUE THREAD

**Issue by zoley** [alibaba/uform#3135]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/designable/tree/main/formily/antd/playground)

### Steps to reproduce
https://designable-antd.formilyjs.org/

打开官方设计器地址，拖拽 自增表格 以及 input 框，对input配置响应器，在依赖 来源字段里无法找到 自增表格组件，做不到外部联动计算。如下图所示

![](https://s3.bmp.ovh/imgs/2022/05/19/f3f563f722dab4e8.jpg)

![](https://s3.bmp.ovh/imgs/2022/05/19/f1763b2f56cb5580.jpg)

### What is expected?
1、希望“自增表格“可以作为来源字段被别的组件依赖

2、或者 给自增表格 ArrayTable 增加onChange事件，使其数据的变化可以被实时监听到。（目前的onChange应该是无效的）

### What is actually happening?
1、“自增表格“没有作为来源字段被别的组件依赖

2、自增表格 ArrayTable 的onChange无效，监听不到数据的变化

### Package
@formily/antd@2.1.2

---

**Comment by janryWang** [comment]
用高级模式，form.query自己查找array table字段
