### ISSUE TITLE
[Feature Request] 移动端antd-mobile怎么搭配formily使用？

### ISSUE THREAD

**Issue by XuZhongqiang** [alibaba/uform#3150]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我的h5业务中有个动态表单的场景，UI库使用的是antd-mobile，希望能使用formily的json schema能力，但是当前的formily体系不能够兼容antd-mobile组件库。

### What does the proposed API look like?
@formily/antd-mobile?

**Comment by janryWang** [comment]
https://github.com/formilyjs/antd-mobile 
其实本身就有，只是之前维护该项目的人不没精力继续维护了，连发个基础版本的时间都没有，本身formily是非常欢迎社区共建的，推荐大家，有需求，直接上，而不是等着用
