### ISSUE TITLE
[Bug Report] @formily/antd   ArrayTable 数据中有children时children 数据显示不出来 

### ISSUE THREAD

**Issue by siyuejiwang** [alibaba/uform#3152]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily)

### Steps to reproduce
当arrayTable  数据为  [{name: 1, children: [{name: 2}]}]  这种格式时， chidlren 值没显示
![image](https://user-images.githubusercontent.com/13113046/170668325-fc3b7767-505a-403c-9493-013f5de92f86.png)
改了下好像可以。恳请大佬有空的时候修改下这个问题

### What is expected?
能够显示children下的数据

### What is actually happening?
未显示children下数据

### Package
@formily/antd@2.1.1

---

**Comment by janryWang** [comment]
不支持
