### ISSUE TITLE
[Bug Report] After sorting array items, the "mounted" property value of some array items changes to false

### ISSUE THREAD

**Issue by ccpu** [alibaba/uform#3157]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-array-sort-mount-issue-xllgyv?file=/App.tsx)

### Steps to reproduce
- Add two new items
- Sort array items using the handle
- Enter a value for the first item
- Check the console for information regarding the `mounted` state of the fields

![Animation](https://user-images.githubusercontent.com/4041334/170882467-748ef2a8-5486-427c-836e-a7538aec9403.gif)

### What is expected?
The `mounted` property value should be `true` since items are visible.

### What is actually happening?
The `mounted` property value of some items becomes `false` after sorting.

### Package
@formily/core@2.1.4

---

**Comment by janryWang** [comment]
Hi @ccpu, if you can confirm that this is a bug, welcome to PR, or very welcome to help us to further investigate the cause of the problem, which will facilitate us to quickly fix this problem, I found that the questions you raised are basically very advanced and professional Problem, the repair process is very time consuming, we will be very grateful if we can get further help from you.

**Comment by ccpu** [comment]
Hi @janryWang, After further investigation, I have concluded that the issue may be a race condition within the [useAttach.ts](https://github.com/alibaba/formily/blob/formily_next/packages/react/src/hooks/useAttach.ts) file. 

Wrapping [target.onMount()](https://github.com/alibaba/formily/blob/dad0816f332dc3f03f3d32382cd59c3866e25a40/packages/react/src/hooks/useAttach.ts#L15) as follows will solve the issue:

```ts
    window.requestIdleCallback(() => {
      target.onMount()
    })
```

However, using `requestIdleCallback` is not recommended, as it can cause other issues and restrict the formily to only being used in browsers.

The other solution would be to memoize target fields:

```ts
  const fieldMemo = React.useMemo(() => 
    form.createField({ basePath: parent?.address, ...props })
  , [])

  const field = useAttach(fieldMemo);
```
However, this will result in sortability problems since the [index has been used for the key,](https://github.com/alibaba/formily/blob/dad0816f332dc3f03f3d32382cd59c3866e25a40/packages/antd/src/array-items/index.tsx#L99) i think generating Id for each item and attaching it to the array item upon creation would be a better solution than using the index.

The current schedule I have leaves me very little time for further investigation, but I'll have a look at it again if i get a chance.

I hope it helps.
