### ISSUE TITLE
[Bug Report] 可预览模式的 schema 无法切换至设计模式。

### ISSUE THREAD

**Issue by jianxiaoBai** [alibaba/uform#3158]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://designable-antd.formilyjs.org/

### Steps to reproduce
1. 打开 https://designable-antd.formilyjs.org/
2. 拖拽一个 InputNumber 输入框
3. 编辑《格式转换器》
4. 输入： function (val) { return val }
5. 切换预览模式
6. 切换回设计模式失败

### What is expected?
期望能成功切换至设计模式

### What is actually happening?
白屏了，控制台报错 “Uncaught TypeError: formatter is not a function”

### Package
@formily/json-schema@2.1.4

---

**Comment by janryWang** [comment]
麻烦提到desingable上去，这里主要收集formily问题
