### ISSUE TITLE
[Bug Report] FormGrid 下使用 DatePicker.RangePicker 时，展开的面板定位不准。

### ISSUE THREAD

**Issue by MEDIOCAL** [alibaba/uform#3167]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lvluk1)

### Steps to reproduce
在第一次打开页面的时候，直接点击DatePicker 框，展开的面板 left 定位为 0；第二次点击就恢复正常了。
可以直接访问官方文档 https://antd.formilyjs.org/zh-CN/components/form-grid 找到 查询表单实现案例 点击展开，点击 DatePicker.RangePicker 就可以复现，再次点击就好了。

### What is expected?
left 应该定位正常

### What is actually happening?
left 第一次为 0

### Package
@formily/antd@2.1.4

---

**Comment by jymsy** [comment]
当input 的宽度大于日期弹窗的宽度的时候就会出现这个问题。
![image](https://user-images.githubusercontent.com/2777671/172110290-872ef4a2-6f23-4e7d-b4a7-3c68066b692e.png)

**Comment by timelessover** [comment]
+1

**Comment by janryWang** [comment]
这是antd的问题吧，FormGrid没有做啥特殊处理的

**Comment by GitYiM** [comment]
遇到相同的问题了，请教下这个最后是怎么解的呢

**Comment by jymsy** [comment]
> 遇到相同的问题了，请教下这个最后是怎么解的呢

宽度改小

**Comment by henryzp** [comment]
@jymsy 把宽度改小，会带来其他的副作用，有什么其他的解法么？

**Comment by jymsy** [comment]
> @jymsy 把宽度改小，会带来其他的副作用，有什么其他的解法么？

什么副作用，我这没问题

**Comment by henryzp** [comment]
比如说grid布局，如果你给它宽度减小，这样无法自适应布局了吧

**Comment by henryzp** [comment]
@jymsy

**Comment by jymsy** [comment]
> 比如说grid布局，如果你给它宽度减小，这样无法自适应布局了吧

可以自适应啊，为什么不能呢，要么就让grid每列的宽度小于弹窗的宽度，要么就手动设置input框的width

**Comment by henryzp** [comment]
@jymsy ，那个grid没法指定宽度吧？

**Comment by henryzp** [comment]
我现在写的是设置input框的width，但是这样的话，会导致这样的问题啊：

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/3849702/236595710-74ff1fa2-1ae9-4eba-b8b1-fc4507d81064.png">

不知道你是怎么处理的？

**Comment by jymsy** [comment]
@henryzp 弹出框的宽度是560px，你这里的input框的宽度不设置width也没到560吧，也会有这个问题么

**Comment by jymsy** [comment]
实在不行就改设计吧，尽量限制外层的最大宽度

**Comment by henryzp** [comment]
有，会出现，而且是必现，第一次就是left: 0，第二次正常了。。。

**Comment by henryzp** [comment]
@jymsy 有，会出现，而且是必现，第一次就是left: 0，第二次正常了。。。

**Comment by henryzp** [comment]
@GitYiM ，你的场景是怎样的？

**Comment by tpc-ht** [comment]
![image](https://github.com/alibaba/formily/assets/59469126/86e66fe7-9a0d-4a6a-8787-6f70877830d4)
![image](https://github.com/alibaba/formily/assets/59469126/865428ae-0f9f-48b4-bd26-0c86b33ed84b)
只要不加  FormGrid 就不会出现弹窗错位。而且input框的宽度也大于弹窗。
![image](https://github.com/alibaba/formily/assets/59469126/3c7e9895-b76d-4280-9822-37b56a1ac03e)
如果input宽度小于弹窗，初次还是错位
所以各位大佬有什么好的解决方案吗？

@formily/antd：2.2.26

**Comment by tpc-ht** [comment]
![image](https://github.com/alibaba/formily/assets/59469126/4191b1a3-33d6-4a02-9331-6e7a57816255)
本地修改 form-grid 源码中的 gridTemplateColumns 可以解决初次弹窗错位的问题
额... 感觉原本写的没啥问题了。我用三元区判空、加默认值，都不行。得必须给 `grid-template-columns: repeat(4, minmax(100px, 400px));` 才可以
