### ISSUE TITLE
能否给一个扩展feild组件的demo

### ISSUE THREAD

**Issue by mediasale** [alibaba/uform#318]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Feature request

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
文档中都有的
