### ISSUE TITLE
[Bug Report] onFieldInit 监听报错 “consume method cannot be used in asynchronous function body”

### ISSUE THREAD

**Issue by BILLYHO** [alibaba/uform#3195]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dry-sound-ettojg?file=/App.tsx)

### Steps to reproduce
直接运行，会报错

input1 监听 input2 的 onFieldInit，会出现报错 “consume method cannot be used in asynchronous function body”

### What is expected?
能够正常监听 input2 的 onFieldInit

### What is actually happening?
报错 “consume method cannot be used in asynchronous function body”

### Package
@formily/core@2.1.5

---

**Comment by janryWang** [comment]
文档从没提过可以在reactions里可以用effects函数，而且非常不推荐这么用

**Comment by xn330125** [comment]
> 文档从没提过可以在reactions里可以用effects函数，而且非常不推荐这么用

请问一下formily[文档](https://react.formilyjs.org/api/shared/schema#schemareactions)里面写的x-reaction可以配置SchemaReactionEffect，这个可以使用吗？

我们配置了这个 x-reactions
```
{
   "effects": ['onFieldInit'],
   "fulfill": {
     "run": "{{scope.getDatasource( $self)}}",
   },
 }
```
发现在第一次渲染后是正常的，但是field在卸载后重新挂载时也会报这个错误（arraytable配置了显隐联动，这个field在arraytable里面）

**Comment by xn330125** [comment]
> > 文档从没提过可以在reactions里可以用effects函数，而且非常不推荐这么用
> 
> 请问一下formily[文档](https://react.formilyjs.org/api/shared/schema#schemareactions)里面写的x-reaction可以配置SchemaReactionEffect，这个可以使用吗？
> 
> 我们配置了这个 x-reactions
> 
> ```
> {
>    "effects": ['onFieldInit'],
>    "fulfill": {
>      "run": "{{scope.getDatasource( $self)}}",
>    },
>  }
> ```
> 
> 发现在第一次渲染后是正常的，但是field在卸载后重新挂载时也会报这个错误（arraytable配置了显隐联动，这个field在arraytable里面）

测试了一下是低版本的问题，最新版本是好的
