### ISSUE TITLE
空值的‘N/A’标识应该可配置

### ISSUE THREAD

**Issue by littleone2018** [alibaba/uform#320]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Feature request

2. Describe your issue:
  - What is the expected behavior?
 运营和产品都认为'N/A'这个标识过于陌生，希望Uform提供配置入口
.

**Comment by cherishh** [comment]
遇到同样的需求，如果值为空希望可以配置。试了下设置x-props的defaultValue为''并不管用

**Comment by betterRunner** [comment]
> 遇到同样的需求，如果值为空希望可以配置。试了下设置x-props的defaultValue为''并不管用

@cherishh 有试过设置`default`属性吗？我设置了default好像是可以的

**Comment by xiaojuown** [comment]
现在可以配置了吗？
