### ISSUE TITLE
[Bug Report] ArrayCollapse 用 index 作为 React.Key

### ISSUE THREAD

**Issue by Hoo1nKyoma** [alibaba/uform#3208]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-hypatia-j8lge3?file=/App.tsx)

### Steps to reproduce
1. 新建两个 ArrayCollapse.CollapsePanel
2. 在第一个 Panel 中的 Input 输入 hello
3. 在第二个 Panel 中的 Input 输入 world
4. 删除第一个 Panel
5. 查看当前第一个 Panel 中的 Input 的内容

### What is expected?
期望结果是 world

### What is actually happening?
实际的结果是 hello

### Package
@formily/antd@2.1.5

---

1. 在 @formily/antd 的 ArrayCollapse 组件中，使用了数组中的 index 来作为 React 的 key 使用，从而导致了该问题。
2. 在 Demo 中，我没有处理 onChange 更快的复现了该问题。

**Comment by janryWang** [comment]
没看懂，什么问题

**Comment by Hoo1nKyoma** [comment]
> 没看懂，什么问题

https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318

直接看这篇文档吧，用了 index 作为 key 带来的负面影响。

如果之前没了解过这个的话，可能要 review 下所有 type Array 的组件了。

**Comment by janryWang** [comment]
先学会描述问题再提issue吧

**Comment by Hoo1nKyoma** [comment]
> 先学会描述问题再提issue吧

已修改复现步骤描述，之前漏了4、5两步，sry

**Comment by janryWang** [comment]
这不是bug，formily的任何自定义组件，都是受控的，你需要接收props.value/props.onChange，这样就能实现数据同步

**Comment by zboMa** [comment]
@Hoo1nKyoma 解决了吗老哥
