### ISSUE TITLE
[Bug Report] update react18 formily not work

### ISSUE THREAD

**Issue by silverWolf818** [alibaba/uform#3219]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/late-mountain-359j2d?file=/src/index.js)

### Steps to reproduce
1. click add button

### What is expected?
click add data show correct

### What is actually happening?
show input add other button

### Package
@formily/core@2.1.6

---

**Comment by YanZiSen** [comment]
+1;
