### ISSUE TITLE
[Bug Report] designable-formily 工具 NumberPicker 组件 配置 formatter 参数报错

### ISSUE THREAD

**Issue by melodyJie** [alibaba/uform#3224]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce

使用官方提供的 formilyjs 线上设计器工具 按照如下步骤操作

1. 选中 NumberPicker 组件
2. 编辑 组件属性中的 格式转换器
3. 输入 ``` value => `$$ ${value}` ```
4. 切换到 `JSONTREE` 模式, 可以看到相关配置: ``` "formatter": "{{value => `$$ ${value}`}}" ```
5. 切换到 `PREVIEW` 模式, 可以看到formily/antd 是正常运行的
6. 切换回 `DESIGNABLE` 模式, 出现报错

![001](https://user-images.githubusercontent.com/19163156/175501797-45cff336-6a1c-46a5-88a3-ba32656dc69e.png)

![002](https://user-images.githubusercontent.com/19163156/175501810-a772df5c-62d8-4c72-88b9-7016f52d72e7.png)

![003](https://user-images.githubusercontent.com/19163156/175501826-663a2e98-6398-4894-96c1-14e352a2c216.png)

### What is expected?
正常运行

### What is actually happening?
报错，且页面挂掉

### Package
@formily/core@2.1.6

---

createForm 的 designable  模式下，表达式字段是否都有类似问题，不会将 ```{{}}```  转成 function？

**Comment by melodyJie** [comment]
我在 alibaba/designable 项目下也提了相关 issues

https://github.com/alibaba/designable/issues/308

**Comment by XimfengYao** [comment]
关注下 https://github.com/formilyjs/antdv-x3 这个项目

**Comment by melodyJie** [comment]
我简单看了下源码, 有两个疑问：

1. `designable` 模式下不走 `makeObservable` 的逻辑是合理的吗？
源码位置：[makeObservable](https://github.com/alibaba/formily/blob/5c122818573ff914c7b4fe37904fddafa2fad6d3/packages/core/src/models/Field.ts#L139)

如果不走，在 designable 模式下 传给底层组件的 需要对表达式值进行相应转换的 `属性` 全部都是`{{string}}` 结构，这种非法传参的情况不会很不合理吗？

2. 关于 toJS 方法的作用？

相关源码：
- [ReactiveField.tsx#L98](https://github.com/alibaba/formily/blob/fac7b670abd383bd07e9453a3a44af36f7ce97ae/packages/react/src/components/ReactiveField.tsx#L98)
- [toJS](https://github.com/alibaba/formily/blob/fac7b670abd383bd07e9453a3a44af36f7ce97ae/packages/reactive/src/externals.ts#L85)

一开始误以为改方法是将 表达式字符串 转换成 js 对象的， 结果发现根本不是，看半天也没理解该方法的作用是什么？

麻烦大佬们有空的话解答下

**Comment by janryWang** [comment]
designable模式，表达式是不会执行的，因为缺少上下文，NumberPicker这个问题，建议在搭建态渲染用Input组件mock一下就行了，搭建态的定位是原型搭建，不是运行时搭建

**Comment by melodyJie** [comment]
本地临时解决方案

> designable模式，表达式是不会执行的，因为缺少上下文，NumberPicker这个问题，建议在搭建态渲染用Input组件mock一下就行了，搭建态的定位是原型搭建，不是运行时搭建

我再 designable 仓库提了改动代码，麻烦大佬看看是否合理。我本地可以解决报错问题

**Comment by yiyunwan** [comment]
> designable模式，表达式是不会执行的，因为缺少上下文，NumberPicker这个问题，建议在搭建态渲染用Input组件mock一下就行了，搭建态的定位是原型搭建，不是运行时搭建
我选择的是搭建态组件写个HOC把{{}}的props置为空
