### ISSUE TITLE
[Bug Report] toArr 方法当值是 0 时会被转为空数组

### ISSUE THREAD

**Issue by mytharcher** [alibaba/uform#3235]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-babbage-kh6xh3?file=/index.tsx)

### Steps to reproduce
~~~
import { toArr } from '@formily/shared';

console.log(toArr(0)); // []
~~~

### What is expected?
~~~
console.log(toArr(0)); // [0]
~~~

### What is actually happening?
~~~
console.log(toArr(0)); // []
~~~

### Package
@formily/shared@2.1.7

---

https://github.com/alibaba/formily/blob/formily_next/packages/shared/src/array.ts#L34

~~~
export const toArr = (val: any): any[] => (isArr(val) ? val : val ? [val] : [])
~~~

方法中的 `val ? [val] : []` 条件表达式有逻辑错误，`0` 会导致 `false` 结果得到空数组，如果要判断 null 应该用 `val == null`，如果要判断 undefined 应该用 `typeof val === 'undefined'`。

**Comment by janryWang** [comment]
私有方法，toArr目前的行为就是特意这样的
