### ISSUE TITLE
[Bug Report] TimePicker组件在range模式下，无法正常工作

### ISSUE THREAD

**Issue by wweggplant** [alibaba/uform#3238]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tmmm85?file=/src/App.vue)

### Steps to reproduce
https://element.formilyjs.org/guide/time-picker.html#markup-schema-%E6%A1%88%E4%BE%8B  在Chrome浏览器中，官网提供的案例，弹出picker后，无法选取时间

### What is expected?
可以正常选取时间

### What is actually happening?
无法选择时间且点击确定后，ui上值为空

### Package
@formily/element@2.1.9

---

**Comment by janryWang** [comment]
duplicate https://github.com/alibaba/formily/issues/3241
