### ISSUE TITLE
[Bug Report] 关于  lowcode-engine  跟 formily 表单结合出现的一个问题

### ISSUE THREAD

**Issue by twinkle77** [alibaba/uform#3248]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/proud-wood-j71knz?file=/App.tsx:91-104)

### Steps to reproduce
伪代码结构如下：

```typescript
export default () => {
  return (
    <Page>
      <FormilyComp />
      <Button></Button>
    </Page>
  );
};
```

* Page 组件为 lowcode-engine 顶层 class 组件
* FormilyComp 组件为用户拖拽进画布的 formily 容器
* FormilyComp 的 schema 依赖 Page 组件的 state，如 ` enum: {{ $page.state.list }}`
* 点击按钮调用 `this.setState({ list: [{label: 1, value: 1}, { label: 2, value: 2 }]})`
* react 整颗树会重渲染，但无法触发 formilyForm 的 select 组件更新
* 查看 formily 源码，原因是 formily 对 field 实例进行复用

尝试通过 clearFormGraph  去解决

```typescript
  useEffect(() => {
     normalForm.clearFormGraph()
  }, [$page.state])
```

但这种方式会导致 field 重新实例化，又重新 mount 了，如果 field 实例  mount 的时候，有调用 $page.setState 场景的话，会触发无限循环（在线源码链接可复现）

### What is expected?
1. 解决 filed 的 enum 更新的问题（enum 依赖 $page.state.xxx）
2. 不会触发无限渲染

### What is actually happening?
现在出现的情况是：
1. Page 组件调用了 setState，但 formily select 组件不会更新

### Package
@formily/core@2.1.9

---

在线链接： https://codesandbox.io/s/proud-wood-j71knz?file=/App.tsx

**Comment by janryWang** [comment]
挪到discussion里去讨论吧

**Comment by twinkle77** [comment]
> 挪到discussion里去讨论吧

已跟进 https://github.com/alibaba/formily/discussions/3249
感谢大佬 @janryWang
