### ISSUE TITLE
[Feature Request] 表单设计器，fied schema扩展无法拿到扩展字段值

### ISSUE THREAD

**Issue by laosandegudai** [alibaba/uform#3254]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义组件，在designerProps 中，将扩展属性添加到   'field-group' 中，设计器可以正常显示，但是在自定义组件的connect中无法拿到该值
![image](https://user-images.githubusercontent.com/17979159/177357144-2ac0be2a-a49d-4d57-8577-9dde02941d8c.png)

![image](https://user-images.githubusercontent.com/17979159/177356910-a8d1fb28-57bc-42f3-b197-cd7dcde33d76.png)

### What does the proposed API look like?
希望自定义组件，可以扩展字段属性头传到组件,目前通过组件属性可以拿到值。

**Comment by janryWang** [comment]
useTreeNode拿node节点属性

**Comment by laosandegudai** [comment]
> useTreeNode拿node节点属性

使用 useFieldSchema 可拿到，但是我看到有data扩展属性，就是不知道怎么用在settingform,
自定义组件，我这样定义的schema
![image](https://user-images.githubusercontent.com/17979159/178400373-dbe3d99f-cf44-4321-b854-6d108e4fc76a.png)
![image](https://user-images.githubusercontent.com/17979159/178400618-f63c4f2f-85ea-4455-8dbc-101700844ad4.png)
这样拿不到data，目前用 useFieldSchema 可以获取到。
