### ISSUE TITLE
[Bug Report] Changes in object field values has no affect in x-reactions

### ISSUE THREAD

**Issue by ccpu** [alibaba/uform#3269]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x-reactions-object-field-issue-x54zsj)

### Steps to reproduce
open console
type in 'BB' field

### What is expected?
`x-reactions` must react when the object field value changes.

### What is actually happening?
A `x-reaction` triggers once when a field mounts, but it won't trigger when object field value is changed by its children.

### Package
@formily/reactive@2.1.10

---

The object field value shouldn't be treated any differently than primitive types value, since both are `DataFields`, so `x-reactions` should be triggered when the object field value changes. Maybe I'm missing something?

**Comment by janryWang** [comment]
Array references don't change when elements are added, so you need to keep track of deep data precisely, you can use JSON.stringify like this:
```
console.log('Array Field Value =',JSON.stringify($self.value))}}`,
```

**Comment by ccpu** [comment]
Sorry, I hadn't saved the code sandbox, so you may have seen the array field, but the problem is with the object, please look at the sand box again and give me some feedback.

**Comment by janryWang** [comment]
I understand no problem. Similarly, when the value of the input changes, the object reference will not change. @formily/reactive is not immutable.

**Comment by ccpu** [comment]
I understand now.
Many thanks.
