### ISSUE TITLE
[Bug Report] target模式下，fulfill.run无法使用$effect

### ISSUE THREAD

**Issue by atom-yang** [alibaba/uform#3271]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/late-frost-4vcpr1?file=/App.tsx)

### Steps to reproduce
```
      "x-reactions": {
        target: "firstName",
        fulfill: {
          schema: {
            "x-component-props": {
              prefix: "123123"
            }
          },
          run: `$effect(()=>{
            console.log('run');
          }, [])`
        }
      }
```
联动target模式下，使用fulfill run的情况下，无法使用$effect函数，告警
`autorun.effect must used in autorun function body.`

### What is expected?
正常运行`fulfill.run`

### What is actually happening?
告警`autorun.effect must used in autorun function body.`

### Package
@formily/json-schema@2.1.10

---

**Comment by atom-yang** [comment]
相关PR: #2560 @janryWang

**Comment by janryWang** [comment]
不支持

**Comment by atom-yang** [comment]
> 不支持

target模式下，具体哪些不支持呢

**Comment by janryWang** [comment]
不支持写相对路径，不支持$effect这些函数，这些都是被动模式才支持的
