### ISSUE TITLE
[Feature Request] 希望FormItem可以支持getValueFromEvent之类的功能

### ISSUE THREAD

**Issue by 314857493** [alibaba/uform#3272]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用于将组件的value根据自己的需求来进行操作

### What does the proposed API look like?
同antd中FormItem的getValueFromEvent

**Comment by janryWang** [comment]
connect的时候自己写个mapProps函数做映射
