### ISSUE TITLE
[Bug Report] element-plus style file spelling mistake

### ISSUE THREAD

**Issue by liuzuwei-go** [alibaba/uform#3274]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-antd-vue-pure-jsx-pp3gvv)

### Steps to reproduce
@formily/element-plus/esm/form-collapse/style.js

### What is expected?
replace import 'element-plus/theme-chalk/src/bdage.scss';  to  import 'element-plus/theme-chalk/src/badge.scss';

### What is actually happening?
build error

### Package
@formily/element-plus@2.1.10

---

**Comment by yiyunwan** [comment]
可以提pr的

**Comment by yiyunwan** [comment]
1.0.0-beta.6 已修复
