### ISSUE TITLE
Value sync display issue when multiple SchemaForm in the same page

### ISSUE THREAD

**Issue by johnnylc** [alibaba/uform#328]
当页面中有两个SchemaForm表单的时候，两者共用一个state数据源，通过其中一个表单多次更改数据（submit，reset）时，两表单数值存在更新不同步问题。

应用场景如下：
![image](https://user-images.githubusercontent.com/12717523/65599830-504ea100-dfd1-11e9-813e-3e8037d8e102.png)

问题的最简demo：
https://codesandbox.io/s/wispy-water-nzqkn

操作步骤：多次修改表单数值并submit或者reset

**Comment by janryWang** [comment]
value={{...data}}这样使用先临时解决问题，因为是相同引用，内部脏检查判断异常，这个问题先记着，后面解决
