### ISSUE TITLE
[Bug Report] 不兼容React18版本的ReactDOM.createRoot(HTMLElement).render语法

### ISSUE THREAD

**Issue by MaxWang17** [alibaba/uform#3282]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/falling-pine-gzedn2?file=/index.tsx)

### Steps to reproduce
使用React18版本的ReactDOM.createRoot(HTMLElement).render语法，初始值和表单校验都会出现明显问题：Field设置initialValue属性时无法响应输入；默认的表单校验逻辑错误，输入时就会标红。

以上是已知问题。预计仍有一些类似问题。

打开复现链接，即可复现。如若直接换成17版本的ReactDOM.render，会发现恢复正常。

### What is expected?
兼容React18版本的ReactDOM.createRoot(HTMLElement).render语法。

### What is actually happening?
不兼容React18版本的ReactDOM.createRoot(HTMLElement).render语法。

### Package
@formily/react@2.1.10

---

我自己新建CRA跑demo的时候，出现了18版本新语法不兼容问题。比较崩溃的一点是，当时场景已经简单到无法再简单，效果却依然不对（且不知道为啥），这相当打击学习信心，希望可以尽快修复。

**Comment by janryWang** [comment]
先把StrictMode干掉吧
