### ISSUE TITLE
[Bug Report] InputNumber组件输入0后，切换成阅读状态，不显示0

### ISSUE THREAD

**Issue by liuzuwei-go** [alibaba/uform#3285]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-react-antd-pure-jsx-omncis)

### Steps to reproduce
1. InputNumber 组件输入0 
2. 切换为阅读状态

### What is expected?
在阅读状态显示 0

### What is actually happening?
不显示

### Package
@formily/element-plus@2.1.10

---

**Comment by yiyunwan** [comment]
提供下准确的sodesanbox吧，以及准确的包版本
