### ISSUE TITLE
[Bug Report] yarn test 大量报错，无法通过

### ISSUE THREAD

**Issue by faner11** [alibaba/uform#3297]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-react-antd-pure-jsx-omncis)

### Steps to reproduce
yarn test

### What is expected?
yarn test 正常

### What is actually happening?
全是报错

### Package
@formily/react@2.1.11

---

可能是之前的代码提交又问题，现在无法正常运行yarn test

**Comment by janryWang** [comment]
不会的吧，每次提交ci都是跑通的，你应该先yarn install然后yarn build
