### ISSUE TITLE
场景案例文档 bug

### ISSUE THREAD

**Issue by dreamkidd** [alibaba/uform#33]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

https://alibaba.github.io/uform/#/YZCyCk/7lC3CXsVhB

antd 简单场景中的年份选择框，点击选项无响应，貌似是因为 antd 中没有该类型

3.  [Bug Report Template](https://2plkr5ox6y.codesandbox.io/)

修改为 month 即可
```
 <Field type="month" title="年份" name="year" />
```

**Comment by janryWang** [comment]
请看该issue，应该是antd的问题 https://github.com/ant-design/ant-design/issues/16436

**Comment by janryWang** [comment]
目前antd的作者已经回复，这个是一个已知问题，后续会新增YearPicker组件，建议先用Select实现年选择的功能
