### ISSUE TITLE
[Bug Report] setComponentProps

### ISSUE THREAD

**Issue by LiGuan-007** [alibaba/uform#3304]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com)

### Steps to reproduce
      <ArrayField name='array'>
        {(fields) =>
          fields.value.map((field, i) => (
            <ObjectField name={i} component={[Xxx]}></ObjectField>
          ))
        }
      </ArrayField>

### What is expected?
query('xxx').take().setComponentProps({})

query去设置ArrayField最后一个field的componentProps时，只改变最后一个field的componentProps

### What is actually happening?
query去设置ArrayField最后一个field的componentProps时，会把前面的field的component的props改变

### Package
@formily/core@2.0.11

---

**Comment by janryWang** [comment]
codesanndbox地址呢
