### ISSUE TITLE
[Bug Report] form.query('xxx').value()取不到没有Field节点的值

### ISSUE THREAD

**Issue by lxzy-yun** [alibaba/uform#3307]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-williams-7tmjgm?file=/App.tsx)

### Steps to reproduce
form.query('xxx').value()取不到没有Field节点的值

### What is expected?
文档上我看是不依赖Field节点的，之前的测试版也是能取到的，到了正式版就不行了

### What is actually happening?
form.query('xxx').value()取不到没有Field节点的值

### Package
@formily/core@2.1.11

---

**Comment by janryWang** [comment]
这个是查询Field的API
