### ISSUE TITLE
第一次异步加载feild的enum出现空值

### ISSUE THREAD

**Issue by czbczb** [alibaba/uform#331]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:
第一次异步加载feild的enum设置后仍然是空，
![image](https://user-images.githubusercontent.com/23630100/65827905-c4d25a00-e2c7-11e9-9ca4-0b7a8b8d054f.png)

但是初始化时设置固定值是正常的，
![image](https://user-images.githubusercontent.com/23630100/65827921-e6334600-e2c7-11e9-822b-af999f8fac40.png)

               ```
 $('onFormInit').subscribe(() => {
                    hide('id');
// 异步加载
                    onLoadAssociateOriginData();
// 设置固定值可以
                    setEnum('IDCid', [
                        {label: "DZM", value: "1"},
                        {label: "JXQ", value: "2"},
                        {label: "YJ", value: "3"},
                        {label: "THQ", value: "4"},
                        {label: "SH", value: "6"},
                        {label: "FS", value: "7"},
                        {label: "GFR", value: "8"}
                    ]);
                })
```

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by czbczb** [comment]
please help me

**Comment by janryWang** [comment]
麻烦给个可复现的codesandbox链接

**Comment by czbczb** [comment]
![image](https://user-images.githubusercontent.com/23630100/65829904-e25dee80-e2dc-11e9-856d-4f922d9d4850.png)
我找到什么原因，value设置不能放到enum的前面或者不写，都会 导致这个原因，
根本原因有待研究

**Comment by fanxiaokun** [comment]
@czbczb 请教一下，这个问题，你是在setEnum后加上这个setValue('field_name',null)就解决了么？

**Comment by czbczb** [comment]
@fanxiaokun 我也没有搞明白，有更好的方法么？
