### ISSUE TITLE
[Bug Report] ArrayCards 等组件 x-component 非字符串时报错

### ISSUE THREAD

**Issue by Grapedge** [alibaba/uform#3318]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/morning-pine-t3dsic)

### Steps to reproduce
点击 `添加条目`

### What is expected?
正常添加新条目

### What is actually happening?
抛出错误：_a.indexOf is not a function

### Package
@formily/next@2.1.12

---

原因：ArrayCards 等组件没有处理内联组件的场景：

```tsx
const isIndexComponent = (schema: ISchema) => {
  return schema['x-component']?.indexOf('Index') > -1
}
```

**Comment by janryWang** [comment]
welcome pr
