### ISSUE TITLE
请问能把Field的type统一成返回的数据类型，而x-component统一成展示UI组件吗？

### ISSUE THREAD

**Issue by effapp** [alibaba/uform#332]
1. How would you tag this issue?

  - Enhancement
  - Performance

2. Describe your issue:
1）、Field组件有两个属性，type和x-component，在使用的时候有些困扰，比如checkbox，<Field type="checkbox" enum={['1', '2', '3', '4']} required title="Checkbox" name="checkbox" />，这里的type是checkbox，能不能把type统一成field返回的值类型，而x-component统一成展现的组件，这样的话，checkbox即可以返回string，也可以返回number；

2）、比如type=“string”时，可以有多种展现UI形式：
<Field  type="string" x-component="textarea"  ...props  />
<Field  type="string" x-component="select"  ...props   />
<Field  type="string" x-component="checkbox"  ...props   />
<Field  type="string" x-component="radio"  ...props   />
...

**Comment by effapp** [comment]
现在的Field组件使用起来有些不方便，也不太容易理解和记忆，type一会儿是string、number等数据类型，一会儿又是checkbox、textarea等UI组件名称。

**Comment by janryWang** [comment]
标准形式<Field type="这是数据类型" x-component="这是UI组件"/>，你自己按照这样来写是没问题的
