### ISSUE TITLE
[Bug Report] ArrayTable remove其中一项之后，调用form.reset 之后初始值不正常

### ISSUE THREAD

**Issue by ytftianwen** [alibaba/uform#3322]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/snowy-frost-tucn7f?file=/App.tsx)

### Steps to reproduce
1. 进入codesanbox链接
2. 点击删除table中的其中一项
3. 点击reset

### What is expected?
被删掉的那项初始值正确显示

### What is actually happening?
 如图：被删掉的那项初始值不正确
![image](https://user-images.githubusercontent.com/13484089/184057611-6e5f6636-3de3-4b86-b9b1-7dc9ee22236c.png)

### Package
@formily/antd@2.1.12

---

**Comment by janryWang** [comment]
initialValues只能保证第一次初始值是生效的，删除一行之后initialValues是会跟随字段模型一并清空的，如果你希望每次都有默认值效果，最好是在每个字段上加default属性

**Comment by ytftianwen** [comment]
> @janryWang 
ArrayTable的default，在reset时也是相同的问题呢
![image](https://user-images.githubusercontent.com/13484089/184060730-409e72a2-94e3-4c5b-a957-afb45cc3306f.png)

**Comment by ytftianwen** [comment]
试了下调用form.setValues({...})可以达到预期效果

**Comment by janryWang** [comment]
的确有点问题，我修复一下
