### ISSUE TITLE
怎样自定义Field组件，能从远程服务器加载数据

### ISSUE THREAD

**Issue by effapp** [alibaba/uform#333]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:

 请问，怎样实现一个能够远程加载数据的自定义Field组件，如下拉框的下拉选项只有在下拉的时候才从服务器加载数据。

**Comment by janryWang** [comment]
自定义组件自己管理状态，想怎么写就怎么写，这种问题不要再问了，建议你好好学下React开发再问
