### ISSUE TITLE
[Bug Report] fusion next的ArrayField下，动态新增的使用input和select作为component的Field无法输入

### ISSUE THREAD

**Issue by HengzheLi** [alibaba/uform#3334]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boring-bash-nud4zy?file=/App.tsx)

### Steps to reproduce
https://codesandbox.io/s/boring-bash-nud4zy?file=/App.tsx

1. 点击新增参数
2. 在新出现的输入框中做任何输入

输入框没有任何内容

同时：https://formilyjs.org/guide/issue-helper (英文版)中，版本输入框不接受手动输入，但是下拉框中也没有可选择的选项

### What is expected?
输入啥显示啥

### What is actually happening?
输入框空空如也

### Package
@formily/next@2.2.0

---

**Comment by janryWang** [comment]
https://codesandbox.io/s/funny-meninsky-cz6jvd
