### ISSUE TITLE
[Bug Report] switch component can not work effectively in @formily/semi

### ISSUE THREAD

**Issue by zhaolingqi** [alibaba/uform#3339]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yeu3my?file=/package.json)

### Steps to reproduce
在formily/semi中使用switch组件

### What is expected?
点击整个switch均可生效

### What is actually happening?
点击switch的右半部分没有失效，只有点击左半部分会生效。

### Package
@formily/semi@1.0.3

---

**Comment by prgrmrwy** [comment]
用户混用了 formily/antd 和 formily/semi，出现样式覆盖，已解决
