### ISSUE TITLE
表单国际化

### ISSUE THREAD

**Issue by czbczb** [alibaba/uform#334]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  表单国际化LocaleProvider 组件已经弃用，使用会报错，希望更新一下

**Comment by czbczb** [comment]
如果用antd最新的组件ConfigProvider的情况下uform表单国际化不起作用

**Comment by janryWang** [comment]
目前Uform内部并没有依赖LocaleProvider
