### ISSUE TITLE
[Bug Report] @formily/element 不支持vue2.7，提示“Can't resolve '@vue/composition-api' in ”

### ISSUE THREAD

**Issue by iceycc** [alibaba/uform#3342]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily/blob/formily_next/packages/element/package.json)

### Steps to reproduce
项目用了安装后提示Module not found: Error: Can't resolve '@vue/composition-api' in '/xx/WebstormProjects/template/pebble-design-pro-preview/src'
 @ ./src/main.js 47:6-23 8:0-17

### What is expected?
"@formily/core": "^2.2.0",
    "@formily/element": "^2.2.0",
    "@formily/vue": "^2.2.0",
    "vue": "^2.7.8",

### What is actually happening?
项目安装到vue2.7 提示需要安装@vue/composition-api'

### Package
@formily/element@2.2.0

---

**Comment by MisicDemone** [comment]
https://github.com/alibaba/formily/blob/formily_next/packages/element/src/__builtins__/shared/resolve-component.ts#L2

@formily/element中的所有 composition-api 应该从'vue-demi'引入

**Comment by GpingFeng** [comment]
我现在 vue 版本是 2.7.8，但我发现 Form Provider 的 setUp 在组件渲染的时候没有执行，请问这个可能的原因是？

<img width="1877" alt="image" src="https://github.com/alibaba/formily/assets/20135760/e7060ec3-3511-41e1-aaab-2779b45de5de">

<img width="2249" alt="image" src="https://github.com/alibaba/formily/assets/20135760/00ab791e-d25c-4e5f-835d-e84032dfd37f">
