### ISSUE TITLE
[Bug Report] @formily/element-plus组件库 评分器，滑动条，树选择，网格布局 在设计器中报错

### ISSUE THREAD

**Issue by yjh30** [alibaba/uform#3347]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/qq1037305420/element-plus)

### Steps to reproduce
克隆https://github.com/qq1037305420/element-plus，启动本地serve，拖拽评分器，滑动条，树选择，网格布局 在设计器中报错，拖到element-plus设计器工作区以后，然后点击工作区其他区域，js报错，然后就不能再拖组件了

### What is expected?
期望 正常

### What is actually happening?
js报错，element-plus设计器不能用了

### Package
@formily/element-plus@1.0.0

---

**Comment by qq1037305420** [comment]
已经修复了 关了吧
如果还有其他issue直接提到对应的repo就行了。
打开了issues了，没想到fork的repo必须手动打开才行
@yjh30
