### ISSUE TITLE
[Feature Request] 是针对vant 的动态表单的解决方案么

### ISSUE THREAD

**Issue by chenxiangjun2010** [alibaba/uform#3351]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
是针对vant 的动态表单的解决方案么

### What does the proposed API look like?
是针对vant 的动态表单的解决方案么

**Comment by janryWang** [comment]
这是通用的动态表单方案，不局限某个组件库
