### ISSUE TITLE
[Bug Report] vue 版本正式环境 SchemaField加载不出来

### ISSUE THREAD

**Issue by uuai** [alibaba/uform#3359]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6upcz8?file=/src/App.vue)

### Steps to reproduce
直接复制文档代码 本地可以运行，线上环境加载不出iform

### What is expected?
线上环境可以加载出form

### What is actually happening?
线上环境加载不出iform

### Package
formily-antdv@2.2.1

---

**Comment by zhouxinyong** [comment]
跟vue的版本有关系，固定vue在2.7以下就没问题，2.7最新版本我这边在改@formily/antdv，到时候发个新版本
