### ISSUE TITLE
FormLayout的labelTextAlign不生效

### ISSUE THREAD

**Issue by wangmingxu** [alibaba/uform#337]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - What is the current behavior?
设置了labelTextAlign=left不生效
  - What is the expected behavior?
可以正常生效
  - Which versions of UForm?
@uform/antd 0.4.3

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.https://codesandbox.io/s/adoring-bose-vfv7j

**Comment by janryWang** [comment]
antd的Form也不支持labelTextAlign，所以，@uform/antd这个包也没法支持了
