### ISSUE TITLE
[Bug Report] >= 2.2.2 在 ArrayArrayBase Context 外部使用 ArrayBase.useRecord() 报错

### ISSUE THREAD

**Issue by charlzyx** [alibaba/uform#3377]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-lovelace-o81fk8?file=/App.tsx)

### Steps to reproduce
在 Array Context 之外使用 ArrayBase.useRecord() 即可复现

例如: 自定义组件:

```tsx
const BugDemo = () => {
  // 这里会报错
  const array = ArrayBase?.useRecord?.();
  return <div>DEMO</div>;
};

```

### What is expected?
需求是有一些组件根据是否是在 ArrayBase context 中来判断是取那个字段, 结合 
![image](https://user-images.githubusercontent.com/18055018/188865721-fc3a674f-b995-414a-bbbc-0e9383c793ed.png)

https://github.com/alibaba/formily/blob/formily_next/packages/antd/src/array-base/index.tsx#L94

这里 takeRecord 的时候 ctx.record 根据 ctx 是否存在做了三目运算符判断, 但 ctx.index 没有做这样的判断

在 <= 2.2.1 的版本, 因为没用到 ctx.index, 所以没有这个问题

### What is actually happening?

TypeError: Cannot read properties of null (reading 'index')

### Package
@formily/antd@2.2.2

---

**Comment by janryWang** [comment]
来个PR吧
