### ISSUE TITLE
[Bug Report] enum label 无法动态更新

### ISSUE THREAD

**Issue by fanmingfei** [alibaba/uform#3378]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-aryabhata-iy9rz0?file=/App.tsx)

### Steps to reproduce
点击 update Select 按钮，可以看到label是变了，但是select的option没有变

### What is expected?
select 的option 也跟着变

### What is actually happening?
.

### Package
@formily/reactive-react@2.2.3

---

我想通过修改label来修改Select列表里面的value

**Comment by janryWang** [comment]
enum是shallow属性，建议改成form.query("xxx").take().dataSource = xxx
