### ISSUE TITLE
[Bug Report] @formily/element-plus 缺少 Password 组件

### ISSUE THREAD

**Issue by zongzhenhua** [alibaba/uform#3386]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-vue-ant-design-vue-json-schema-25g4z1)

### Steps to reproduce
https://codesandbox.io/s/formily-vue-ant-design-vue-json-schema-25g4z1

### What is expected?
能正常引入Password 组件

### What is actually happening?
引入 Password 组件不存在

### Package
@formily/element-plus

---

**Comment by Eatwhiterabbit** [comment]
x-component-props指定一下type: 'password'就可以了吧

**Comment by yiyunwan** [comment]
先指定x-component-props指定一下type: 'password'使用，后续发版添加组件

**Comment by zongzhenhua** [comment]
谢谢



在 2022-09-20 11:05:44，"yiyunwan" ***@***.***> 写道：

先指定x-component-props指定一下type: 'password'使用，后续发版添加组件
