### ISSUE TITLE
[Bug Report] field.validate expect return Promise type  but it return any

### ISSUE THREAD

**Issue by summer789** [alibaba/uform#3391]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily/blob/5acb7e1abf745e9b81c9612c1eae329ff8321432/packages/core/src/models/Field.ts#L494)

### Steps to reproduce
![](https://i.postimg.cc/BZkJfbtb/screenshot-20220913-171436.png)

### What is expected?
return Promise 

### What is actually happening?
return any

### Package
@formily/core@2.2.4

---

**Comment by janryWang** [comment]
看了下，类型是能正确推导的，我猜测是你的ts版本或者配置的问题
