### ISSUE TITLE
@babel/runtime

### ISSUE THREAD

**Issue by lingxufeng2014** [alibaba/uform#34]
dependency 里面缺少了 @babel/runtime 依赖，单独引入会报错。
- 给的实例中因为是跟 antd 一起用的，而 antd 自带了 @babel/runtime ，没报错。
- 我们的场景，antd 是 umd 引入的……
-------------
麻烦一并修复一下呗，感谢~~~
后续有问题，我尽量提 pr。

**Comment by janryWang** [comment]
目前在v0.1.10版本中已经将@babel/runtime加入了peerDependencies，您需要自行安装
