### ISSUE TITLE
SchemaForm使用时报错复用了React的Event

### ISSUE THREAD

**Issue by beihaifeiwu** [alibaba/uform#340]
1. How would you tag this issue?
  - Tip

2. Describe your issue:
SchemaForm使用时报如下错误，复用了React的Event

![image](https://user-images.githubusercontent.com/5372382/66907145-7220ce00-f03b-11e9-9caa-82f7769a9cb1.png)

**Comment by janryWang** [comment]
麻烦给个codesandbox

**Comment by beihaifeiwu** [comment]
不好意思，是这边弄错了
