### ISSUE TITLE
[Bug Report] ArrayTable设置disabled:true之后addition没有隐藏

### ISSUE THREAD

**Issue by XcGuaN-miepia** [alibaba/uform#3403]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-elion-hsqszi?file=/src/App.vue)

### Steps to reproduce
点击按钮后设置disabled为true

### What is expected?
addition组件没有隐藏消失

### What is actually happening?
addition组件在disabled下也消失

### Package
@formily/antdv-x3@2.2.4

---

直接设置addtion "x-pattarn": "disabled" 也不生效

**Comment by charlzyx** [comment]
emm, 因为 `pattarn: disabled` 是不会隐藏的, 我个人理解的话, 应该是设计如此

- antdv 中的实现

[antdv-x3/blob/main/packages/components/src/array-base/index.ts#L237-L242](https://github.com/formilyjs/antdv-x3/blob/main/packages/components/src/array-base/index.ts#L237-L242)
![image](https://user-images.githubusercontent.com/18055018/191653332-75fe2634-6d77-4247-98ad-1e1798f2c8d5.png)

- antd 中也是一样

[packages/antd/src/array-base/index.tsx#L171-L176](https://github.com/alibaba/formily/blob/formily_next/packages/antd/src/array-base/index.tsx#L171-L176)
![image](https://user-images.githubusercontent.com/18055018/191653365-b0a958e5-426a-4571-9e56-52b5e0333c07.png)

需要给 ArrayTable 的 pattarn 设置为 `readPretty` | `readOnly` 解决;

参考:
- [formily/core.fieldpatterntypes](https://core.formilyjs.org/zh-CN/api/models/field#fieldpatterntypes)

**Comment by XcGuaN-miepia** [comment]
> emm, 因为 `pattarn: disabled` 是不会隐藏的, 我个人理解的话, 应该是设计如此
> 
> * antdv 中的实现
> 
> [antdv-x3/blob/main/packages/components/src/array-base/index.ts#L237-L242](https://github.com/formilyjs/antdv-x3/blob/main/packages/components/src/array-base/index.ts#L237-L242) ![image](https://user-images.githubusercontent.com/18055018/191653332-75fe2634-6d77-4247-98ad-1e1798f2c8d5.png)
> 
> * antd 中也是一样
> 
> [packages/antd/src/array-base/index.tsx#L171-L176](https://github.com/alibaba/formily/blob/formily_next/packages/antd/src/array-base/index.tsx#L171-L176) ![image](https://user-images.githubusercontent.com/18055018/191653365-b0a958e5-426a-4571-9e56-52b5e0333c07.png)
> 
> 需要给 ArrayTable 的 pattarn 设置为 `readPretty` | `readOnly` 解决;
> 
> 参考:
> 
> * [formily/core.fieldpatterntypes](https://core.formilyjs.org/zh-CN/api/models/field#fieldpatterntypes)

设置readOnly和disabled场景不一样，有些样式展示是不同的，antd的disabled是禁止点击，element-plus的是隐藏，antdv对于这个按钮没有控制，在disabled场景下还能新增行，之后会考虑试试单独给addition加上readOnly而不是disabled来控制

**Comment by frehaiku** [comment]
在 disabled 状态下默认行为是不会隐藏，如需隐藏多加一个 `x-visible` 控制
