### ISSUE TITLE
[Bug Report] 使用getFieldState遍历表单field后，数组删除操作很卡顿

### ISSUE THREAD

**Issue by Jiazhi-Wong** [alibaba/uform#3404]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shu-zu-xing-neng-wen-ti-1ryul8?file=/App.tsx)

### Steps to reproduce
- 打开demo，删除城市列表的第一项

### What is expected?
- 操作不会卡顿
- 如果注释掉 `form.getFieldState(path);` 这一行，就不会卡顿，但实际场景中需要访问 field 上的显示状态

### What is actually happening?
- 操作非常卡顿，js需要执行十几秒

### Package
@formily/core@2.2.4

---

**Comment by janryWang** [comment]
删除是会触发列表组件整体渲染的，推荐改成ArrayTable，分页模式
