### ISSUE TITLE
[Bug Report] @formify/element-plus with vite-plugin-imp failed in Nuxt3

### ISSUE THREAD

**Issue by NexZhu** [alibaba/uform#3414]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/daotl/nuxt-starter/tree/formily)

### Steps to reproduce
```sh
git clone -b formily https://github.com/daotl/nuxt-starter.git
cd nuxt-starter
npm install
npm run dev
```

`npm run dev` in `main` branch without `Formily` works, open `http://localhost:3000` in the browser

`npm run dev` and open `http://localhost:3000` in the browser, 500 error

### What is expected?
I'm following this guid to use Formily with Element Plus + Nuxt3 + Vite
https://element-plus.formilyjs.org/guide/#%E6%8C%89%E9%9C%80%E6%89%93%E5%8C%85

Expected to work.

### What is actually happening?
I just modified `nuxt.config.ts`, I haven't use the `Form` component in `.vue` file yet, but Nuxt already failed to startup.

nuxt.config.ts (related part):
```ts
export default defineNuxtConfig({
  ...
  vite: {
    plugins: [
      vitePluginImp({
        libList: [
          {
            libName: '@formily/element-plus',
            libDirectory: 'esm',
            style(name): string {
              return `@formily/element-plus/esm/${name}/style.js`
            },
          },
        ],
      }),
    ],
  ...
}
```

**npm run dev** error, then go to `http://localhost:3000/`, error log in the console:
```
 ERROR  Unexpected token, expected "}" (5:7)
```

Error log in the page:
```
[vite-node] [plugin:vite-plugin-imp] [UnexpectedToken] /app.vue:5:7

3  |  
4  |  useHead({
5  |    title: 'Vitesse Nuxt 3',
   |         ^
6  |    link: [
7  |      {
```

### Package
@formily/element-plus@2.2.9

---

Node version v18.9.0

**Comment by NexZhu** [comment]
@wukd @yiyunwan I really need help for this, could you please take a look? 🙏

**Comment by yiyunwan** [comment]
拉代码看好像已经解决了？
解决了的话可以分享下，然后就关issue了

**Comment by NexZhu** [comment]
@yiyunwan 没有解决，还是一样的问题

**Comment by yiyunwan** [comment]
@NexZhu 可以把有问题的代码提个分支嘛，我这边看看

**Comment by NexZhu** [comment]
就是`formily`分支
```sh
git clone -b formily https://github.com/daotl/nuxt-starter.git
```

**Comment by yiyunwan** [comment]
@daotl/** 貌似是内部源，无法下载

**Comment by NexZhu** [comment]
@yiyunwan 抱歉可能有的包发布错registry了，能看倒是哪个包没下下来吗

**Comment by yiyunwan** [comment]
@NexZhu "@daotl/unplugin-vue-components" nuxt3目前也不稳定，目前看可能是vite-plugin-imp 跟nuxt 3的兼容性问题，暂时先导入所有样式文件吧 import '@formily/element-plus/esm/style'
只是为了体验暂时没必要为了包大小纠结

**Comment by NexZhu** [comment]
@yiyunwan 依赖改过来了，有空请帮忙看看是哪里冲突，我先试试导入所有，谢谢。
