### ISSUE TITLE
[Feature Request] @formily/react 兼容  react-native

### ISSUE THREAD

**Issue by StarHosea** [alibaba/uform#3419]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
@formily/react 中使用了 react-dom ，不兼容 react-native

### What does the proposed API look like?
将 @formily/react 拆分为` @formily/react` , `@formily/react-web`, 前者完全兼容 react-native

**Comment by janryWang** [comment]
不要用markup写法

**Comment by StarHosea** [comment]
不太明白， json-schema 写法一样依赖 `@formily/react` 包。 我看包里面有一行，import 了 `react-dom`， 导致 react-native 运行报错，这个文件单独拿出去，就可以在  react-native 里使用了，测试了 markup, json schema 写法都没问题
https://github.com/alibaba/formily/blob/formily_next/packages/react/src/shared/render.ts#L2

**Comment by StarHosea** [comment]
请问 markup 在 react-native 是有已知问题吗？

**Comment by janryWang** [comment]
其实也没啥问题，我先open，react-native报错就是这里存在依赖 https://github.com/alibaba/formily/blob/formily_next/packages/react/src/shared/render.ts#L2

**Comment by darkmice** [comment]
webpack做一个alias，rax我就是这么跑起来的
