### ISSUE TITLE
如何获取 Field 中的x-component 的 ref

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/uform#342]
## Help us to manage our issues by answering the following:
```
 <Field
        type="string"
        title="TextArea"
        name="textarea"
        x-component="textarea"
      />
```
 上面的代码 我如何获取到 x-component 的 ref

**Comment by janryWang** [comment]
不支持获取ref，也不推荐获取ref，不过可以描述一下大概的需求场景

**Comment by zhaofinger** [comment]
类似需求，我有个 `TextArea` 需要通过 `ref` 拿到光标位置，然后根据光标位置插入文本。 @janryWang

**Comment by BingBlog** [comment]
+1

**Comment by BingBlog** [comment]
> 类似需求，我有个 `TextArea` 需要通过 `ref` 拿到光标位置，然后根据光标位置插入文本。 @janryWang
@zhaofinger hello，你最后是怎么解决的？

**Comment by nigiwen** [comment]
vue里大把用ref调用函数的场景

**Comment by Atw-Lee** [comment]
👀
