### ISSUE TITLE
表单详情展示时，单选字段展示异常（使用JSX渲染选项）

### ISSUE THREAD

**Issue by beihaifeiwu** [alibaba/uform#343]
1. How would you tag this issue?
  - Bug

2. Describe your issue:
表单详情展示时，单选字段展示异常（使用JSX渲染选项）

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.
https://codesandbox.io/embed/friendly-agnesi-ceyls

**Comment by janryWang** [comment]
与#341 重复了

**Comment by beihaifeiwu** [comment]
请问这个什么时候会发布修复版本呢？
