### ISSUE TITLE
[Feature Request] ant design 5 版本的适配

### ISSUE THREAD

**Issue by lblblong** [alibaba/uform#3435]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ant design 5 马上发布了

### What does the proposed API look like?
适配 ant design 5

**Comment by JLoveI** [comment]
ant design 5发布了 less移除了 现在不兼容，近期计划适配吗

**Comment by chenchengwork** [comment]
期待ant design 5的适配

**Comment by faner11** [comment]
@janryWang antd 5的适配是在现有的antd 包升级还是加个新的antd 5包

**Comment by janryWang** [comment]
> @janryWang antd 5的适配是在现有的antd 包升级还是加个新的antd 5包

后面会把antd迁移到formilyjs里

**Comment by faner11** [comment]
@janryWang 规划好的的话，升级的事情我可以帮忙弄

**Comment by DophinL** [comment]
赞，同求适配

**Comment by wrfighting** [comment]
+1 期待，有个升级计划就好了，这样大家可以一起帮忙

**Comment by yiyunwan** [comment]
后续计划是在这个参股进行开发的 https://github.com/formilyjs/antd
现阶段我已经在 https://github.com/pindjs/antd/tree/feat/antd-v5 完成了一部分迁移了，有兴趣的可以一起开发

**Comment by janryWang** [comment]
> 后续计划是在这个参股进行开发的 https://github.com/formilyjs/antd 现阶段我已经在 https://github.com/pindjs/antd/tree/feat/antd-v5 完成了一部分迁移了，有兴趣的可以一起开发

哈哈，那这个你来跟进吧，大家可以都进来review或者贡献代码

**Comment by omidabd** [comment]
> 后续计划是在这个参股进行开发的 https://github.com/formilyjs/antd 现阶段我已经在 https://github.com/pindjs/antd/tree/feat/antd-v5 完成了一部分迁移了，有兴趣的可以一起开发

How much of the job is done?
Is there any task list that I can incorporate?

**Comment by yiyunwan** [comment]
@Rnb1189 目前大部分工作已经做完了，不过还未详细测试，试用的话可以npm i @formily/antd@3.0.0-alpha.1试用下

**Comment by yiyunwan** [comment]
现在发布了next版本的，下载使用的话可以npm i @formily/antd@next

**Comment by DophinL** [comment]
> 

请问当前是否稳定可用了呢？

**Comment by DophinL** [comment]
> 现在发布了next版本的，下载使用的话可以npm i @formily/antd@next

@yiyunwan 请问现在是否稳定可用了呢？

**Comment by kaoding** [comment]
重新规化下的版本antd 5.0版本使用，下载使用的话可以npm i @formily/antd-v5（ https://github.com/formilyjs/antd ）

**Comment by lgh06** [comment]
#3757 #3752
