### ISSUE TITLE
[Bug Report] ArrayItems 和 initialValues 搭配导致删除后添加依然存在数据

### ISSUE THREAD

**Issue by xinshangshangxin** [alibaba/uform#3450]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-tereshkova-flxrys?file=/App.tsx)

### Steps to reproduce
1. 先删除 4
2. 点击 Add entry

此时 4 重新显示到界面中

### What is expected?
initialValues 不影响删除添加

### What is actually happening?
4 重新显示到界面中

### Package
@formily/antd@2.2.6

---

**Comment by janryWang** [comment]
用values

**Comment by xinshangshangxin** [comment]
![image](https://user-images.githubusercontent.com/8779091/195302959-68ebf7ef-2191-4694-b86b-8e33c037d067.png)


initialValues 不是 初始化值吗?

或者说 initialValues 和 values 使用场景区别是?


`initialValues主要用于异步默认值，针对未设置默认值的字段，只会生效一次，后面都改不了了` https://github.com/alibaba/formily/issues/599

不是只生效一次吗? 为什么会在 删除和添加的时候影响

**Comment by janryWang** [comment]
initialValues  和 values 的区别是，前者可以重置回默认值状态，后者重置直接清空，你这个场景是因为顶层设置了默认值，删除之后重新创建字段，还是会复用默认值的

**Comment by xinshangshangxin** [comment]
好的, 谢谢~
