### ISSUE TITLE
[Bug Report] why @formily/antd array-table field not in function WrapperComp dependencies

### ISSUE THREAD

**Issue by mercyscope** [alibaba/uform#3454]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-react-antd-pure-jsx-omncis)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

### Package
@formily/antd@2.2.7

---

**Comment by janryWang** [comment]
不知道你想表达什么问题

**Comment by mercyscope** [comment]
![Snipaste_2022-10-13_15-45-49](https://user-images.githubusercontent.com/25003730/195534484-6d604100-8801-4f87-b9f2-0d561a26238e.png)

**Comment by mercyscope** [comment]
我切换表单，然后拖拽排序，但是动作结束后field内数据不对，导致排序结果不对

**Comment by janryWang** [comment]
给一个详细的复现 demo吧

**Comment by mercyscope** [comment]
我的理解，field应该在useCallback的依赖里的吧，我回滚到2.1.4版本，不存在这个问题

**Comment by janryWang** [comment]
先给demo吧，我详细看看

**Comment by mercyscope** [comment]
好吧，那我先搞个demo

**Comment by mercyscope** [comment]
https://codesandbox.io/s/gifted-goodall-c58ijc?file=/App.tsx
我点击changeElement后，排序就会有上述问题

**Comment by janryWang** [comment]
的确有你所说的问题，改动点不大，来个PR？

**Comment by mercyscope** [comment]
不了，你们有时间修一下就行
