### ISSUE TITLE
[Bug Report] [Bug Report] Array类组件索引改变导致相对路径出现问题

### ISSUE THREAD

**Issue by ifblooms** [alibaba/uform#3473]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eloquent-hertz-p7zs4z?file=/App.tsx)

### Steps to reproduce
为ArrayTable添加两行数据，修改某行中A2字段的值，该行A3的数值会改变（符合预期）。
点击某行右侧功能上下排序后，再次修改某行中A2字段的值，A3字段的变化行数不对应了（不符合预期）。

### What is expected?
期望ArrayTable的行数拖拽改变后，使用$self.query()获取的相对路径是准确的，不会因为索引改变而改变预期。

### What is actually happening?
-

### Package
@formily/core@2.2.9

---

**Comment by janryWang** [comment]
暂时无解，设计问题导致的，x-reactions 中的主动联动设计的不太好，后续应该会废弃这种用法
