### ISSUE TITLE
[Bug Report] observe 无法被触发问题

### ISSUE THREAD

**Issue by fanmingfei** [alibaba/uform#3478]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-faraday-dx8ln4?file=/App.tsx)

### Steps to reproduce
![](https://user-images.githubusercontent.com/4632277/196325257-ab5aa20d-651e-4fe0-94fb-399242427c47.gif)

observable传入使用原来的对象，是可以监听原来已有列表内容的数据变化的

传入新的对象，原来已有列表内容的数据变化无法被监听到

### What is expected?
传入新的对象，也可以绑定所有数据变化

### What is actually happening?
observable传入使用原来的对象，是可以监听原来已有列表内容的数据变化的

传入新的对象，原来已有列表内容的数据变化无法被监听到

### Package
@formily/reactive@2.2.9

---

**Comment by janryWang** [comment]
demo 太绕了，如果是reactive相关的问题，就把跟reactive无关的都移除掉

**Comment by fanmingfei** [comment]
> demo 太绕了，如果是reactive相关的问题，就把跟reactive无关的都移除掉

修改了一下demo：https://codesandbox.io/s/crazy-rosalind-6qfkpk?file=/App.tsx

25/26行代码是我认为正常的代码

29 行的代码是我认为异常的代码

**Comment by janryWang** [comment]
用法问题，...store是浅合并，改成...toJS(store)

**Comment by fanmingfei** [comment]
> 用法问题，...store是浅合并，改成...toJS(store)

https://codesandbox.io/s/admiring-joji-g4dgrv?file=/App.tsx

如果使用toJS的话，单个数据的引用是会变化的。我希望的只是 store 的引用会变化就好。

**Comment by janryWang** [comment]
> > 用法问题，...store是浅合并，改成...toJS(store)
> 
> https://codesandbox.io/s/admiring-joji-g4dgrv?file=/App.tsx
> 
> 如果使用toJS的话，单个数据的引用是会变化的。我希望的只是 store 的引用会变化就好。

不支持你这种用法的，observe是监听树的变化，如果引用没变，子对象的父节点还是之前的observable对象，没法动态解锁的
