### ISSUE TITLE
[Bug Report] antd版本设计器，属性面板中属性变化后，设计器没有同步变化

### ISSUE THREAD

**Issue by iTrustGuid** [alibaba/uform#3487]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-react-antd-pure-jsx-omncis)

### Steps to reproduce
字段属性类别下的属性变化，会触发设计器状态更新。但其他属性变化，例如组件属性，设计器不会更新状态。如下图所示：

![](https://justgoooo.oss-cn-beijing.aliyuncs.com/article/formily-bug.gif)

### What is expected?
属性变化能正常触发设计器状态更新

### What is actually happening?
属性变化没能正常触发设计器状态更新

### Package
@formily/antd@2.2.9

---

**Comment by iTrustGuid** [comment]
设计器版本： [1.0.0-beta.45](https://www.npmjs.com/package/@designable/core/v/1.0.0-beta.45)

**Comment by iTrustGuid** [comment]
![image](https://user-images.githubusercontent.com/10825268/197727504-d7c00edd-9a80-4694-8cbf-15609a74fc16.png)

先临时用这种方式可以主动触发一次状态更新，可以达到更新设计视图的效果

**Comment by sunWhereCode** [comment]
设计器好像不更新了
