### ISSUE TITLE
[Bug Report] formily-antd-mobile.netlify.app not found

### ISSUE THREAD

**Issue by pccai** [alibaba/uform#3498]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/formilyjs/antd-mobile)

### Steps to reproduce
https://formily-antd-mobile.netlify.app/

### What is expected?
https://formily-antd-mobile.netlify.app/ not found

### What is actually happening?
https://formily-antd-mobile.netlify.app/ not found

### Package
formily-antd-mobile@2.2.10

---

**Comment by darkmice** [comment]
现在可以正常访问了

**Comment by pccai** [comment]
nice!
