### ISSUE TITLE
[Feature Request] 希望支持通过配置 schema 的 x-reactions 修改 x-index 实现字段排序

### ISSUE THREAD

**Issue by prettyboyweiwei** [alibaba/uform#3509]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Discussed in https://github.com/alibaba/formily/discussions/3507

<sup>Originally posted by **prettyboyweiwei** October 31, 2022</sup>

### What does the proposed API look like?
在 schema 中类似配置 title 一样配置响应的 x-index 属性
```json
{
  "x-index": 1,
  "x-reactions": {
    "dependencies": [
      {
        "property": "value",
        "type": "any",
        "name": "value"
      }
    ],
    "fulfill": {
      "state": {
        "title": "{{$deps.value}}",
        "index": "{{$deps.value}}"
      },
    }
  }
}
```

**Comment by janryWang** [comment]
这个相当于改schema结构，需要走受控表单的方式来更新schema https://formilyjs.org/zh-CN/guide/advanced/controlled
