### ISSUE TITLE
文本串联展示详情时width设置不正确

### ISSUE THREAD

**Issue by beihaifeiwu** [alibaba/uform#356]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug

2. Describe your issue:
  文本串联可以使用正确宽度展示内容

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
![image](https://user-images.githubusercontent.com/5372382/67916321-44f22500-fbd0-11e9-9c0c-801567712caf.png)

**Comment by janryWang** [comment]
给个codesandbox吧
