### ISSUE TITLE
[Bug Report] https://designable-antd.formilyjs.org/ 好像挂了

### ISSUE THREAD

**Issue by prettyboyweiwei** [alibaba/uform#3565]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily)

### Steps to reproduce
1. 打开网站 https://designable-antd.formilyjs.org/ 可看到白屏，且控制台有错误

### What is expected?
网站正常访问

### What is actually happening?
网站白屏

### Package
@formily/designable-antd@2.2.12

---

**Comment by arrowing** [comment]
昨天也发现这个问题了，没人解决下么？

**Comment by WinstonSue** [comment]
formily引入antd的包是通过cdn的方式，但是没有指定大版本，antd5.0发布了，cdn地址默认指向5.0，导致报错
