### ISSUE TITLE
[Bug Report] vue schema 模式 $form.readPretty 联动失效

### ISSUE THREAD

**Issue by frehaiku** [alibaba/uform#3570]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-lehmann-nl14fy?file=/src/App.vue)

### Steps to reproduce
点击“切换阅读态”按钮

### What is expected?
textarea 隐藏

### What is actually happening?
textarea 仍展示

### Package
@formily/vue@2.2.12

---

field模型中visible是符合预期，同样例react正常。排查中发现是reactions里少了 textarea 的render更新

**Comment by MisicDemone** [comment]
改成 $self 可以正常更新，暂时不清楚$form为啥不行

**Comment by frehaiku** [comment]
@MisicDemone 老哥🐂 🤩，方便告知下如何排查的吗
