### ISSUE TITLE
[Bug Report] array table设置 initialValues 后，删除一行再添加，原来的value没有清空

### ISSUE THREAD

**Issue by Frida0612** [alibaba/uform#3571]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wizardly-sun-lcmxqn?file=/App.tsx)

### Steps to reproduce
1、设置 initialValues 
2、点击删除
3、点击添加一行

### What is expected?
应该是空白行

### What is actually happening?
保留了最后一行的数据

### Package
@formily/next@2.2.12

---

**Comment by janryWang** [comment]
不是bug，这是默认值逻辑

**Comment by Frida0612** [comment]
1、我理解里initialValue应该只有初始化和重置时候生效；
2、那么请问如何做到删除之后添加的默认行是空的？

**Comment by Frida0612** [comment]
@janryWang 
1、我理解里initialValue应该只有初始化和重置时候生效；
2、那么请问如何做到删除之后添加的默认行是空的？

**Comment by jo0ger** [comment]
同问

**Comment by HuColin** [comment]
配置 defaultValue

**Comment by HuColin** [comment]
`ArrayBase.Addition` 配置 `props.defaultValue` 即可
