### ISSUE TITLE
createFormActions的validate方法，无法获取到具体是哪个字段产生了错误

### ISSUE THREAD

**Issue by lianyzhou** [alibaba/uform#36]
createFormActions().validate().then(() =>{}, (errors) => {console.log(errors)})

打印这个数据时发现，errors是一个字符串数组

![Uploading image.png…]()

无法获取到具体是哪个字段产生了错误。

**Comment by janryWang** [comment]
目前是只支持errors字符串数组，什么场景需要知道具体哪个字段发生了错误？

**Comment by lianyzhou** [comment]
> 目前是只支持errors字符串数组，什么场景需要知道具体哪个字段发生了错误？

比如说，整个表单是通过上一步，下一步进行填写的，校验时发现是第一页的数据出错了，但是页面停留在第三个页面，如果能知道是哪个字段出错了，就能把界面切换回去。

**Comment by janryWang** [comment]
已经在0.1.11中修复，errors现在的数据结构是[{name:"",errors:[]}]的数据结构
