### ISSUE TITLE
建议新增属性用来控制字段是否显示。

### ISSUE THREAD

**Issue by Natumsol** [alibaba/uform#360]
业务中经常有这种需求：某个字段需要提前埋在页面中，但是不需要显示，比如ID。
目前UForm只能通过effects修改state达到目的，比较繁琐。考虑新增某个属性，用来控制某个字段是否显示。比如：
```jsx
<Field type="string" name="name" x-visible={false}/>
```

**Comment by janryWang** [comment]
duplicate with #350
