### ISSUE TITLE
[Bug Report] Code Generation doesn't work on https://designable-antd.formilyjs.org/

### ISSUE THREAD

**Issue by skitsanos** [alibaba/uform#3602]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://designable-antd.formilyjs.org/

### Steps to reproduce
Add any field and try to generate code, on Fusion components link it works, on AntD https://designable-antd.formilyjs.org/ - it doesn't

### What is expected?
Expected to be working demo

### What is actually happening?
loader.js:686          GET https://unpkg.com/monaco-editor@0.30.1/min/vs/editor/editor.main.nls.js net::ERR_ABORTED 502

---

**Comment by janryWang** [comment]
Designable issues need to be submitted to https://github.com/alibaba/designable
