### ISSUE TITLE
[Bug Report] Vue2 使用 SchemaVoidField x-content 存在问题

### ISSUE THREAD

**Issue by yanhao98** [alibaba/uform#3608]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-schemavoidfield-x-content-r0rgw3?file=/src/App.vue)

### Steps to reproduce
访问重现链接。

### What is expected?
<SchemaVoidField x-content="我会被渲染" />

可以正常渲染

### What is actually happening?
<SchemaVoidField x-content="我会被渲染" />

在Vue2时，无法正常渲染。

### Package
@formily/vue@2.2.14

---

试过在Vue 2.6.x和 Vue 2.7.x 都不能正常渲染。
在Vue 3.x 可以正常渲染。

<img width="1972" alt="图片" src="https://user-images.githubusercontent.com/37316281/205891641-8050d081-96d6-466d-a2ce-fd762913f119.png">

**Comment by lumdzeehol** [comment]
vue组件，需要return的是vnode ，字符串是无法渲染的

**Comment by yanhao98** [comment]
在Vue 3 中就可以正常渲染。

在@formily/vue的[核心概念]的[Markup Schema 开发模式]中有这样的的示例。

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/37316281/206114254-71354634-7b00-47de-9ac6-d6a70aa833ec.png">

**Comment by MisicDemone** [comment]
vue2必须要有个component：https://codesandbox.io/s/formily-schemavoidfield-x-content-forked-z4br4d?file=/src/App.vue

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/10394516/206674782-b6f3f5ae-1bbd-4825-a5a7-736fa35b0fbe.png">
