### ISSUE TITLE
[Bug Report] field.setState display hidden visible 冲突

### ISSUE THREAD

**Issue by xiaosi-ss** [alibaba/uform#3614]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hungry-pond-s95lm0?file=/App.tsx)

### Steps to reproduce
setState的时候  x-hidden = true  value丢失

因为 display 跟 visible set 的触发顺序是json 的顺序,
先走的 display, 再走 visible 导致value丢失

### What is expected?
x-hidden情况下正常赋值Value

### What is actually happening?
x-hidden导致value丢失

### Package
@formily/core@2.2.14

---

**Comment by janryWang** [comment]
setState设计的有问题，后面是打算废弃的，不推荐使用

**Comment by xiaosi-ss** [comment]
我自己修一下？很快的……

**Comment by janryWang** [comment]
> 我自己修一下？很快的……

说一下你的修复方案？

**Comment by xiaosi-ss** [comment]
![image](https://user-images.githubusercontent.com/7309546/206415378-0a840ae0-a36c-4745-b25e-81ff1c9ad44b.png)

// 我的使用场景
  const formGraph = form.getFormGraph();
  form2.setFormGraph(formGraph);

**Comment by xiaosi-ss** [comment]
一般手动 setState 的时候确实不会有人同时 set visible 跟 display

**Comment by janryWang** [comment]
> ![image](https://user-images.githubusercontent.com/7309546/206415378-0a840ae0-a36c-4745-b25e-81ff1c9ad44b.png)
> 
> // 我的使用场景 const formGraph = form.getFormGraph(); form2.setFormGraph(formGraph);

你是希望保存graph做什么呢？

**Comment by xiaosi-ss** [comment]
visible 跟 display 在 Field 模型中同时存在的一个隐患, 或者说是 Field 模型中的  computed 类型字段跟  state 字段重复设置会隐式存在优先级的问题

**Comment by charlzyx** [comment]
> setState设计的有问题，后面是打算废弃的，不推荐使用

~~害怕.jpg~~

`setFormGraph` 文档说明:  **将 Immutable 字段状态导入至表单模型中**
[![image](https://user-images.githubusercontent.com/18055018/206422716-2cec01d1-340f-4b84-9607-301dbf3d1c89.png)](https://github.com/alibaba/formily/blob/4e1ce55a459d66d9c64c7e24358d74e7fa24c5e2/packages/core/docs/guide/form.zh-CN.md)
上方 demo 中字段 display 状态值在 get -> set 之后, 发生了意料之外的变化 (hidden -> none) , 这样使用的场景不一定对, 但单独针对 setFormGraph 这个api 的话的描述的话,  state 中的 display 值变化, 应该不是一个符合预期的行为

为了便于理解

> 因为 display 跟 visible set 的触发顺序是json 的顺序,
> 先走的 display, 再走 visible 导致value丢失

我写了个最小复现来方便理解

![image](https://user-images.githubusercontent.com/18055018/206423782-fe98d109-a1af-4e31-b783-5433bcc57938.png)


[![Edit suspicious-dew-2dvhex](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-dew-2dvhex?fontsize=14&hidenavigation=1&theme=dark)

本质上的问题正如上面所说:  是 Field 模型中的visible 跟 hidden 共同消费了 display 字段导致的冲突
```js
set visible -> display = 'hidden' | 'none'
set hidden -> display = 'hidden' | 'visible'
```
[源码位置](https://github.com/alibaba/formily/blob/formily_next/packages/core/src/models/BaseField.ts#L136-L164)

我更愿意理解为是模型设计的一点小瑕疵或者是一点便捷性的妥协

**Comment by janryWang** [comment]
> > setState设计的有问题，后面是打算废弃的，不推荐使用
> 
> ~害怕.jpg~
> 
> `setFormGraph` 文档说明: **将 Immutable 字段状态导入至表单模型中** [![image](https://user-images.githubusercontent.com/18055018/206422716-2cec01d1-340f-4b84-9607-301dbf3d1c89.png)](https://github.com/alibaba/formily/blob/4e1ce55a459d66d9c64c7e24358d74e7fa24c5e2/packages/core/docs/guide/form.zh-CN.md) 上方 demo 中字段 display 状态值在 get -> set 之后, 发生了意料之外的变化 (hidden -> none) , 这样使用的场景不一定对, 但单独针对 setFormGraph 这个api 的话的描述的话, state 中的 display 值变化, 应该不是一个符合预期的行为
> 
> 为了便于理解
> 
> > 因为 display 跟 visible set 的触发顺序是json 的顺序,
> > 先走的 display, 再走 visible 导致value丢失
> 
> 我写了个最小复现来方便理解
> 
> ![image](https://user-images.githubusercontent.com/18055018/206423782-fe98d109-a1af-4e31-b783-5433bcc57938.png)
> 
> [![Edit suspicious-dew-2dvhex](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/suspicious-dew-2dvhex?fontsize=14&hidenavigation=1&theme=dark)
> 
> 本质上的问题正如上面所说: 是 Field 模型中的visible 跟 hidden 共同消费了 display 字段导致的冲突
> 
> ```js
> set visible -> display = 'hidden' | 'none'
> set hidden -> display = 'hidden' | 'visible'
> ```
> 
> [源码位置](https://github.com/alibaba/formily/blob/formily_next/packages/core/src/models/BaseField.ts#L136-L164)
> 
> 我更愿意理解为是模型设计的一点小瑕疵或者是一点便捷性的妥协

说的对，这就是因为支持setState才会存在这个问题，如果是正常引用式操作是不会存在的，就是按照谁后赋值，谁的优先级高

**Comment by xiaosi-ss** [comment]
![image](https://user-images.githubusercontent.com/7309546/207217273-4822348d-6065-4173-9cb7-1a3fb7dc4b4f.png)
我的使用场景就是复制一个form  form里面存在x-hidden的字段 所以当底层调用setState的时候清空我x-hidden字段value  个人认为还是不合理的  因为setFormGraph 确实没有复原我的Form
