### ISSUE TITLE
[Bug Report] Field类型错误

### ISSUE THREAD

**Issue by HavocZhang** [alibaba/uform#3622]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-vue-ant-design-vue-markup-schema-donivp?file=/src/App.vue)

### Steps to reproduce
`
const useAsyncDataSource = (pattern: any, service: any) => {
    onFieldReact(pattern, (field: Field) => {
      field.loading = true
      service().then(
        action.bound &&
          action.bound((data: any) => {
            field.dataSource = data
            field.loading = false
          })
      )
    })
  }
`
类型“(field: Field) => void”的参数不能赋给类型“(field: GeneralField, form: Form<any>) => void”的参数。
  参数“field”和“field” 的类型不兼容。

### What is expected?
我看了类型定义ts type GeneralField = Field
但是不知道为什么这个地方却无法兼容

### What is actually happening?
应该类型是兼容的

### Package
@formily/core@2.2.14

---

**Comment by xiaosi-ss** [comment]
用isField判断一下？

**Comment by ksdaylight** [comment]
目前的版本也这样报错...
要改成这样
```
const useAsyncDataSource = (
  pattern: FormPathPattern,
  service: (field: Field) => Promise<{ label: string; value: any }[]>,
) => {
  onFieldReact(pattern, (field) => {
    if (!isField(field)) return; // 检查 field 是否是 Field 类型
    field.loading = true;
    service(field).then(
      action.bound?.((data) => {
        field.dataSource = data;
        field.loading = false;
      }),
    );
  });
};
```
