### ISSUE TITLE
vue/element-ui/Radio点击后无法切换值

### ISSUE THREAD

**Issue by tanghuibo** [alibaba/uform#3640]
示例: https://element.formilyjs.org/guide/radio.html#markup-schema-%E6%A1%88%E4%BE%8B

**Comment by yanhao98** [comment]
这个是有问题的：
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/37316281/209319086-de005512-8a40-4975-a59d-faab7b35dc3e.png">


这是我自己桥接的。
造成这个的原因就是：<ElRadioGroup /> 组件的change事件带的值是undefind。
<img width="744" alt="image" src="https://user-images.githubusercontent.com/37316281/209319212-53b9341f-620d-4447-b670-7edd49818b99.png">
