### ISSUE TITLE
[Bug Report] vue2/element-ui/radio 点击失效

### ISSUE THREAD

**Issue by tanghuibo** [alibaba/uform#3641]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily/tree/formily_next/packages/element/src/radio)

### Steps to reproduce
地址: https://element.formilyjs.org/guide/radio.html#markup-schema-%E6%A1%88%E4%BE%8B，点击切换选项

### What is expected?
成功切换

### What is actually happening?
切换失败

### Package
@formily/element@2.2.15

---

**Comment by frehaiku** [comment]
@MisicDemone 可以一起看下，看起来是 PR https://github.com/alibaba/formily/commit/82ca678d 引起
