### ISSUE TITLE
[Bug Report] 更新schema中的x-components-props，没有效果

### ISSUE THREAD

**Issue by JerryFan626** [alibaba/uform#3653]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-x-component-props-not-work-q3igk9?file=/App.tsx)

### Steps to reproduce
更新schema中的x-xcomponents-props
详细见上面代码

### What is expected?
期望：更新schema中每个字段的x-components-props，对应字段中的x-components-props更新

### What is actually happening?
更新schema中每个字段的x-components-props，没有生效。
字段中的x-components-props没有更新。

### Package
@formily/reactive@2.2.12

---

**Comment by janryWang** [comment]
https://formilyjs.org/zh-CN/guide/advanced/controlled
