### ISSUE TITLE
[Feature] Schema Support name property

### ISSUE THREAD

**Issue by skyfore** [alibaba/uform#3664]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-snow-ftclu8?file=/App.tsx)

### Steps to reproduce
Just see CodeSandbox

### What is expected?
expect schema support name

希望 Schema 能够支持 name 属性，用于处理数据解构相关，然后本省的 name 用于设置联动，配置字段模型相关

### What is actually happening?
not working

### Package
@formily/react@2.2.16

---

**Comment by janryWang** [comment]
无法支持，因为目前json schema是基于properties的key来定义name的，如果支持name属性，那key与name属性会存在不一致的情况，这个以谁为准，说不清楚

**Comment by skyfore** [comment]
有没有可能一个单独的定义用来做解构数据，因为当我使用了解构作为 key 时，写联动逻辑出问题是会很难排查，比如

```js
const schema = {
  '{ label: a, value: b }': {
    'x-component': 'Select'
  },
  b: {
    'x-component': 'Text'
  }
}

const effect = (form) => {
  // 这里的 key 很容易就会出现问题，比如空格少一个
  onFieldChange('{label: a, value: b }', (state) => {
    setFieldState('b', (field) => {
      field.value = state.value
    })
  })
}

// 希望的 schema 定义
const newSchema = {
  a: {
    dataName: '{ label: a, value: b }',
    'x-component': 'Select'
  },
  b: {
    'x-component': 'Text'
  }
}
```
