### ISSUE TITLE
[Bug Report] 自增表格 设置列展示状态为半隐藏时，数据丢失

### ISSUE THREAD

**Issue by zoley** [alibaba/uform#3678]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gallant-wind-bdg80k?file=/App.tsx)

### Steps to reproduce
![微信图片_20230117134654.png](https://img.fy6b.com/2023/01/17/886cd7ad3e30e.png)

`"x-display": "hidden",`

表格列设置 "x-display": "hidden" ，在渲染时候直接去掉了该列，导致该列下的输入框 bbb 的默认值在表单保存时丢失。
把 x-display 改为 x-hidden 也是无效的。

### What is expected?
期望 自增表格 列UI隐藏 但 数据保留 

### What is actually happening?
自增表格 列 DOM 直接消失了 数据自然也丢失

### Package
@formily/antd@2.2.16

---

**Comment by janryWang** [comment]
你这个数据是一条条添加的，整个列都隐藏了，字段是没法初始化的，只有初始化之后才能收集到默认值
