### ISSUE TITLE
[Bug Report] when form has ArrayField, use setInitialValues and setValues with the same `values` will cause Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ChrisShen93** [alibaba/uform#3688]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-kepler-s238sw?file=/App.tsx)

### Steps to reproduce
open the link

then modify the field and press enter

the error will occur

### What is expected?
user can modify form as usual

### What is actually happening?
Maximum call stack size exceeded

### Package
@formily/core@2.2.17

---

**Comment by janryWang** [comment]
自己 clone 一下吧，因为 form 内部会监听 initialValues 变化去同步到 values 上，同一个引用的话，变化来源成死循环了，但是 formily 不太好对传入的数据进行 clone ，因为如果外部数据是 observable 数据，是需要引用共享变化，不过我有个疑问，为什么要重复调用？直接 setInitialValues 不就行了？

**Comment by ChrisShen93** [comment]
嗯，现在是通过cloneDeep暂时解决的问题

重复调用是历史遗留问题，💩山不太敢动。。

既然符合预期我就close了吧

thx
