### ISSUE TITLE
[Feature Request] FormItem支持配置label过长时不显示tooltip

### ISSUE THREAD

**Issue by elvinzhu** [alibaba/uform#3689]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
领导嫌太难看

### What does the proposed API look like?

labelOverflow: 'tooltip' | 'ellipsis' | 'none';

tooltip：省略加tooltip
ellipsis：仅省略
none：不做处理

**Comment by janryWang** [comment]
没懂，如果溢出了，不用tooltip提示应该用什么提示？需求是直接被裁掉？

**Comment by elvinzhu** [comment]
@janryWang 我们要求每个组件的总长保持一致，label和input都自适应。如下图

![image](https://user-images.githubusercontent.com/10510488/215992096-2be5b413-75e2-416b-a443-e354f00cfc88.png)

**Comment by xiaosi-ss** [comment]
设置一下labelWidth不就可以了么
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7309546/216012331-35ec5dbb-cb20-44c6-8cf6-a26be712a163.png">

**Comment by janryWang** [comment]
> 设置一下labelWidth不就可以了么 <img alt="image" width="1440" src="https://user-images.githubusercontent.com/7309546/216012331-35ec5dbb-cb20-44c6-8cf6-a26be712a163.png">

嗯，这是最佳实践，issue 先关了 @elvinzhu
