### ISSUE TITLE
关于onValidateFailed/submit/validate返回的错误信息数据结构优化提案

### ISSUE THREAD

**Issue by janryWang** [alibaba/uform#37]
问题来源于 https://github.com/alibaba/uform/issues/36

目前针对onValidateFailed/submit/validate所返回的错误消息都是一个字符串数组，并未明确给出具体字段的错误信息，这里是一个设计上的缺陷，如果要修复，最好的解决方案就是修改其数据结构

```
["该字段必填","该字段必填","该字段必填"]

===>

[{name:"aaa",message:"该字段必填"},{name:"bbb",message:"该字段必填"}]

```

显然，这是存在Break Change的，需要确认所有用户是否对所返回的错误消息做处理，如果没有，则可以在下个版本做修正。

**Comment by monkindey** [comment]
第二个参数支持? 不需要 Break Change

```js
createFormActions().validate().then(() =>{}, (errors, all) => {console.log(errors, all)})
```

**Comment by liuyiliuyi** [comment]
你好，我想从 Next/Form 组件进行迁移，想问几个问题：
1. Next 组件库的 Field 是提供 requiredMessage 等等自定义错误信息。
2. Next 组件库校验不通过是会 将对应表单的边框变成红色即（给与 .next-error 类名）。
3. Next 组件库的 Field 是提供 setError 的方法，可以给对应字段 setError。
4. 是否有 api，可获取对应的 actions，如 Next 中的 saveField。
非常感谢 😁

**Comment by janryWang** [comment]
@liuyiliuyi 请新创建issue讨论相关问题，目前的主题与您所提到的主题并不match

**Comment by liuyiliuyi** [comment]
@janryWang  不好意思，因为有关于校验所以我就跟在了这个主题下，非常抱歉给您造成困扰。不好意思，已经重开 issue，希望可以给予解答，谢谢。
这个功能我也是非常希望您可以支持。
关于校验可以看下 next/Form 的实现 （虽然我觉得您一定是看过的）。
非常感谢 ☺
