### ISSUE TITLE
[Bug Report] vite build 后 require is not defined

### ISSUE THREAD

**Issue by madocto** [alibaba/uform#3704]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/imoctopus/vite-formily)

### Steps to reproduce
`yarn build`

### What is expected?
正常显示

### What is actually happening?
require is not defined

### Package
@formily/react@2.2.18

---

**Comment by madocto** [comment]
回退到 2.2.6 版本没问题

**Comment by zzzzzhowie** [comment]
这个问题 2.2.20 还存在，是否能跟进一下
