### ISSUE TITLE
[Feature Request] Field Model Support freeze prop

### ISSUE THREAD

**Issue by skyfore** [alibaba/uform#3706]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Normally, we won't add field in schema when need hidden all time. But the effects not works which bind with hidden field.
We could add hidden property instead, but some field can easy change it.

So maybe we could add freeze prop as *Object.freeze*.

---

当我们想要设置字段一直隐藏有两种方式：
1. 直接在生成 schema 或者写 JSX 的时候直接隐藏，这样字段模型里面也没有这个字段，但是这样会导致所有涉及到这个字段的联动逻辑不生效，比如其他字段依赖了它作为判断。
2. 给这个字段设置为 hidden，这样也能在字段模型中生效，并且其绑定的联动逻辑也能正常工作，但是会被其他字段的逻辑轻松更改。

有没有可能我们可以给这个字段设置为 freeze，这样其他字段在影响它时能够给到提醒，这个字段是被冻结了的，需要先解除冻结，或者无法影响。

这个场景在动态表单中是一个很常见的问题，因为联动逻辑和字段模型解析是一个通用逻辑，假如我给 A 字段设置了始终隐藏，我需要其他字段依赖它进行值判断可以生效，并且绑定在其他字段上的联动逻辑是不能更改字段 A 的显隐。

### What does the proposed API look like?
```js
// js
field.freeze()
field.unfreeze()

// json schema
{
  a: {
    type: 'string',
    'x-freeze': true
  }
}
```

**Comment by janryWang** [comment]
你在联动的字段属性表达式中直接依赖字段的 display 属性做判断不就行了么

**Comment by skyfore** [comment]
我现在就是这样做的，但是我们是动态的表单，所以可能会出现配置为一直隐藏的字段会因为某一个联动逻辑配置将其修改为显示，我们配置时字段的属性和联动逻辑是分开的

**Comment by janryWang** [comment]
不太理解实际的业务需求是什么，从没遇到过，可以深入讨论一下吗？

**Comment by skyfore** [comment]
场景就很简单，假设有 `A`、`B`、`C` 三个字段，其中 `B` 的展示依赖 `A`，但是 `A` 属于后端默认给到的值，用户不可见且不可编辑，但是整体表单是运营配置的，所以有可能出现因为配置错误 `C` 打开了 `A` 的展示或者属性变化。
所以假设目前有 freeze 的能力，`A` 就可以一直保持默认状态

**Comment by janryWang** [comment]
我觉得这个是你们的产品逻辑，应该是在配置系统中给出提醒，或者做控制的，跟formily能力没关系

**Comment by skyfore** [comment]
是的，现在就是在配置系统内限制的，不过就和 Object.freeze 一样可以考虑提供这个能力

**Comment by skyfore** [comment]
还有一个问题请教一下，假如我现在要增强枚举支持废弃逻辑【editable 下 dataSource 过滤带有废弃标签的枚举，readPretty 下不进行过滤】这种应该在哪里做更好一点，我现在想到的是两种：
1. 包装 connect 函数
2. Form 增加 effects

**Comment by janryWang** [comment]
> 还有一个问题请教一下，假如我现在要增强枚举支持废弃逻辑【editable 下 dataSource 过滤带有废弃标签的枚举，readPretty 下不进行过滤】这种应该在哪里做更好一点，我现在想到的是两种：
> 
> 1. 包装 connect 函数
> 2. Form 增加 effects

这个在 connect 里做吧
