### ISSUE TITLE
[Feature Request] ArrayTable schema 场景下，如何获取 table 实例 ref

### ISSUE THREAD

**Issue by liam61** [alibaba/uform#3715]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ArrayTable schema 场景下，获取 table 实例 ref

### What does the proposed API look like?
{
  'x-component-props': {
    ref: tableRef
  }
}

**Comment by coolbob1998** [comment]
可以使用 `field.inject` `field.invoke`
示例可以参考 [demo](https://codesandbox.io/p/sandbox/lively-grass-2gvn5n?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A37%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A37%7D%5D)

**Comment by liam61** [comment]
好的，感谢
