### ISSUE TITLE
[Feature Request] 发一个稳定版本

### ISSUE THREAD

**Issue by kaoding** [alibaba/uform#3718]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
v3.0.0

### What does the proposed API look like?
v3.0.0

**Comment by janryWang** [comment]
2.0 存在什么问题？为啥要发3.0

**Comment by kaoding** [comment]
在 https://github.com/formilyjs/antd 提不Issue，直接提到这里了。
