### ISSUE TITLE
[Feature Request] ArrayTable.Index 序号表示是否可以自定义？现在固定了 #1. 的表示

### ISSUE THREAD

**Issue by BBSQQ** [alibaba/uform#3724]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如题

### What does the proposed API look like?
```
properties: {
    index: {
          type: 'void',
          'x-component': 'ArrayTable.Index',
          'x-component-props': {
               content: (index) => string,
          }
    },
},
```

**Comment by janryWang** [comment]
直接写个自定义组件就行了，内部 useIndex 拿到索引

**Comment by BBSQQ** [comment]
ok 最开始找 useIndex 没找到，原来是挂在 ArrayTable 上了

**Comment by cizhaYang** [comment]
@BBSQQ 自定义怎么写
