### ISSUE TITLE
[Feature Request] SchemaField 不能渲染div

### ISSUE THREAD

**Issue by jxp1147** [alibaba/uform#3725]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能够渲染出div 从而控制页面布局

### What does the proposed API look like?
  <Form :form="form">
        <SchemaField>
 <div class="form-row">
            <SchemaStringField class="half-row"
                               name="reduceThreshold"
                               title="降级阈值"
                               x-decorator="FormItem"
                               x-component="Input" />
            <SchemaBooleanField class="half-row"
                                name="isOpenflowControl"
                                title="是否开启流控 (1或0)"
                                x-decorator="FormItem"
                                x-component="Switch" />
          </div>
        </SchemaField>
        <Submit @submit="onSubmit">提交</Submit>
      </Form>

**Comment by lumdzeehol** [comment]
div是可以渲染的，可以提供一下最小复现链接看看
