### ISSUE TITLE
[Feature Request]  线上环境关闭 console

### ISSUE THREAD

**Issue by saiyagg** [alibaba/uform#3730]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.
 

### What problem does this feature solve?  
- @formily/antd@1.3.17
- 由于业务自定义组件与内置组件名字重复，所以有 console.warn， 希望能区分环境， 在自定义组件重名时生产环境不再 console.warn()
![image](https://user-images.githubusercontent.com/432377/220078823-7490cbcd-07ea-45e5-93bb-af4895db4a88.png)

### What does the proposed API look like?    
ENV !== 'PROD' && console.warn();

**Comment by janryWang** [comment]
1.x 已经不维护，建议升级 2.x
