### ISSUE TITLE
[Bug Report] antdv-x3的form-collapse组件无法传递组件参数

### ISSUE THREAD

**Issue by haibins** [alibaba/uform#3733]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-volhard-zo3p3h?file=/src/App.vue)

### Steps to reproduce
FormCollapse传递组件属性不生效

### What is expected?
属性能够正常生效

### What is actually happening?
FormCollapse传递组件属性不生效

### Package
@formily/antdv-x3@1.0.0

---

![](https://user-images.githubusercontent.com/29914762/220307038-e9394d89-4232-4e58-a536-b110d2f2d484.png)

**Comment by zhouxinyong** [comment]
我看下这个问题

**Comment by zhouxinyong** [comment]
已修复
