### ISSUE TITLE
[Bug Report] antdv5的折叠面板无法折叠

### ISSUE THREAD

**Issue by phoema** [alibaba/uform#3765]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ft6j62)

### Steps to reproduce
cord的版本2.2.13和2.2.21都试过了

https://antd5.formilyjs.org/zh-CN/components/form-collapse
JSON Schema 案例打开到codesandbox中执行

### What is expected?
可折叠

### What is actually happening?
未折叠

### Package
@formily/antd-v5@2.2.21

---

**Comment by yiyunwan** [comment]
这个是@formily/reactive版本问题导致的，如果是本地可以检查下，codesandbox上暂时没找到原因

**Comment by yiyunwan** [comment]
保持@formily/reactive同一个版本即可

**Comment by phoema** [comment]
收到。
所有formily的包版本，强制保持到2.2.20解决了
内部依赖使用了^指定版本号，获取内部依赖的时候自动升级到了最新版
