### ISSUE TITLE
[Bug Report] @formily/antd-v5 使用cnpm i 安装后报错

### ISSUE THREAD

**Issue by an9el** [alibaba/uform#3781]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-oskar-q7kj4z)

### Steps to reproduce
cnpm i

安装完依赖之后页面就报错

### What is expected?
能够使用cnpm i 进行包的安装

### What is actually happening?
pnpm i 安装后可以正常使用，cnpm i 不行

### Package
@formily/antd-v5@1.0.1

---

**Comment by yiyunwan** [comment]
能提供个github仓库和例子吗

**Comment by yiyunwan** [comment]
我试了下cnpm 是可以使用的，具体可以看下demo https://github.com/yiyunwan/react-formily
