### ISSUE TITLE
[Bug Report] Manually changing `form.modified` prevents it from autoupdating

### ISSUE THREAD

**Issue by Faithfinder** [alibaba/uform#3784]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-modified-reset-ttr2p9?file=/src/App.tsx)

### Steps to reproduce
- Edit the field
- Observe "Modified" changing to `true`
- Submit the form
- Modified changes to `false`
- Edit the field again
- Modified stays `false`

### What is expected?
`Modified` changes to `true` when a field is edited.

### What is actually happening?
See repro

### Package
@formily/react@2.2.21

---

My use case is, there's no redirection after form submission, the form stays on screen. However, I want it to, essentially, be reset. Except, `reset` will also reset `values` to `initialValues`, and that's not what I want.
I'm still exploring Formily, so I'm not yet sure what the best way to reset a form is. 
Initially I just reset `modified` back to `false` and discovered this bug. Now I do this:

```ts
form.submit(onSubmit);
form.setInitialValues(form.values);
await form.reset();
```

This seems to work fine, if a bit too verbose for my taste.

However, I think form should not stop tracking modification if you just set `modified` to `false`.

**Comment by janryWang** [comment]
Formily thinks that the modified attribute can only be reset when reset is reasonable. Simply setting modified to false does not accurately indicate that the field has been modified, so Formily recommends using reset to reset the modified state

**Comment by Faithfinder** [comment]
> Formily thinks that the modified attribute can only be reset when reset is reasonable. Simply setting modified to false does not accurately indicate that the field has been modified, so Formily recommends using reset to reset the modified state

Should `modified` be marked as `readonly` at type level then?

**Comment by LaamGinghong** [comment]
@janryWang Is there any way to reset modified state but don't reset form data?
