### ISSUE TITLE
[Bug Report] 为什么ISchema的properties会有string类型

### ISSUE THREAD

**Issue by dxiongya** [alibaba/uform#3786]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-oskar-q7kj4z?file=/App.tsx)

### Steps to reproduce
无，仅仅类型问题

### What is expected?
就是对ISchema properties做处理的时候遇到存在string类型，但是文档内提供的是Record<string, ISchema>，如果存在string，什么场景下使用？

### What is actually happening?
给了string | Record<string, ISchema>

### Package
@formily/json-schema@2.2.19

---

**Comment by dxiongya** [comment]
我有看到ISchema下做了Stringify，但是我想知道properties也是可能存在stirng？如果存在又有啥用，怎么用

**Comment by dxiongya** [comment]
还有items，我暂时没有看到items是ISchema[]的类型，我想问下什么情况下会出现，我按了下文档没找到为ISchema[]的demo

**Comment by janryWang** [comment]
表达式写法
