### ISSUE TITLE
关于从 next/Form 组件迁移至 uform 的疑问

### ISSUE THREAD

**Issue by liuyiliuyi** [alibaba/uform#38]
1. How would you tag this issue?
  - Question

2. Describe your issue:

你好，我想从 Next/Form 组件进行迁移，有如下几个问题：
- Next 组件库的 Field 是提供 requiredMessage 等等自定义错误信息。
- Next 组件库校验不通过是会将对应表单的边框变成红色即给与 .next-error 类名。
- Next 组件库的 Field 是提供 setError 的方法，可以给对应字段 setError。
- 是否有 api，可获取对应的 actions，如 Next 中的 saveField。
不知 uform 是否支持这些功能
非常期待与感谢您的回答 😁
谢谢！

**Comment by janryWang** [comment]
1. 自定义错误消息可以通过x-rules来自定义，这里是文档 https://alibaba.github.io/uform/#/97UlUl/2rC4C7T5T6
2. .next-error类名是会有的，这个放心
3. setError是不会暴露的，针对手动设置错误消息uform有自己的方式实现，可以参考 https://alibaba.github.io/uform/#/YZCyCk/kEhrhbUWS4 中联动校验例子
4. 不明白什么是saveField，是手动提交表单的action？还是什么
