### ISSUE TITLE
[Bug Report] antd-v5 ArrayTable拖拽异常

### ISSUE THREAD

**Issue by sTeADone** [alibaba/uform#3800]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tpovwc)

### Steps to reproduce
1. 打开 https://antd5.formilyjs.org/components/array-table 的文档示例
2. 新建两行
3. 向下拖拽第二行

### What is expected?
正常拖拽

### What is actually happening?
上方内容异常滚动
![](https://p.sda1.dev/11/5963bb32e126db1d3dc1ce91ec6e4c96/CPT2304221549-1201x214.gif)

拖拽行内容被遮挡
![](https://p.sda1.dev/11/0484ef1f1374724543d9402068d5b9c2/CPT2304221550-238x164.gif)

### Package
@formily/antd-v5@1.0.1-rc.2

---

**Comment by yiyunwan** [comment]
fix by https://github.com/formilyjs/antd/pull/7

**Comment by sTeADone** [comment]
z-index没生效 因为position为static
![image](https://github.com/alibaba/formily/assets/70431485/1668e413-1e8d-4d21-93ea-9558dbcadfae)
