### ISSUE TITLE
[Bug Report] 布局组件为“阅读”UI形态下时，嵌套的子输入组件为“禁用”UI形态时，输入组件的UI形态会错误回显成“阅读”UI形态。

### ISSUE THREAD

**Issue by zhangXiaoYuuu** [alibaba/uform#3822]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-bartik-lwsgwg?file=/App.tsx:875-883)

### Steps to reproduce
1. 使用任意布局组件，设置ui形态为阅读
2. 拖拽任意输入组件到布局组件中，设置ui形态为禁用

### What is expected?
输入组件没有按照预期展示禁用效果

### What is actually happening?
预期看到输入组件的禁用效果

### Package
@formily/core@2.2.24

---

在低版本2.0.18中没有存在这种问题，高版本存在。

**Comment by janryWang** [comment]
这个问题做过优化，阅读态优先级高于禁用态，如果本来就是整体阅读态，内部再用禁用态就会特别丑

**Comment by zhmushan** [comment]
@janryWang 「丑」或「不丑」有点太主观了，现在的问题是「能」与「不能」，子级居然无法覆盖父级的配置。
在整体阅读态下设置禁用是开发者 **故意** 的行为，他使用这个能力的时候和丑不丑无关了。

**Comment by janryWang** [comment]
> @janryWang 「丑」或「不丑」有点太主观了，现在的问题是「能」与「不能」，子级居然无法覆盖父级的配置。 在整体阅读态下设置禁用是开发者 **故意** 的行为，他使用这个能力的时候和丑不丑无关了。

阅读态本身就代表禁止编辑，同时是以一种更好阅读的形态来展示，所以对于这个包含关系，我们做了内置处理，相当于是一种约定
