### ISSUE TITLE
[Bug Report] form.validate中遇到了一些问题

### ISSUE THREAD

**Issue by GuoSTZ** [alibaba/uform#3825]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/formily-zibmnb)

### Steps to reproduce
1. 点击「提交」

2. 点击「校验输入框1」，此时发现「当前校验失败的组件有」的内容中，输出了所有的输入框组件

3. 点击「同时校验账密」按钮，发现校验能够直接进入then回调，但实际上并没有触发必填校验

### What is expected?
1. form.validate()能够支持仅针对单个字段做校验，而不收集其他字段的相关信息
 
2. form.validate()能够支持同时校验多个字段

### What is actually happening?
1. 当且仅当有其他字段存在校验失败的情况下，此时进行操作

      ```JavaScript

       form
         .validate(['input1'])
         .then(() => console.log("input1 完成校验"))
        .catch(error => console.log("input1 校验失败"))

      ```

      会发现此次校验进入了catch，且能够打印出其他校验失败的字段的信息

3. form.validate(["account", "password"])，目前似乎并不支持同时校验两个字段，点击按钮没有反应，且方法也不会触发，暂时使用Promise.allSettled来做替代，但仍有一些不便之处

### Package
@formily/core@2.2.21
其他包也都是2.2.21版本

---

希望有大佬能看看，是不是我的写法有问题

**Comment by janryWang** [comment]
看api文档，validate传参可以指定多个字段的，用的路径匹配语法

**Comment by GuoSTZ** [comment]
> 看api文档，validate传参可以指定多个字段的，用的路径匹配语法

我试了一下，使用form.validate([FormPath.parse("*(account,password)").toString()])是可以校验到这两个字段的，
不过关于另外一个问题，就是validate方法能够收集到其他字段的报错信息，导致无法通过校验，这个有什么方案能解决吗

**Comment by janryWang** [comment]
1. form.validate("*(account,password)") 这样就能校验，没必要那么复杂
2. 具体什么问题，codesandbox 能复现吗

**Comment by GuoSTZ** [comment]
> 1. form.validate("*(account,password)") 这样就能校验，没必要那么复杂
> 2. 具体什么问题，codesandbox 能复现吗

codesandbox能够复现的，具体复现步骤如下：
1. 点击「校验输入框1」，收集到 1 条错误信息，包含【输入框1错误信息】
2. 点击「同时校验账密」，收集到 3 条错误信息，包含【输入框1错误信息，账号错误信息，密码错误信息】

「同时校验账密」按钮只是去校验了账号和密码，不应该收集到输入框1的错误信息才对

**Comment by YanZiSen** [comment]
遇到了同样的问题，校验某个字段的时候如果该字段校验通过，其他字段有报错，也会抛出异常；
