### ISSUE TITLE
[Bug Report] 表单设计器配置依赖会白屏

### ISSUE THREAD

**Issue by kaneruan** [alibaba/uform#3845]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

https://designable-antd.formilyjs.org/

### Steps to reproduce
https://designable-antd.formilyjs.org/

### What is expected?
不会出现白屏

### What is actually happening?
出现了白屏

### Package
@formily/designable-antd@2.2.24

---

**Comment by kaneruan** [comment]
<img width="1752" alt="截屏2023-06-03 15 08 59" src="https://github.com/alibaba/formily/assets/13065289/c583266d-ed90-4f27-a5f9-30d0b51a021e">
<img width="1792" alt="截屏2023-06-03 15 09 09" src="https://github.com/alibaba/formily/assets/13065289/d7e050c7-6a2c-4857-86c5-a744070cf2ee">
<img width="1774" alt="截屏2023-06-03 15 09 18" src="https://github.com/alibaba/formily/assets/13065289/3eb5e58f-e1c5-458d-af46-ab4515d93ff3">

**Comment by janryWang** [comment]
非常抱歉，现在 designable 暂停维护了🙃

**Comment by phoema** [comment]
> 非常抱歉，现在 designable 暂停维护了🙃

请问本地的拖拽功能目前需要使用什么组件来实现呢？

**Comment by my9074** [comment]
> 非常抱歉，现在 designable 暂停维护了🙃

@janryWang 请问现在 formily 可以用哪个设计器？想找一个可以基于 formily 支持 vue 组件的设计器
