### ISSUE TITLE
[Bug Report] Can't find stylesheet to import.

### ISSUE THREAD

**Issue by Silence-dream** [alibaba/uform#3848]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://stackblitz.com/edit/vitejs-vite-uju7kq?file=vite.config.js)

### Steps to reproduce

打开stackblitz即可看见

### What is expected?
预期是正确的引入sass
[@import '~@alifd/next/lib/core/index-noreset.scss';
](https://github.com/alibaba/formily/blob/7477e86aa7f7fd5d14866779cdf10b541432af80/packages/next/src/array-table/main.scss#LL1C20-L1C20)

### What is actually happening?
<img width="853" alt="image" src="https://github.com/alibaba/formily/assets/42824008/41a91341-4f63-40a9-87c8-e5577195d482">

### Package
@formily/next@2.2.24

---

**Comment by janryWang** [comment]
fusion 不支持 vite 吧？

**Comment by Silence-dream** [comment]
> fusion 不支持 vite 吧？

fusion支持vite的,只在引入formily的时候会出现这个问题

**Comment by lumdzeehol** [comment]
vite 配置一下alias就能解决了， 把 "~" replace掉

**Comment by Silence-dream** [comment]
> vite 配置一下alias就能解决了， 把 "~" replace掉

<img width="718" alt="image" src="https://github.com/alibaba/formily/assets/42824008/cce6bb9a-14fa-4299-a837-9c8f7e65fdf3">

感谢大佬解决了
