### ISSUE TITLE
[Bug Report] antd radio无法选中

### ISSUE THREAD

**Issue by kaoding** [alibaba/uform#3866]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily/discussions/3859)

### Steps to reproduce
radio无法选中

### What is expected?
radio无法选中

### What is actually happening?
radio无法选中

### Package
@formily/core@2.2.25

---

radio无法选中

**Comment by zhangzhonghe** [comment]
同样遇到这个问题，怀疑和这个 #3856 有关。

**Comment by yiyunwan** [comment]
就是那个问题导致的，他判断了target和currentTarget

**Comment by yiyunwan** [comment]
我看已经修复了，得发新版本，建议先回退24

**Comment by yiyunwan** [comment]
新版本已修复
