### ISSUE TITLE
[Feature Request] /docs下面的组件，有一些在src下面找不到 #2

### ISSUE THREAD

**Issue by simplast** [alibaba/uform#3874]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如ArrayCard，在dscs下面有文档，但是实际包里面没有组件的代码

### What does the proposed API look like?
docs/components/ArrayCards.md

是这个项目哈：https://github.com/formilyjs/antd-mobile

**Comment by hchlq** [comment]
我看是有的，你是不是看漏了呢

这里：https://github.com/formilyjs/antd-mobile/tree/master/packages/components/src

**Comment by hchlq** [comment]
应该是没开发完，源文件虽然有，但是官方文档也没有暴露出来，感觉还好。

**Comment by simplast** [comment]
> 应该是没开发完，源文件虽然有，但是官方文档也没有暴露出来，感觉还好。

哦哦，请问下build的时候遇到rpt2: options error TS6053: File '/antd-mobile/packages/renderer/src/index.ts' not found. 是为啥，文件命名是存在的

**Comment by hchlq** [comment]
可以直接去 https://github.com/formilyjs/antd-mobile 这个仓库提 issue 就可以了哈
