### ISSUE TITLE
[Bug Report] CodeSandbox Error

### ISSUE THREAD

**Issue by zhangmo8** [alibaba/uform#3877]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-ben-rlvgqg?file=/App.tsx)

### Steps to reproduce
Just link the URL.

### What is actually happening?
Maybe it's the CodeSandbox Error. 

### Package
@formily/antd-mobile@1.0.0

---

**Comment by hchlq** [comment]
初步判断是 @formily/antd-mobile 和 antd-mobile 版本兼容问题
