### ISSUE TITLE
[Bug Report] field设置setComponentProps后组件未渲染

### ISSUE THREAD

**Issue by 007sair** [alibaba/uform#3899]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-christian-h3d5x5?file=/App.tsx)

### Steps to reproduce
点击 设置“A1”的标题为“A1(新)”   按钮

### What is expected?
点击按钮 设置“A1”的标题为“A1(新)”  后A1的标题发生变化

### What is actually happening?
点击按钮 设置“A1”的标题为“A1(新)”  后A1的标题未发生变化

### Package
@formily/antd-v5@1.1.0

---

**Comment by hchlq** [comment]
原因是 antd 中的组件在合并 componentProps 的时候失去了依赖收集能力
