### ISSUE TITLE
[Feature Request] ArrayTable 自增表格是否支持多级表头

### ISSUE THREAD

**Issue by zoley** [alibaba/uform#3900]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
![](https://pic.imgdb.cn/item/64acb8e01ddac507cc22e12c.jpg)

类似上图；

尝试过在schema层用“x-component-props”里的children 来处理，但数据就没办法编辑了。

再 用 items 嵌套，结果也不生效。

![](https://pic.imgdb.cn/item/64acba591ddac507cc29254b.jpg)

### What does the proposed API look like?
能在配置项里的简单设置父级表头，或在schema里支持也行

**Comment by janryWang** [comment]
建议写自定义组件吧，目前暂时不考虑支持这种能力
