### ISSUE TITLE
[Bug Report] ArrayItems 当处于字符串数组模式时，required校验逻辑异常

### ISSUE THREAD

**Issue by Landon-CN** [alibaba/uform#3910]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-vaughan-y4gllg?file=/App.tsx)

### Steps to reproduce
第一步： 点击提交触发校验失败，提示必填
![image](https://github.com/alibaba/formily/assets/12167648/b295d5df-0013-4a2f-992f-620fe5958c00)

第二步： 添加一条，并且在输入框里输入值
![image](https://github.com/alibaba/formily/assets/12167648/306149cb-c508-4305-ba28-5707a9c7078a)

第三步：点击提交，校验结果更新
![image](https://github.com/alibaba/formily/assets/12167648/273927ab-5486-483c-a627-101329937f6e)

### What is expected?
1、字段校验自动触发，更新校验结果

### What is actually happening?
校验结果是历史结果，未触发更新，需要点击提交手动更新

### Package
@formily/core@2.2.27

---

初步debug判断是string_array.0的字段值更新时没有触发父级string_array的校验导致的

**Comment by hchlq** [comment]
原因：字符串数组为空（undefined 或 null）时，required 校验不通过

解决方案：
1. formily 更改 required 的数据校验规则【影响可能较大】

2. 通过其他校验规则，比如使用 min

```ts
 'x-validator': {
      min: 1,
  },
```
