### ISSUE TITLE
[Bug Report] 使用@formily/antd引出的Upload组件, 进行二次封装, 文件列表不展示

### ISSUE THREAD

**Issue by HAjiMa666** [alibaba/uform#3912]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/holy-star-6pshtl?file=/src/App.js)

### Steps to reproduce
点击文件上传

### What is expected?
展示文件列表

### What is actually happening?
没展示文件列表

### Package
@formily/antd@2.2.27

---

**Comment by janryWang** [comment]
https://antd.formilyjs.org/components/upload 这文档里不是有二次封装的例子吗？

**Comment by HAjiMa666** [comment]
> https://antd.formilyjs.org/components/upload 这文档里不是有二次封装的例子吗？

我是基于 formily提供的upload组件进行二次封装的, 不是通过antd的, 他就是不展示文件列表, 你可以看下我提供的demo.

**Comment by janryWang** [comment]
我给的文档例子也是 formily 提供的 Upload 二次封装例子啊
