### ISSUE TITLE
[Bug Report] 使用@formily/antd-v5，ArrayTable在暗黑模式下，样式出现bug

### ISSUE THREAD

**Issue by mercyscope** [alibaba/uform#3919]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-sky-fnk3m4?file=/App.tsx)

### Steps to reproduce
配置暗黑模式，ArrayTable样式异常

### What is expected?
能正常显示样式

### What is actually happening?
td的颜色还是白色
![Snipaste_2023-07-28_15-52-02](https://github.com/alibaba/formily/assets/25003730/d0c7447d-02eb-4443-b770-35efdf92066e)

### Package
@formily/antd-v5@2.2.27

---

**Comment by yiyunwan** [comment]
已修复 https://github.com/formilyjs/antd/pull/25
