### ISSUE TITLE
[Bug Report] array 元素过多时删除较慢

### ISSUE THREAD

**Issue by yiyunwan** [alibaba/uform#3968]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on Stackblitz](https://stackblitz.com/edit/vitejs-vite-npfgdf?file=vite.config.ts,src%2Fmain.tsx,src%2FApp.tsx&terminal=dev)

### Steps to reproduce
点击删除，很明显的慢

### What is expected?
删除较快，能100ms内删除成功

### What is actually happening?
元素越多删除越慢

### Package
@formily/antd@2.2.29

---

删除最后数据较快，删除开始数据很慢

**Comment by janryWang** [comment]
无解，数据量大了删除就是很慢，我还以为是分页切换的次数切换很多次之后删除会变慢
