### ISSUE TITLE
[Bug Report] antd-v5 ArrayTable 条目拖曳至表格外后索引为NaN

### ISSUE THREAD

**Issue by tommytsim** [alibaba/uform#3971]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2pqvjx)

### Steps to reproduce
1. 使用文档的[Markup Schema 案例](https://antd5.formilyjs.org/zh-CN/components/array-table#markup-schema-%E6%A1%88%E4%BE%8B)
2. 新增条目
3. 提交表格
4. 校验器提示a2 a3为必填
5. 把条目拖曳至表格外才松开
6. 校验器提示消失
7. 填写a2 a3
8. 再次提交表格

### What is expected?
1. 拖曳后保留校验器提示
2. 填写后能够成功提交表格

### What is actually happening?
从console看见校验错误且条目索引为NaN

### Package
@formily/antd-v5@1.1.1

---

1. Dnd kit 里 `onDragEnd` 的 `DragEndEvent.over` 在拖曳至容器外时为null
2. `SortableContainer` 把 `over?.id` 减1 变成 `NaN`
3. `ArrayTable` 里的组件在 `onDragEnd` 调用 `ArrayField.move(oldIndex, newIndex /* NaN */);`

**Comment by yiyunwan** [comment]
已修复 https://github.com/formilyjs/antd/pull/26
