### ISSUE TITLE
不同Field 切换，如果字段名称name相同，会出现在渲染UI不对

### ISSUE THREAD

**Issue by boqiaok** [alibaba/uform#399]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
        当切换 2个 SchemaForm 的时候， 如果出现 Field 的 name  相同，但是Field type 不相同的情况下，会出现 渲染相同 Field 组件。
        也就是 在 this.fields 缓存里 Field 组件。在下一次 name相同的时候直接拿来用了。但可能有如下情况  Input  和 Number  组件 有不同的类型默认值default，所以当切换Input 和 Number 组件，设置他们的默认值的时候，渲染的是缓存的Field组件。
        可以重新传递下 元数据options.props 给  field.initialize吗？

2. Describe your issue:

  - Which versions of UForm?
 "@uform/antd": "^0.4.3"

路径： /uform/packages/core/src   

```js
public registerField(name: string, options: IFieldOptions) {
  const value = this.getValue(name)
  const initialValue = this.getInitialValue(name, options.path)
  const field = this.fields[name]
  if (field) {
    field.initialize({
      path: options.path,
      onChange: options.onChange,
      value,
      initialValue,
      props: options.props //  <----------------
    } as IFieldOptions)
    this.asyncUpdate(() => {
      this.updateFieldStateFromBuffer(field)
    })
  } else {
    this.fields[name] = new Field(this, {
      name,
      value,
      path: options.path,
      initialValue,
      props: this.traverse ? this.traverse(options.props) : options.props
    })
    const field = this.fields[name]
    if (options.onChange) {
      this.asyncUpdate(() => {
        this.updateFieldStateFromBuffer(field)
        field.onChange(options.onChange)
      })
      this.dispatchEffect('onFieldChange', field.publishState())
    }
    this.fieldSize++
  }
  return this.fields[name]
}
```
.

**Comment by janryWang** [comment]
给个codesandbox？方便复现问题

**Comment by boqiaok** [comment]
https://codesandbox.io/s/currying-tdd-s6pbj
切换SchemaForm 会发现 schema变化了，但是渲染出来的UI 未变化

**Comment by janryWang** [comment]
> https://codesandbox.io/s/currying-tdd-s6pbj
> 切换SchemaForm 会发现 schema变化了，但是渲染出来的UI 未变化

看了你的例子，貌似在切换schema:boolean和schema:string的时候，组件就会改变了，并没有复现问题

**Comment by boqiaok** [comment]
schema: boolean  > schema: number >   schema: string >  schema: boolean

schema: string >  schema: boolean  这里会出现问题 也就是 

[
![switch2](https://user-images.githubusercontent.com/15731814/68913259-ae0f9600-0795-11ea-8ae5-7fba8978928a.gif)
](url)

**Comment by janryWang** [comment]
![image](https://user-images.githubusercontent.com/4060976/68913478-60dff400-0796-11ea-968a-cc6baebf6da7.png)
建议先这样处理吧，这个涉及内核大改造，我在v1版本上试试有没有这个问题

**Comment by boqiaok** [comment]
好的，辛苦了
