### ISSUE TITLE
调用submit方法，在控制台上会打印一个错误信息，无法进行catch

### ISSUE THREAD

**Issue by lianyzhou** [alibaba/uform#40]
如图所示，点击提交时，会产生一个无法catch到的exception
![image](https://user-images.githubusercontent.com/6295633/57257599-80ca8880-708c-11e9-8706-9dd1a486e015.png)
![image](https://user-images.githubusercontent.com/6295633/57257650-a061b100-708c-11e9-9355-725a077d802e.png)
![image](https://user-images.githubusercontent.com/6295633/57257679-b4a5ae00-708c-11e9-809b-a23679dcfbf4.png)

是否可以去掉此exception或者配置成SchemaForm的一个选项，throwException: true/false

**Comment by janryWang** [comment]
这个问题先hold住吧，不阻塞应用，我现在正在思考uform的调试模式和生产模式的差异化控制。是一个整体型的方案，单纯通过一个throwException来解决问题太过于单点。

**Comment by lianyzhou** [comment]
已经找到解决办法了，可以在await模式调用submit函数和validate函数时，加try catch进行解决。
