### ISSUE TITLE
[Bug Report] JSX 模式下， 支持改变字段属性生效

### ISSUE THREAD

**Issue by StarHosea** [alibaba/uform#4013]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jolly-artem-nm7qjy?file=/App.tsx)

### Steps to reproduce
点击切换模式，表单项应该切换到查看模式。查看模式下，字段不可编辑，并且 decorator 使用 FormItem2

### What is expected?
点击切换模式，表单项应该切换到查看模式。查看模式下，字段不可编辑，并且 decorator 使用 FormItem2

### What is actually happening?
点击切换模式按钮后，页面没有任何变化

### Package
@formily/core@2.3.0

---

**Comment by janryWang** [comment]
这是受控更新的老问题了，基于文档推荐的方式来即可 https://formilyjs.org/zh-CN/guide/advanced/controlled
