### ISSUE TITLE
[Bug Report] Antd v5 Collapse warning

### ISSUE THREAD

**Issue by jymsy** [alibaba/uform#4016]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fsv359?file=/App.tsx)

### Steps to reproduce
open console and there is an warning

### What is expected?
no warning

### What is actually happening?
Warning: `children` will be removed in next major version. Please use `items` instead. 

### Package
@formily/antd-v5@1.1.7

---

**Comment by zzhcch** [comment]
We need this update, please

**Comment by jymsy** [comment]
@janryWang please review this pr https://github.com/formilyjs/antd/pull/31
