### ISSUE TITLE
[Bug Report] antd v5 box-shadow error

### ISSUE THREAD

**Issue by jymsy** [alibaba/uform#4019]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/62drtw)

### Steps to reproduce
Making the Date picker error active, and the box-shadow value is wrong
![image](https://github.com/alibaba/formily/assets/2777671/ae1a33d6-7250-4027-84f7-8aa5beb74949)

### What is expected?
box-shadow value is right

### What is actually happening?
 box-shadow value is wrong

### Package
@formily/antd-v5@1.1.7

---

**Comment by zzhcch** [comment]
We are happy to give this MQ to fix this.
