### ISSUE TITLE
请问有能够解析schame，并且获取全部表单name的api嘛

### ISSUE THREAD

**Issue by dlspacezero** [alibaba/uform#4033]
### Discussed in https://github.com/alibaba/formily/discussions/4032

<div type='discussions-op-text'>

<sup>Originally posted by **dlspacezero** November 23, 2023</sup>
业务需要获取到schema渲染出来的表单name，并且保存到服务端上，请问有没有相关api，如果没有，能否提供一个思路</div>

**Comment by fwgood** [comment]
getFormGraph

**Comment by purple-force** [comment]
> getFormGraph

{
    "": {
        "displayName": "Form",
        "id": "6cqvo0uuiwd",
        "initialized": true,
        "submitting": false,
        "validating": false,
        "loading": false,
        "modified": false,
        "mounted": false,
        "unmounted": false,
        "display": "visible",
        "pattern": "editable",
        "values": {},
        "initialValues": {},
        "valid": true,
        "invalid": false,
        "errors": [],
        "warnings": [],
        "successes": [],
        "hidden": false,
        "visible": true,
        "editable": true,
        "readOnly": false,
        "readPretty": false,
        "disabled": false
    }
}
我试了下，返回的是这些，没有返回表单的所有字段

schema 为
{
  form: { labelCol: 6, wrapperCol: 12 },
  schema: {
    type: 'object',
    properties: {
      zk9anpv4y72: {
        type: 'void',
        'x-component': 'FormGrid',
        'x-component-props': { maxColumns: 3 },
        'x-designable-id': 'zk9anpv4y72',
        properties: {
          lr9bvzja7nv: {
            type: 'void',
            'x-component': 'FormGrid.GridColumn',
            'x-designable-id': 'lr9bvzja7nv',
            properties: {
              tsae81g20lo: {
                type: 'string',
                title: '姓名',
                'x-decorator': 'FormItem',
                'x-component': 'Input',
                'x-component-props': { placeholder: '请输入' },
                name: 'tsae81g20lo',
                'x-validator': [],
                'x-decorator-props': {},
                'x-designable-id': 'jww2qre5nls',
                'x-index': 0,
              },
            },
            'x-index': 0,
          },
          wxp4cehpv8d: {
            type: 'void',
            'x-component': 'FormGrid.GridColumn',
            'x-designable-id': 'wxp4cehpv8d',
            properties: {
              inzfgz1rm4l: {
                type: 'string',
                title: '性别',
                'x-decorator': 'FormItem',
                'x-component': 'Input',
                'x-component-props': { placeholder: '请输入' },
                name: 'inzfgz1rm4l',
                'x-validator': [],
                'x-decorator-props': {},
                'x-designable-id': '0p66t5ajpxd',
                'x-index': 0,
              },
            },
            'x-index': 1,
          },
          '1vea5llpjsf': {
            type: 'void',
            'x-component': 'FormGrid.GridColumn',
            'x-designable-id': '1vea5llpjsf',
            properties: {
              p7rrsk4r26v: {
                type: 'string',
                title: '年龄',
                'x-decorator': 'FormItem',
                'x-component': 'NumberPicker',
                'x-component-props': { placeholder: '请输入' },
                name: 'p7rrsk4r26v',
                'x-validator': [],
                'x-decorator-props': {},
                'x-designable-id': 'u79lzeoch4f',
                'x-index': 0,
              },
            },
            'x-index': 2,
          },
          '7z0v6izpw8c': {
            type: 'void',
            'x-component': 'FormGrid.GridColumn',
            'x-component-props': {},
            'x-designable-id': '7z0v6izpw8c',
            properties: {
              qfemujhqqdu: {
                type: 'string',
                title: '描述',
                'x-decorator': 'FormItem',
                'x-component': 'Input',
                'x-component-props': { placeholder: '请输入' },
                name: 'qfemujhqqdu',
                'x-validator': [],
                'x-decorator-props': {},
                'x-designable-id': 'z41bzj9hszt',
                'x-index': 0,
              },
            },
            'x-index': 3,
          },
        },
        'x-index': 0,
      },
    },
    'x-designable-id': '31l822zz3sd',
  },
}

**Comment by purple-force** [comment]
> getFormGraph
通过 getFormGraph 获得的值的key，比实际的表单字段 name 多了一些前缀（Address），这些前缀去掉之后才是真正的name。这些前缀怎么判定？

**Comment by fwgood** [comment]
> > getFormGraph
> > 通过 getFormGraph 获得的值的key，比实际的表单字段 name 多了一些前缀（Address），这些前缀去掉之后才是真正的name。这些前缀怎么判定？

你如果是嵌套的字段，那肯定会拼上父级的name呀，不然怎么区分层级呢？

**Comment by purple-force** [comment]
> > > getFormGraph
> > > 通过 getFormGraph 获得的值的key，比实际的表单字段 name 多了一些前缀（Address），这些前缀去掉之后才是真正的name。这些前缀怎么判定？
> 
> 你如果是嵌套的字段，那肯定会拼上父级的name呀，不然怎么区分层级呢？

并不是嵌套的字段。getFormGraph 会把VoidField，布局等组件的 key 一股脑都拼上去，而 form.values 的 key 只有表单项相关的name。
