### ISSUE TITLE
[Feature Request] 希望 json-schema 中的 x-validator 判断增加值是否在 x-compile-omitted 中

### ISSUE THREAD

**Issue by zynyy** [alibaba/uform#4067]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为目前x-validator需要配置一些变量而这些变量在转换中不存在又希望变量使用的符号`{{}}`保持一致。但是目前 x-validator 无法在 x-compile-omitted 配置中生效
所以希望能支持忽视compile
https://github.com/alibaba/formily/blob/ec5485f4612692c33d3a4de71a40ae45adce5bcc/packages/json-schema/src/shared.ts#L103 中增加判断
```
  if (schema['x-validator'] !== undefined) {
    visitor(schema['x-validator'], ['x-validator'], schema['x-compile-omitted']?.includes('x-validator') );
  }
```

### What does the proposed API look like?
x-compile-omitted 能够对 x-validator 生效

**Comment by janryWang** [comment]
欢迎 PR 哈

**Comment by zynyy** [comment]
@janryWang 一般多久mr。流程是怎么样的很少用这方面不是很懂
