### ISSUE TITLE
[Bug Report] 调用ArrayItems.Remove后$index没有更新

### ISSUE THREAD

**Issue by wy-luke** [alibaba/uform#4100]
- [x]  I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/formily-index-qnp2v6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt8grm8e00073b6eygtltacq%2522%252C%2522sizes%2522%253A%255B71.00593827254887%252C28.994061727451125%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt8grm8e00023b6ezwfnbuhj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt8grm8e00043b6eu27zjtg2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt8grm8e00063b6ewj9a2hki%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.890111004663225%252C44.109888995336775%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt8grm8e00023b6ezwfnbuhj%2522%253A%257B%2522id%2522%253A%2522clt8grm8e00023b6ezwfnbuhj%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt8grm8e00063b6ewj9a2hki%2522%253A%257B%2522id%2522%253A%2522clt8grm8e00063b6ewj9a2hki%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt8grm8e00053b6ew3chvr2w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clt8grm8e00053b6ew3chvr2w%2522%257D%252C%2522clt8grm8e00043b6eu27zjtg2%2522%253A%257B%2522id%2522%253A%2522clt8grm8e00043b6eu27zjtg2%2522%252C%2522activeTabId%2522%253A%2522clt8grm8e00033b6eswuloxkd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt8grm8e00033b6eswuloxkd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clt8grw2l00573b6e7rijzcuv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clt8grwac00mhdjip3dqwg9ud%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
1. 添加两个条目
2. 点击两个编辑按钮，分别会打印出index为0和1
3. 删除第一个元素，然后再点击编辑按钮，打印出来的还是1，而不是0，$index没有更新。但是$self.index是正确的。

### What is expected?
$index随着真实index更新

### What is actually happening?
$index只有初始化时进行赋值，没有再更新，闭包了吧

### Package
@formily/antd-v5@2.3.1

---

**Comment by wy-luke** [comment]
P.S. 原有的CodeSandbox的模版都失效了，加载不出来

**Comment by charlzyx** [comment]
用 $self.index , 这个是响应式的

**Comment by wy-luke** [comment]
> 用 $self.index , 这个是响应式的

后面也是用了这个，既然 $index 设计如此，我就关了 ISSUE 了
