### ISSUE TITLE
[Bug Report] @formily/antdv的about阐述错误，误导了大家

### ISSUE THREAD

**Issue by leoven-chan** [alibaba/uform#4154]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/formilyjs/antdv)

### Steps to reproduce
About

Formily Ant Design Vue Adaptor(Vue2)

### What is expected?
About

Formily Ant Design Vue Adaptor(Vue3)

### What is actually happening?
About

Formily Ant Design Vue Adaptor(Vue2)

@formily/antdv 最新版本支持 vue3，antdv v4，但是github上仍然写着 vue2，误导了我们这些开发使用者

### Package
@formily/antdv@2.3.1

---

**Comment by erweixin** [comment]
辛苦提个 PR 吧。

**Comment by like0413** [comment]
不支持啊，我安装了一下还报这个呢
![image](https://github.com/alibaba/formily/assets/48686374/607431f0-a694-4696-a00f-b9dfe22179b9)

**Comment by yiyunwan** [comment]
升级后文档部署有点问题，使用vue2的话下载1.x吧，不过1.x配合2.7使用有点问题
