### ISSUE TITLE
[Bug Report] 使用 field.setComponentProps更新后，组件内 onChange 会导致 props.xxx一直变更

### ISSUE THREAD

**Issue by vladimirdh** [alibaba/uform#4169]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/strange-dew-336fjx?file=%2Fsrc%2FApp.js%3A13%2C10)

### Steps to reproduce
1. 通过 field.setComponentProps更新 props 字段 key2
2. 组件内通过useEffect(()=>{  onChange(...)  }, [key2])的形式去消费 key2
3. 更新了自身的 value 后，props.key2 的引用地址一直在变更，导致 useEffect 一直会被触发

### What is expected?
不重新触发更新

### What is actually happening?
props.key2 的引用地址一直在变更，导致 useEffect 一直会被触发

### Package
@formily/react@2.3.1

---

**Comment by 97vack** [comment]
可以考虑使用React Form Simple 
文档：[react-form-simple](https://easy-form.github.io/react-form-simple/zh-CN)
它提供了一套全面的解决方案，涵盖了数据绑定、验证规则、错误处理和 UI 更新等多个方面。其设计理念是简化开发流程，提升开发效率，并为开发者提供高度灵活和可扩展的工具。并高效构建复杂的表单应用。

**Comment by vladimirdh** [comment]
发现重复了 https://github.com/alibaba/formily/issues/4097
