### ISSUE TITLE
[Bug Report] schema 重渲染组件

### ISSUE THREAD

**Issue by Atw-Lee** [alibaba/uform#4206]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
很抱歉，reproduction没有写。

我的场景如下：

使用的JSON Schema模式，基于antdv自定义组件A、B

A、B组件存在依赖关系，我希望当A组件@change的时候，重新渲染B组件（想在onMounted中执行某个函数），其实我最开始的想法是通过ref进行调用，当我查找issues后发现不建议使用ref。

我继续查看文档，找到了联动逻辑相关的[文档](https://formilyjs.org/zh-CN/guide/advanced/linkages)及demo，以及下文的管理业务逻辑。

但是我不确定的是能否“重渲染”B组件，想咨询一下，（偷个懒先不写demo验证了）^_^

期待您的回复

### What is expected?
no

### What is actually happening?
no

### Package
@formily/vue@2.3.2

---

**Comment by Atw-Lee** [comment]
好像不可以，我该怎么实现我的需求呢。

**Comment by yanhao98** [comment]
https://www.npmjs.com/package/mitt

用这个通知吧，想干啥干啥。
