### ISSUE TITLE
动态设置Field

### ISSUE THREAD

**Issue by xwchris** [alibaba/uform#427]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
 

2. Describe your issue:

  - What is the current behavior?
使用
```js
{
                    !!parent?.id && <Field title="所属业务组" name="belongTo" enum={[{ value: parent.id, label: parent.name }]} default={parent.id} editable={false} />
                }
```
会报错
```
The schema field's component is not found, or field's schema is not defined.
```
  - What is the expected behavior?
根据判断的值动态显示Field
  - Which versions of UForm?
@uform/antd@^0.4.4
  - Did this work in previous versions of UForm?
不了解
3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
没有指定type
