### ISSUE TITLE
setFieldState里面不能设置errors

### ISSUE THREAD

**Issue by wangxiaofeid** [alibaba/uform#428]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug

2. Describe your issue:

  - What is the current behavior?
使用数组输入时候

```
<Field
    required
    type="array"
    name="edgeMaker"
    x-props={{
        renderMoveDown: () => null,
        renderMoveUp: () => null,
        operationsWidth: 0,
    }}
>
    <Field type="object">
        <FormLayout labelCol={8} wrapperCol={14}>
            <FormItemGrid>
                <Field
                    required
                    title="关系标识"
                    name="label"
                    type="string"
                />
                <Field
                    required
                    title="关系名称"
                    name="labelName"
                    type="string"
                />
            </FormItemGrid>
        </FormLayout>
    </Field>
</Field>
```

操作是：添加一组输入-->点提交触发校验-->添加的那组检验不通过，提示是必填字段-->再添加一组字段-->删除第一组输入-->第一组的错误信息展示在了刚才第一组的位置
而且

```
setFieldState(
    FormPath.match(`elements.*.type`),
    state => {
        state.errors = [];
    }
);
```

这样不能清除错误
  - What is the expected behavior?
错误信息不要串了；或者setFieldState支持清除错误信息
  - Which versions of UForm?
"@uform/antd": "0.4.4",
  - Did this work in previous versions of UForm?
不清楚
3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
给个codesandbox链接吧
