### ISSUE TITLE
年份选择器不生效

### ISSUE THREAD

**Issue by g770728y** [alibaba/uform#43]
官方页面https://alibaba.github.io/uform/#/YZCyCk/7lC3CXsVhB
antd > 简单场景 页面:
    年份选择器 可以展开, 但选择后无任何效果 ( 下拉框也不会关闭 )

我的本地练习, 也有同样问题.

( 注: Fusion next 对应功能是正确的. )

**Comment by janryWang** [comment]
重复了 https://github.com/alibaba/uform/issues/33
