### ISSUE TITLE
rules.ts maximum

### ISSUE THREAD

**Issue by wsw** [alibaba/uform#453]
maximum(value: any, rule: ValidateDescription) {
    return Number(value) > Number(rule.maximum) ? getMessage('maximum') : ''
},

这段代码的getMessage为啥不是getRuleMessage呀？

**Comment by janryWang** [comment]
有什么问题吗

**Comment by wsw** [comment]
不能显示自定义message了啊

**Comment by janryWang** [comment]
好吧，以后麻烦问题描述清楚一些吧，一定要带上codesandbox地址，不然看着无头无尾的，只能先close
