### ISSUE TITLE
select  input 的 type 约定建议

### ISSUE THREAD

**Issue by lingxufeng2014** [alibaba/uform#47]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Discussion

2. Describe your issue:
- input 和 select 的type ，我感觉语义多少都有问题，现在都叫做 string，然后通过 enum 来识别的方法值得商榷：一个是内容本身就不一定是 string，另一个是带来了使用上的不确定性。
- 顺带报一个 bug：antd 的 select，点击时会有 warning，官方示例都能看得到。

**Comment by janryWang** [comment]
1. 目前不止是string支持enum，number，boolean也支持，只要配了enum就会展示成select形态，这个语义并不存在啥问题吧，因为后端返回出来的json-schema形式的基本数据类型就是只有string/number/boolean。
2. 这个其实应算做是antd的bug。具体看看 https://github.com/alibaba/uform/issues/26
