### ISSUE TITLE
API文档下有一处错误。

### ISSUE THREAD

**Issue by whj1995** [alibaba/uform#48]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:

https://alibaba.github.io/uform/#/97UlUl/RbFYF9CvHx

该文档下的用例
``` js
setTimeout(() => {
  aa.changeValue(456) // 此处报错没有这个这个方法
  setTimeout(() => {
    form.submit()
  }, 1000)
}, 500)
```

是不是应该改为
``` js
  form.setValue('aa', 456);
```

**Comment by janryWang** [comment]
感谢反馈，要不您提一个PR？
