### ISSUE TITLE
core.reset()为什么是返回验证结果？

### ISSUE THREAD

**Issue by jincdream** [alibaba/uform#486]
https://github.com/alibaba/uform/blob/335552d769fe6bccb2f12ec145bcf6c0c31760f6/packages/core/src/index.ts#L725

这个是出于什么考虑？
reset不应该是给到initialValues么

**Comment by janryWang** [comment]
因为是重置自动校验的话，会返回校验结果，这个是正确的方式，至于说返回initialValues，这个通过getFormState就能取到了
