### ISSUE TITLE
@uform/antd和@uform/next(antd)有什么区别吗

### ISSUE THREAD

**Issue by Sayid1** [alibaba/uform#487]
@uform/antd和@uform/next(antd)有什么区别吗

**Comment by janryWang** [comment]
后者只是文档上说明两个包API基本一致，如果还没用过0.x的用户，建议都看1.x的文档吧https://uform-next.netlify.com

**Comment by janryWang** [comment]
后者只是文档上说明两个包API基本一致，如果还没用过0.x的用户，建议都看1.x的文档吧https://uform-next.netlify.com
