### ISSUE TITLE
使用ON_FORM_INIT设置的visible=false，ui会隐藏，但数据会print出来

### ISSUE THREAD

**Issue by zp2359** [alibaba/uform#491]
案例：https://github.com/alibaba/uform/blob/master/packages/react/README.zh-cn.md#%E5%A4%8D%E6%9D%82%E8%81%94%E5%8A%A8

![image](https://user-images.githubusercontent.com/6220430/70496868-34788700-1b4c-11ea-9edb-24c82fa6cf4e.png)

**Comment by janryWang** [comment]
复现步骤麻烦给一下，目前没法复现

**Comment by zp2359** [comment]
> 复现步骤麻烦给一下，目前没法复现

https://codesandbox.io/s/eager-hermann-5nk49
经这个案例，修改问题描述如下：field的visible必须先设置为true，再设置为false，数据才会隐藏。
