### ISSUE TITLE
未来一年内有支持vue的计划吗？

### ISSUE THREAD

**Issue by wzw007** [alibaba/uform#496]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Question
2. Describe your issue:
  - uform   未来一年内有支持vue的计划吗？ 
3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by jincdream** [comment]
目前暂时没有计划？ 但可以帮助社区开发vue版本
