### ISSUE TITLE
value 为空字符串时处理错误

### ISSUE THREAD

**Issue by foolyoghurt** [alibaba/uform#5]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug

2. radio 组件中，value 设置为空字符串的情况下，`{ label: "无", value: "" }`, 向 SchemaForm 传入 value 中对应字段值也为空字符串 `value={{ mode: "" }}` ，这时候没有选中对应的 radio，在如下 demo 中，「无」这一项应该是被选中的

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen

https://codesandbox.io/s/91177rqzzw
.

**Comment by janryWang** [comment]
这种场景能否推动后端支持value:"ALL"之类的枚举值，空值的话太容易出现边界问题

**Comment by foolyoghurt** [comment]
> 这种场景能否推动后端支持value:"ALL"之类的枚举值，空值的话太容易出现边界问题

确实容易出现边界问题，但是 UForm 是一个基础组件，使用广泛了，总会遇到这种 case，不可能每次都能推动去使用 value: ALL 这样的方式解决，所以长期来讲，我觉得 UForm 还是需要解决这个问题的

**Comment by janryWang** [comment]
咱们可以考虑一个场景：
Input为空字符串是属于有值还是没值，Select为空字符串是属于有值还是没值，如果两个组件一个的定义是有值，一个定义是没值，那这个空字符串定义就是有歧义的

**Comment by foolyoghurt** [comment]
> 咱们可以考虑一个场景：
> Input为空字符串是属于有值还是没值，Select为空字符串是属于有值还是没值，如果两个组件一个的定义是有值，一个定义是没值，那这个空字符串定义就是有歧义的

嗯，有道理，确实容易产生歧义，我这块先自己改成非空的

**Comment by janryWang** [comment]
嗯嗯，那就先close掉了哈
