### ISSUE TITLE
connect 方法在 @uform/react 中不存在

### ISSUE THREAD

**Issue by shengliangli** [alibaba/uform#500]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance
 Bug

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of UForm?
  - Did this work in previous versions of UForm?
@uform/react^1.0.0-alpha.8
3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

导出 @uform/react 中的 connect ，得到的是 null

从 @uform/antd 中导出 connect，是对的

官方文档中写的 connect 是从 @uform/react 导出，是文档写错了，还是新的版本把 connect 换了地方？

**Comment by janryWang** [comment]
你看的是0.x的文档，要看1.x的文档，1.x的包名，@uform/react现在叫做@uform/react-schema-renderer
