### ISSUE TITLE
actions.validate 无法获取错误信息

### ISSUE THREAD

**Issue by shengliangli** [alibaba/uform#504]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance
Q
2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of UForm?
  - Did this work in previous versions of UForm?
1.x
3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.
https://codesandbox.io/s/uform-lizi-d6oth

如上代码，希望在自己的 button 组件中校验表单，按照官网的例子写的，但是不工作。请大佬帮看看，多谢

**Comment by janryWang** [comment]
校验失败会走到reject流程
