### ISSUE TITLE
@uform/antd的<SchemaForm colon={false} hideRequiredMark={false}>无效

### ISSUE THREAD

**Issue by zp2359** [alibaba/uform#514]
见：https://codesandbox.io/s/serene-napier-flwuu

colon：不显示label中的冒号
hideRequiredMark：隐藏label中的符号*

**Comment by janryWang** [comment]
Field维度不能直接传组件属性，使用x-component-props

**Comment by zp2359** [comment]
尝试了，只有 <SchemaForm colon={false} /> 有效，其他均无效:

- x-props
- x-component-props

- 加在SchemaForm
- 加在Field

- hideRequireMark

如果是下面这样，也无效
> <SchemaForm colon={false} ><FormItemGrid><Field>

见:https://codesandbox.io/s/lingering-violet-5pmjy

**Comment by janryWang** [comment]
FormItem的属性，只能配在x-props上，Form的属性配在SchemaForm上就行了

**Comment by zp2359** [comment]
- 配置x-props，x-components-props无效，见：https://codesandbox.io/s/friendly-gauss-xfjbd

- 如果使用了<Field type="object">，无效，见：https://codesandbox.io/s/holy-sea-rbpcu

- hideRequiredMark无效，见：https://codesandbox.io/s/hopeful-diffie-o1e5i

**Comment by janryWang** [comment]
我看隐藏冒号是生效了的，你说的是隐藏必填星号吧

**Comment by zp2359** [comment]
隐藏冒号，在使用了`<Field type="object">`的情况下，不生效；
隐藏必填星号不生效。

**Comment by janryWang** [comment]
这个你可以先用原生的antd Form试试，有没有问题吧，讲道理uform都是完全透传所有属性给antd的，没有做任何过滤

**Comment by zp2359** [comment]
好的，有时间我也排查下，这边业务改造量太大，我得先处理业务。
