### ISSUE TITLE
inline 模式下 string 和 number 的宽度不一致。

### ISSUE THREAD

**Issue by alexPang6** [alibaba/uform#517]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
<FormLayout labelCol={10} wrapperCol={10} inline>
  <Field title="字符串" type="string" name="str1" />
  <Field title="数值型" type="number" name="num1" />
  <Field title="字符串" type="string" name="str2" />
  <Field title="数值型" type="number" name="num2" />
  <Field title="数值型" type="number" name="num3" />
</FormLayout>

2. Describe your issue:
  - What is the current behavior?
     string 和 number  label宽度和输入框宽度不一样，造成 不对齐

  - What is the expected behavior?
    两种类型的总宽度一致，我增加 minWidth 后，input宽度一样了，
    但是 string 的 label 还是很宽，造成不美观，
    所有类型都是 string 或 number 后就很整齐。

  - Which versions of UForm?
    "@uform/antd": "^0.4.4",
    "@uform/react": "^1.0.0-alpha.4",
    "antd": "^3.23.6",

  - Did this work in previous versions of UForm?
     每次使用 inline 都会有很多问题，antd Form inline 模式下，
     宽度变窄后，会自动换行，uForm 不会。

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
给个codesandbox

**Comment by alexPang6** [comment]
https://codesandbox.io/s/interesting-cloud-5qvbl 演示代码。

**Comment by alexPang6** [comment]
原来 inline 模式下，不需要用 labelCol, wrapperCol 。
