### ISSUE TITLE
文档 API 按照字母表排序

### ISSUE THREAD

**Issue by monkindey** [alibaba/uform#52]
摘取一个例子

| 属性名称 | 属性描述 | 属性类型 | 默认值 |
| --- | --- | --- | --- |
| type | 字段类型 | Object |  |
| name | 字段名称 | Object | {} |
| default | 默认值 | any |  |

可以变成

| 属性名称 | 属性描述 | 属性类型 | 默认值 |
| --- | --- | --- | --- |
| default | 默认值 | any |  |
| name | 字段名称 | Object | {} |
| type | 字段类型 | Object |  |

这样子方便查找, 之前为 antd 写了一个 [sort 脚本](https://github.com/ant-design/ant-design/blob/master/scripts/sort-api-table.js), 后面整合进去

**Comment by janryWang** [comment]
提个PR吧
