### ISSUE TITLE
新增的控件，在SchemaForm里绑定的onFieldChange$，不是动态的

### ISSUE THREAD

**Issue by zp2359** [alibaba/uform#527]
https://codesandbox.io/s/distracted-mahavira-vbzoz
期望：新增的数据也能绑定上onFieldChange$

**Comment by janryWang** [comment]
list.*.a去筛选

**Comment by zp2359** [comment]
demo写错了，更新了https://codesandbox.io/s/distracted-mahavira-vbzoz
加了list.*.a，还是不行

**Comment by zp2359** [comment]
加了`<Field type="object">`又可以了，奇怪了，我看一下我的业务场景代码...

**Comment by zp2359** [comment]
是一个业务code也错了，抱歉~
