### ISSUE TITLE
仓库不要太多 docs 编译后的 bundle.js

### ISSUE THREAD

**Issue by monkindey** [alibaba/uform#53]
https://github.com/alibaba/uform/tree/master/packages/docs

好多开源都只是做到 markdown 驱动渲染, 不会提交 docs/bundle.js 等等大包的文档代码。保持仓库干净和减少 .git 的大小。

**Comment by janryWang** [comment]
因为是采用静态文档方案，源码需要走npm cdn存放才能提升页面加载性能。所以就单独开了个npm package来存放bundle文件

**Comment by monkindey** [comment]
netlify + gatsby 驱动 ?

**Comment by janryWang** [comment]
这个调研一下吧，最好能搞一套线上自动部署的文档站，目前的还是比较简陋
