### ISSUE TITLE
uform中使用Tabs控件分页显示表单显示不正常

### ISSUE THREAD

**Issue by crashsol** [alibaba/uform#530]
表单内容太，需要分步骤展示，使用Tabs展示时，显示不正常，请老大指点，群里同仁说FormSlot，尝试多次未成功，请老大指点
https://codesandbox.io/s/sharp-resonance-qfgpz

**Comment by janryWang** [comment]
SchemaForm子节点不能直接使用UI组件的，需要封装成VirtualBox才能使用，不过封装成VNode还是有问题，因为你需要Tabs和TabPane通讯，这块可能需要context来通讯，不太容易处理，还有，Tabs这种交互不推荐用在表单上，特别是表单校验相关的，如果只是因为内容多，可以使用Card的收起展开功能
