### ISSUE TITLE
Field初始化时的业务与Field Change时的业务不同，目前生命周期不支持

### ISSUE THREAD

**Issue by zp2359** [alibaba/uform#534]
见：https://codesandbox.io/s/stupefied-turing-lkp3n

**Comment by janryWang** [comment]
onFieldValueChange，在初始化的时候是会触发的，因为一开始的值是undefined，从undefined变为有值，所以会触发，如果你希望只监听修改的动作，可以使用onFieldInputChange

**Comment by gxy01** [comment]
如果我一个field，不想初始化的时候触发，又想要别的值被set field的时候触发更新呢？
