### ISSUE TITLE
在使用表格录入多条的时候报错

### ISSUE THREAD

**Issue by 544751779** [alibaba/uform#538]
https://codesandbox.io/s/lz3du

Warning: Each record in table should have a unique `key` prop,or set `rowKey` to an unique primary key. 
Warning: [antd: Table] Each record in dataSource of table should have a unique `key` prop, or set `rowKey` of Table to an unique primary key, see https://u.ant.design/table-row-key

**Comment by janryWang** [comment]
看antd的文档，需要配置rowKey

**Comment by 544751779** [comment]
https://codesandbox.io/s/wizardly-knuth-hmok5?fontsize=14&hidenavigation=1&theme=dark

根据antd文档已经设置了 rowKey还是报错
    rowKey:"aa" ,

**Comment by janryWang** [comment]
你这个复现的是用的next的组件包啊，文档不一样

**Comment by 544751779** [comment]
@janryWang   不好意思 发错了 这个是 antd的 

https://codesandbox.io/s/festive-bash-7fi32?fontsize=14&hidenavigation=1&theme=dark

**Comment by 544751779** [comment]
以前是好的 升级了antd 和uform之后就这样了 如果有数据 也不能加载正确

**Comment by janryWang** [comment]
rowKey:({index})=>index这样写就行了

**Comment by 544751779** [comment]
@janryWang   感谢回复  

这样写还是报错呢

https://codesandbox.io/s/festive-bash-7fi32?fontsize=14&hidenavigation=1&theme=dark

**Comment by 544751779** [comment]
这样改下就好了  谢谢
`rowKey:(record:any,index:number )=>{
                                    return index
                                }`
