### ISSUE TITLE
SchemaForm[onValidateFailed] 返回的错误对象缺少 name属性

### ISSUE THREAD

**Issue by kpaxqin** [alibaba/uform#543]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

v1中errors为
```js
{
  messages: [],
  path: 'NO_NAME_FIELDS_$1.foo.bar'
}
```

v0.4中为

```js
{
  errors: [],
  name: 'foo.bar'
}
```

数据结构可以自行转换，但path多出来的NO_NAME_FIELDS_$1不利于进行路径判断等操作，期望返回和v0.4相同的name属性

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by quirkyshop** [comment]
#545 已修复
