### ISSUE TITLE
UForm文档覆盖不全不友好

### ISSUE THREAD

**Issue by xwchris** [alibaba/uform#544]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Enhancement

2. Describe your issue:
用uform一段时间了，用起来感觉还不错。唯一感到遗憾的是，api文档真的写的太少了，很多情况覆盖不到，或者不写，需要自己看代码摸索，太浪费时间了。真心希望uform能好好发展，先把文档建设下吧，拜托了

**Comment by janryWang** [comment]
UForm是开源方案，如果对文档有不满意的地方，欢迎一起共建，尽量做到有问题，大家一起解决，而不是以需求方，业务方的态度向开源方案索取。

**Comment by quirkyshop** [comment]
@xwchris 同学你好，想问下如果API文档要完善的话，你希望是怎么样的呢？哪一部分的缺失最影响日常开发？
