### ISSUE TITLE
在v0.4中，Field[type="array"]的default值在value=[] 时不应该生效

### ISSUE THREAD

**Issue by kpaxqin** [alibaba/uform#554]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

对Field[type="array"]，应该仅当值为undefined时才取default字段的值，实际情况是当值为[]空数组时就取了default。

如果一个字段设置default=[{foo: 1}]，且minItems=0，则保存数据空数组后反显结果永远是[{foo: 1}]
 
3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox

https://codesandbox.io/s/epic-elgamal-qg5em

**Comment by janryWang** [comment]
0.4内核机制的问题，这部分改起来较为困难，有可能还会引起其他副作用问题，推荐升级1.x
