### ISSUE TITLE
【讨论】保持字段组件和布局组件的API一致性

### ISSUE THREAD

**Issue by soulwu** [alibaba/uform#558]
业务中，比较常见的会使用布局组件组合一个或多个表单字段，并且在表单值变化时对布局组件整体进行联调（显隐、是否必选等）

对于普通的Field，设置必选的方式为`state.required = true`
而对于布局组件，设置必选需要使用`state.props["x-component-props"].required = true`（此处使用x-component-props应该是一个bug，理论上required应该是属于x-props的，但设置x-props时UI不会更新）

对于普通的Field，可以直接在JSX中指定visible，`<Field visible={false} />`
而对于布局组件，JSX中指定visible是无效的，需要通过`state.visible = true`进行动态设置

另外，对于FormTextBox这个布局组件来说，大部分情况下，只要FormTextBox是required，那么内部的字段都应该是必填的（求举反例），但是目前设置FormTextBox的required为true，只是影响label上红星的显示，需要把内部的字段各自设置required才行

**Comment by janryWang** [comment]
第一个问题，目前已经修了哈
第二个，我感觉还是可以支持的
第三个，这个就不用支持了，因为布局组件的职责是只负责布局样式相关的，不会干涉Field的校验，数据等核心逻辑

**Comment by wittech** [comment]
如果需要支持的话，需要用createControllerBox自己进行封装？
