### ISSUE TITLE
【bug】 stuck after custom components

### ISSUE THREAD

**Issue by YYL1999** [alibaba/uform#562]
when i use the custom components then uform becomes stuck  
my code 
```
registerFormField(
  'eventMeasure',
  formConnect()((props) => {
    const { disabled, allEventData, handleChange, event } = props;
    return (
      <EventMeasure
        disabled={disabled}
        allEventData={allEventData}
        event={event}
        onChange={handleChange}
      />
    );
  }),
);
```
the EventMeeasure is a packaged Select Component of antd

**Comment by YYL1999** [comment]
发现问题了 每一次onFieldChange事件触发都会导致registerField函数执行两次 通过测试发现Ufrom提供的onFieldChange事件比自定义组件的onChange事件晚2s执行

**Comment by janryWang** [comment]
给个codesandbox吧，晚2秒这种是很严重的性能问题了，从没发现过

**Comment by YYL1999** [comment]
> 给个codesandbox吧，晚2秒这种是很严重的性能问题了，从没发现过

稍等 在开会

**Comment by YYL1999** [comment]
> 给个codesandbox吧，晚2秒这种是很严重的性能问题了，从没发现过

最后升级版本了 之前0.4.3有这个问题  现在1.0.0-rc.0么得了
