### ISSUE TITLE
表单List里的字段无法编辑

### ISSUE THREAD

**Issue by LiHaoGit** [alibaba/uform#581]
1. How would you tag this issue?
  - Bug

2. Describe your issue:
表单List里的字段无法编辑
1.点击`新增维度`
2.编辑`维度名称`字段，无法编辑

![image](https://user-images.githubusercontent.com/7036191/71863299-63781d80-3137-11ea-8f7f-f70d16e85a51.png)

3. https://codesandbox.io/s/nostalgic-gagarin-2hbrb
.

**Comment by janryWang** [comment]
用法问题，Field array的子节点不要放虚拟节点，必须是数据节点，就是把FormLayout放到object里去
https://codesandbox.io/s/recursing-http-x2i26
