### ISSUE TITLE
question:调用mutators的change事件会导致表单全部渲染

### ISSUE THREAD

**Issue by YYL1999** [alibaba/uform#586]
每次调用mutators的change事件会导致表单的重新渲染 之前保存的值全部替换为初始值  请问是使用不当还是设计如此  
**避免如此我现在的做法是先将要修改的值深拷贝一份拿出来 调用remove移除掉要修改的部分 再调用insert将修改后的值插入 功能可以实现 但是有点low**

**Comment by janryWang** [comment]
提问题，在群里提
