### ISSUE TITLE
使用uform过程中的一些问题和疑惑

### ISSUE THREAD

**Issue by fchengjin** [alibaba/uform#591]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

 - Discussion

2. Describe your issue:
 - Which versions of UForm?
v1.0.0.rc1 @uform/antd

初次接触uform，并在项目中使用，感觉功能十分强大。但是有以下一些疑惑，希望可以解答一下。
1. 此前描述有问题，effects的subscribe中无法取得useState中真实的值[codeSandbox地址](https://codesandbox.io/s/uform-effects-depend-b0ol7)
```javascript
  const handleStepChange = useCallback(() => {
    console.log("stepChange", temp); // 始终为0 ，期望为2
  }, [temp]);
```

2. FormStep 无法设置current属性, 看源代码好像是组件内部维护的current,外部无法更新，但是文档上面有这个prop。[codeSandbox地址](https://codesandbox.io/s/currying-currying-ec5et)
![image](https://user-images.githubusercontent.com/28423685/72037094-e2a45780-32d7-11ea-9823-3c78ffb09087.png)

3. actions.validate() 只校验了出现在视野中的表单，当使用FormStep的时候没法全部校验。想要实现全部校验应该怎么处理。[codeSandbox地址](https://codesandbox.io/s/uform-formstep-verify-pdgex)

4. 路径匹配问题，这个应该是一个bug。
`*(phase.*.steps.*.type,phase.*.type)` 会只有一个匹配到。[codeSandbox地址](https://codesandbox.io/s/uform-formpath-ujptm)
```javascript
$("onFieldValueChange", "*(phases.*.type,phases.*.steps.*.type)").subscribe(
      fileState => {
        console.log(fileState.name); // 期望phases.*.steps.*.type也会触发
      }
    );
```

5. 使用FormStep时，如果使用useFormEffects的组件不是在第一页，其中一些生命周期不会触发。[codeSandbox地址](https://codesandbox.io/s/uform-lifecycle-gfbpt)

![image](https://user-images.githubusercontent.com/28423685/72037286-8db51100-32d8-11ea-8581-226d4b765a0c.png)

6. 假如现在有以下需求, [codeSandbox地址](https://codesandbox.io/s/nice-heisenberg-pdgex), 虽然通过hack的方式实现了，但是感觉姿势明显不对。有没有更合理的实现方式。这个比较复杂，麻烦耐心看下。
![image](https://user-images.githubusercontent.com/28423685/71956381-fdb68f00-3225-11ea-8b14-b2764fc1e4c1.png)

不好意思攒了这么多问题，希望大家不吝赐教😁

**Comment by janryWang** [comment]
每个问题都给一个codesandbox，并说明如何复现，注意codesandbox一定要保证是最小复现用例，不要带其他无关代码

**Comment by fchengjin** [comment]
> 每个问题都给一个codesandbox，并说明如何复现，注意codesandbox一定要保证是最小复现用例，不要带其他无关代码

你好，已全部更新为最小可复现用例。具体问题在代码也有注释。辛苦看下

**Comment by janryWang** [comment]
第一问题：effects内因为是需要保证引用不变，所以是不支持直接读useState的状态的，而且也不推荐在effects内部依赖外部状态，如果外部状态想依赖effects，可以通过调用actions.dispatch一个自定义事件，然后在effects内部以rxjs写法来处理，如果坚持这么用的话，建议用useRef创建一个持久引用来读取状态

第二个问题：current属性如果要读的话，官方是推荐借助FormSpy去处理，具体看看这个例子：https://codesandbox.io/s/z7nqn

第三个问题：设计就是这样的，分步表单校验，只会校验当前步的字段

第四个问题：的确是个bug，已经修复，可以npm update重试

第五个问题：使用useFormEffects，onFormMount,onFormInit，当前字段的onFieldMount，onFieldInit都无法监听到，因为执行到useFormEffects的时候，事件已经触发，这类初始化监听动作，可以直接写在useFormEffects主函数体内

第6个问题
监听onChange去调用dispatch就可以直接跳转了，可以看看这个例子 https://codesandbox.io/s/uform-formstep-verify-yblyx

**Comment by janryWang** [comment]
后面提issue尽量做到一个问题只提一个issue，不要汇总，这样不方便分发问题解决者

**Comment by wittech** [comment]
请问问题1，说的 采用rxjs的写法是指的是用rxjs的广播将变化的值传递到外部？或者说别的方法？

**Comment by fchengjin** [comment]
@wittech 
```javascript
const currentChange$ = createEffectHook("currentChange");
const actions = createFormActions();

const [current, setCurrent] = useState(0);
useEffect(() => {
    setTimeout(() => {
        setCurrent(2);
        actions.dispatch("currentChange", 2); // 出发自定义事件
    }, 100)
}, [])
const handleEffects =($) => {
    currentChange$().subscribe(payload => {
        console.log(payload); // 2
        // doSomething(payload)
    });
})
```
