### ISSUE TITLE
form表单的value值当中如果存在null值会触发表单初始化校验

### ISSUE THREAD

**Issue by LeslieHoward** [alibaba/uform#602]
1. How would you tag this issue?
- Bug

2. Describe your issue:

  - What is the current behavior?

> 初始化时，form表单的value值当中如果存在null值会触发校验

  - What is the expected behavior?

> 表单初始化不应该触发校验

      
  - Which versions of UForm?

> 1.0.0-rc.2

  - Did this work in previous versions of UForm?

> no

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
[https://codesandbox.io/s/lively-currying-zscpe](url)

**Comment by janryWang** [comment]
already fixed
