### ISSUE TITLE
[Bug] createVirtualBox与setFormState一块使用会导致页面展示数据与真实数据不一致

### ISSUE THREAD

**Issue by fchengjin** [alibaba/uform#608]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug

2. Describe your issue:

  - What is the current behavior?
![Kapture 2020-01-14 at 12 36 15](https://user-images.githubusercontent.com/28423685/72314698-e9adda00-36ca-11ea-8b80-54cce7a7fa97.gif)

  - What is the expected behavior?
![Kapture 2020-01-14 at 12 37 38](https://user-images.githubusercontent.com/28423685/72314704-f16d7e80-36ca-11ea-8474-9e4dbfc35717.gif)

  - Which versions of UForm?
1.0.0-rc.3

当未使用createVirtualBox时一切正常，使用createVirtualBox包装之后就会出现上面的异常。[codeSandbox地址](https://codesandbox.io/s/uform-setformstate-4yue8)

```javascript
actions.setFormState(state => Object.assign(state, t));
console.log(actions.getFormState()); // 此时获取的为想要的数据
setTimeout(() => { // 中间未做任何操作
   console.log(actions.getFormState()); // 此时获取的是页面展示的数据。但不是想要的数据
}, 0);
```

另外感觉actions.setFormState 这个api设计的有点别扭。应该是`setFormState(obj)`，或者是
`setFormState(state => {return newState;})` 会更合理一些

**Comment by janryWang** [comment]
存储和获取使用getFormGraph和setFormGraph
