### ISSUE TITLE
form表单的value值当中如果存在null值会触发表单初始化校验

### ISSUE THREAD

**Issue by LeslieHoward** [alibaba/uform#610]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

>   - Bug

2. Describe your issue:

  - What is the current behavior?

> 表单初始化的时候，如果数据中如果包含空字符串或者null值，会直接触发表单的校验

  - What is the expected behavior?

> 表单初始化不应该触发校验

  - Which versions of UForm?

> 1.0.0-rc.31.0.0-rc.3

  - Did this work in previous versions of UForm?

> no

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
[codesanbox address](https://codesandbox.io/s/lively-currying-zscpe)

**Comment by janryWang** [comment]
这个问题，为什么一定要传null。传undefined会导致什么问题吗？仔细看了下底层实现，是因为每个Field的默认值都是undefined，如果传null，uform会检测到null !== undefiend，从而触发field onChange，onChange触发就会触发校验逻辑。有两个方案：
1. 把null改为undefiend。
2. 给Field设置triggerType `<Field x-props={{triggerType:"onBlur"}}/>`
自行选择吧，目前来看，uform现在的逻辑是合理的
