### ISSUE TITLE
如何自定义默认校验规则的提示文案

### ISSUE THREAD

**Issue by yanqiw** [alibaba/uform#619]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:

  - What is the current behavior?
直接使用 registerField 方法，需要注册自定义的“必填文案”， 官网文档中没有相关说明。
经过查看代码逻辑，尝试用如下设置解决：
```javascript
rules=[{
required:true,
message:'自定义文案'
}]
```

  - What is the expected behavior?
希望官网文档加入更详细的关于规则自定义的说明
  - Which versions of UForm?
v1.0
  - Did this work in previous versions of UForm?
none

**Comment by quirkyshop** [comment]
校验可以查看这一小节的[Validation文档](https://uform-next.netlify.com/#/MpI2Ij/rRCmCPsOHO)

issue中的描述实际上是 **ValidateDescription** 类型的校验规则，后续文档会重构完善下，便于找到相关描述
