### ISSUE TITLE
重设表单值，重复值变为N/A

### ISSUE THREAD

**Issue by yinxuan1128** [alibaba/uform#626]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

2. Describe your issue:
想在同一个表单多次重载值，加载新值后，使用Reset,重新setState 表单值，结果跟前一次value值一样的字段全都变成N/A

场景重现：https://codesandbox.io/s/condescending-river-hisqj

**Comment by janryWang** [comment]
用法问题，把initialValues换成value就行了，主要原因是，value是可以支持多次赋值，但是initialValues只是针对首次为空的赋值有效
