### ISSUE TITLE
如何为createVirtualBox创建的自定义容器设置visible属性？

### ISSUE THREAD

**Issue by wittech** [alibaba/uform#632]
`export declare function createVirtualBox<T = {}>(key: string, component?: React.JSXElementConstructor<any>): React.FC<T & {
    name?: string;
    visible?: boolean;
    display?: boolean;
}>;`

在createVirtualBox的定义中有visible属性，但是在render中却无法获取到visible的值。

`<TableLayout title="标题" name="noname" visible={false} display={true}>
          <Field
            type="string"
            title="TextArea"
            name="textarea"
            x-component="textarea"
          />
          <Field type="boolean" title="开关选择" name="boolean" />
</TableLayout>`

`export const TableLayout = createVirtualBox<TableProps>(
  "table-layout",
  (props) => {
    return (
      <table>
        <tbody>
          {props.children}
        </tbody>
      </table>
    )
  }
);`

以上无法在props中获取到    name?: string;
    visible?: boolean;
    display?: boolean;
三个属性。难道容器组件不能用这几个参数？

**Comment by janryWang** [comment]
createVirtualBox的API是限制了用户只能拿x-component-props的属性，visible/display属性属于schema扩展属性，如果你想在自定义布局组件里拿到这些属性的话，可以使用createControllerBox
