### ISSUE TITLE
嵌套表单（一对一、一对多子表单）支持

### ISSUE THREAD

**Issue by jasl** [alibaba/uform#66]
RT，场景如报销申请单中的报销项目：

- 报销项目是一个子表单（可能内含报销项目、价格等字段），其有自己的字段验证规则
- 报销项目可能有0条至多条，由用户动态增加。
- 父表单（这里指报销申请单）有对子表单（报销项目）的验证，如数量（至少有一条，不可超过十条）
- 需考虑修改表单时对子表单数据的渲染和删除子表单项目时提交的结果方便服务器端处理

搜索过文档似乎没有发现关于嵌套表单相关的支持，请问 UForm 是否支持这一场景？或者以后是否计划实现？

**Comment by janryWang** [comment]
如果你所说的嵌套只是数据结构层面上的嵌套，那么UForm是天然支持的，因为它就是一个json schema，json schema是可以完全描述后端数据模型的

**Comment by jasl** [comment]
所以也就是说 JSON schema 支持嵌套 JSON Schema？并且嵌套的 JSON Schema 可以当做一个整体看待支持 Validation？

**Comment by janryWang** [comment]
> 所以也就是说 JSON schema 支持嵌套 JSON Schema？并且嵌套的 JSON Schema 可以当做一个整体看待支持 Validation？

是的，具体可以看看场景用例中的Array List场景，type="array"代表是一个数据容器，在其内部再做详细的表单描述，提交的时候是会自动构建出一个复杂数据结构。https://uformjs.org/#/YZCyCk/e3fefAFqug
