### ISSUE TITLE
[Umbrella] UForm Typescripts

### ISSUE THREAD

**Issue by janryWang** [alibaba/uform#69]
为了让UForm拥有更好的IDE编辑体验，在这里发起了对UForm的Typescripts支持项目，统一在next-ts分支上维护，欢迎大家PR贡献。
下面是完成进度。
- [x]  @uform/utils
  - [x]  accessor.ts
  - [x]  array.ts
  - [x]  broadcast.ts
  - [x]  case.ts
  - [x]  clone.ts
  - [x]  compare.ts
  - [x]  defer.ts
  - [x]  index.ts
  - [x]  isEmpty.ts
  - [x]  lru.ts
  - [x]  schema.ts
  - [x]  types.ts
- [x] @uform/validator
- [x]  @uform/core
- [x]  @uform/react
- [x]  @uform/antd
- [x]  @uform/next

**Comment by monkindey** [comment]
进度关联下对应的 PR 吧？

**Comment by janryWang** [comment]
@all-contributors please add yujiangshui for code and doc

**Comment by monkindey** [comment]
### 后续优化

* SchemaForm, Field, FormBlock 等组件的 props 都没有提示
* x-props 能不能自己用 next 或者 antd 的 type 接口定义？
* 代码 type 定义跟文档保持一样

**Comment by stkevintan** [comment]
@monkindey  可以先补全一些库的社区types，比如说@types/react, @types/react-dom, @types/style-component...这些直接npm安装就行了。
然后修掉现在eslint报warning的地方

然后x-props类型补全比较困难， 泛型不一定能搞定

**Comment by YikaJ** [comment]
看到这个 issue 昨天关闭了，是可以更新使用 typescript 了么，具体哪个版本支持了？谢谢。

**Comment by monkindey** [comment]
@YikaJ  最新版本 `v0.3.9` 支持了，可以试下，有问题可以直接反馈下哦。
