### ISSUE TITLE
不支持 json schema 协议的 additionalProperties 属性

### ISSUE THREAD

**Issue by wulucxy** [alibaba/uform#76]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

 **Bug**

2. Describe your issue:

没有实现 json-schema 的 additionalProperties 属性，导致对一些动态属性难以支持

**Comment by monkindey** [comment]
嗯嗯，感觉文档少了写上当前支持的 JSON schema 版本。还有你使用 additionalProperties 的场景是？

**Comment by wulucxy** [comment]
@janryWang 有进展么

**Comment by janryWang** [comment]
> @janryWang 有进展么

非常不好意思，因为最近其他事情影响，来不及支持这个需求，预计6月初投入支持该feature
