### ISSUE TITLE
文档缺少布局空间构成图示

### ISSUE THREAD

**Issue by monkindey** [alibaba/uform#77]
我看了部分文档，一些名称有点难于理解，比如：

![image](https://user-images.githubusercontent.com/6913898/58149211-8206d280-7c94-11e9-9013-705063f95d16.png)

我类比了 bizcharts，我觉得需要统一所有的名称还有他们对应的位置，这样子才能一目了然。

![image](https://user-images.githubusercontent.com/6913898/58149177-5daaf600-7c94-11e9-9d1d-36cbe69cb199.png)

**Comment by janryWang** [comment]
PR加一下吧
