### ISSUE TITLE
同一个 field 订阅了多个事件，如何保证先后顺序？

### ISSUE THREAD

**Issue by javahuang** [alibaba/uform#78]
我对 fieldA 订阅了两个个事件(eventA, eventB)来设置 fieldB 的值，并且每个事件都依赖 fieldB 的最新值，但是现在修改 fieldA 后，两个事件获取的都是 fieldB 的旧值，请教大家应该如何操作？

**Comment by janryWang** [comment]
答疑性问题，在群里问吧，issue主要用于提bug
