### ISSUE TITLE
Field的editable的问题

### ISSUE THREAD

**Issue by BlackSkyJY** [alibaba/uform#79]
Bug
问题： 
![image](https://user-images.githubusercontent.com/29111051/58164135-d1122f00-7cb7-11e9-8202-0923dc60c5ad.png)
如果Field上设置了editable在 SchemaForm上设定的editable，不会全局覆盖掉Field的editable

**Comment by janryWang** [comment]
这个是正常逻辑，Field上设置的优先级高于全局设置的
