### ISSUE TITLE
setFieldState同时设置loading和value未触发校验

### ISSUE THREAD

**Issue by cbozi** [alibaba/uform#82]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  setFieldState同时设置loading和value未触发校验

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox

.  https://codesandbox.io/s/dkywe

**Comment by janryWang** [comment]
```
return await actions.setFieldState("test", state => {
    state.loading = false;
    state.value = value;
  });
```
这里加个await就行了
