### ISSUE TITLE
missing "scripts/start.js" in packages/builder ?

### ISSUE THREAD

**Issue by mysansa52** [alibaba/uform#87]
1. How would you tag this issue?
  - Question
2. Describe your issue:
  when I try to start builder, find missing start.js .

**Comment by cnt1992** [comment]
> 1. How would you tag this issue?
> 
> * Question
> 
> 1. Describe your issue:
>    when I try to start builder, find missing start.js .

Just start the builder command in the root directory : `npm start`, and
